### ISSUE TITLE
Use test runner to execute the unit tests

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1004]
Investigate the use of common test runner (Karma or Venus.js, or other candidates) to run the unit tests.

The benefits:

* there is no need to write a special test runner
* execute the tests on e.g. Sauce Labs
* simplify the test fixture (individual test and expected result)

**Comment by ariya** [comment]
Note that AFAIK, Karma and Venus.js does not support running the tests on Node.js (or these days, io.js). Thus, at least we need to specialize the test runner for stand-alone JS environment vs browser environment.

**Comment by ariya** [comment]
Some historical context:

* https://code.google.com/p/esprima/issues/detail?id=336
* https://code.google.com/p/esprima/issues/detail?id=478
* https://code.google.com/p/esprima/issues/detail?id=606
* https://code.google.com/p/esprima/issues/detail?id=628

**Comment by nzakas** [comment]
Mocha works for both Node.js and browser tests. We use it for both ESLint and Espree.

**Comment by mikesherov** [comment]
@ariya, then I'll take this one and get mocha set up. Expect PR tomorrow.

**Comment by ariya** [comment]
@mikesherov Shouldn't you start with a test runner first (Karma or Venus.js)? Last time I checked, maybe it's changing already these days, the standard `mocha` runner doesn't automatically run the tests in (different) browsers.

**Comment by mikesherov** [comment]
@ariya, there are multiple concerns:

1. Using a test framework so we can unblock #1025 . For this, I'd like to use mocha.

2. Using a test runner so that local development can test in both node and browser environments. This requires karma, which itself requires a test framework, like mocha.

3. Getting that test runner to run both browser and node envs as part of CI. For this, we'd use saucelabs.

I'd like to tackle test framework first, because given that, test runner is essentially trivial.

**Comment by mikesherov** [comment]
Also, I think espree has already solved this problem in a way that makes tests easy to write and contribute: https://github.com/eslint/espree/blob/master/tests/lib/ecma-features.js

Mocha seems like natural starting point with karma then layered on top.

**Comment by ariya** [comment]
I don't really have any preference of a particular test library, mocha or any other.

Could you do me a favor and take a look at `test/parselibs.js`? It may be easier to see where I'm going after you glance at it. It could also show why I believe a test library does not bring much (not that I object or anything) since at most you will end up using the equality check.

Also, if you see the style of `test/parselibs.js`, the expected baseline (files under `test/3rdparty/syntax/`) contains the syntax tree and token array. No need to wrap it with `module.exports`. This makes it really trivial to generate the expected baseline (what `test/parselibs.js` does when a certain baseline does not exist yet).

See also commit f46263690 (/cc @eventualbuddha) since it is important to show the diff when something goes wrong. Perhaps mocha or even another assertion library has the ability to do that. If not, we can still use `json-diff`.

**Comment by nzakas** [comment]
A test library like Mocha is pretty huge for an open source project. There are already a ton of tools and documentation available, not to mention people who are familiar with it. It's one less thing people have to learn about before they can contribute.

@mikesherov let me know if you have any questions about what we did for testing in Espree. It's still not quite where I wanted to go with it.

**Comment by mikesherov** [comment]
> It's one less thing people have to learn about before they can contribute.

This. I don't think we need to reinvent the wheel here. As long as the resulting tests are small, easily identified when failing, and can be run on node and browsers both locally and in CI, we should be good.

I think using mocha, chai, leche, and karma address this issue while providing contributors familiarity.

**Comment by ariya** [comment]
Oh, I'm not anti-Mocha or anything. Mocha is definitely fantastic, that's why we use it for our [Shift AST JavaScript implementation](https://github.com/shapesecurity/shift-ast-js) (as well as my few personal projects).

All I ask is, let's review the requirements of such a test system and see what solution will emerge. Fair request @mikesherov?

**Comment by mikesherov** [comment]
@ariya, totally fair. The only reason I'd like to move forward quickly here is that espree has basically done all the work here and I'm envious of that test suite. Should be straightforward path without having to consume your time with what is essentially a trivial task here.

I'll review test/parselibs and saw that the commit added JSON diffing, but doesn't show the line number, which is the most frustrating thing about the test suite at the moment for me. Took me over an hour to fix tests when I landed consumeSemicolon changes because I had to wade through a >25K line test suite.

I think we have the same vision for the suite. Let me put something together and you can critique the code. Fair?

**Comment by ariya** [comment]
Showing the failing line number, or more general, the stack trace, is an example of a good requirement.

**Comment by mikesherov** [comment]
Yup, all comes free with mocha/karma.

**Comment by Attamusc** [comment]
@ariya @mikesherov I'd like to look into this, as I've been having a lot of pain updating the harmony module tests to validate token generation. Are you both cool with me looking into this, provided I receive some guidance from @ariya on requirements and @nzakas for lessons learned with espree's suite?

**Comment by ikarienator** [comment]
@mikesherov This issue and in general #1025 has HIGH importance and deserves high priority. It allows me to move much much faster than I can do now. The tremendous `test.js` file kills my WebStorm all the time and rebasing it is impossible. I'm kinda blocked by this issue right now.

**Comment by mikesherov** [comment]
Yes, we are all blocked by it. @deezus can you whip something up this weekend?

**Comment by Attamusc** [comment]
@mikesherov I'm not home this weekend, so the earliest I could look into this is probably Monday. If this needs something this weekend, feel free to have someone else pick this up.

**Comment by ikarienator** [comment]
@ariya @markelog @Attamusc I can split the tests into smaller files first if you like. For visual diff I will simply use [expect.js](https://github.com/Automattic/expect.js). If you are OK, I can finish it today.

**Comment by mikesherov** [comment]
Sounds good to me.

**Comment by nzakas** [comment]
You may want to look at Chai as well. Espree uses `assert.deepEqual()` to compare AST output. I'm not sure Expect.js does deep equality (doesn't appear so in the docs).

**Comment by ikarienator** [comment]
@nzakas I'm using expect.js with mocha in shift-parser currently. It supports deep equality test and it supports visual diff as well. Not sure if it's mocha's functionality or expect.js's. Let me try to reused the current runner first.

**Comment by nzakas** [comment]
:+1:

**Comment by ariya** [comment]
@Attamusc you might also want to take a look at PR #1075.

**Comment by markelog** [comment]
sounds good!

**Comment by jasonLaster** [comment]
@ariya @mikesherov, I'd be happy to investigate a test-runner like mocha or something simple that would allow tests to be run in the browser (aka devtools).

**Comment by mikesherov** [comment]
Sounds good!

**Comment by jasonLaster** [comment]
Just got an example test runner setup https://github.com/jasonLaster/esprima-test. If this looks good, I'll add a similar config to esprima. The basic setup is Karma, mocha, html2js (for fixtures). Worked really nicely.

**Comment by mikesherov** [comment]
@jasonLaster Awesome. Open an RFC pull request so we can continue the discussion there!

**Comment by ariya** [comment]
@jasonLaster Nice! Do you plan to write a custom Karma adapter or do you want to utilize Mocha? I personally think that there is no major advantage of using Mocha because the way our tests are organized is: input -> process -> output, verify output vs baseline. Unless you want to convert every single one into the the BDD style of `describe(...)`.

**Comment by jasonLaster** [comment]
@mikesherov will open when I'm back at my computer. 

@ariya I personally prefer espree's bdd style with describe / it because the tests seem to read better. Also, I believe they have some interesting helpers that are worth investigating. I remember one being latte. My fear with this approach is scope creep. Let me investigate a little further and report back. What are your thoughts on a bdd approach? 

One potential concern I have with using html2js is that the content won't be copied over exactly. I.e. Will be escaped poorly. I'll share if anything comes up there

**Comment by jasonLaster** [comment]
@mikesherov I think a lot of the questions are with the test style. I think it'll be simpler to focus on just the environments. 

@ariya I'll probable go with the smallest possible changeset. I like mochas reporter, so hopefully we can do something simple and evolve the test style gradually. People have lots of good ideas in this thread.

One potential concern I have with using html2js is that the content won't be copied over exactly. I.e. Will be escaped poorly. I'll share if anything comes up there

**Comment by jasonLaster** [comment]
Couple updates:
+ started a branch [karma-test](https://github.com/jquery/esprima/compare/master...jasonLaster:test-runner?expand=1)
+ made a couple tweaks to html2js ([diff](https://gist.github.com/jasonLaster/f4b53746792d1b159ef1)) to escapse line breks
+ invalid syntax fixtures failed to load with html2js so i deleted the files temporarily. I'm thinking we'll want to escape more agressively.
+ some other files failed to load as well. One of them was a unicode issue, but i'm not sure about the others
+ at this point, most of the files are loaded and I'm going to focus on refactoring runner.js to run through the cases.


One of the ideas I have for more aggressive escaping is a hack that i've seen for javascript templates. The idea is that the karma-preprocessor would put the file content inside of a function declaration, who's body is multiline comment `function(){ /*  <content goes here> */ }`. That way the runner can get the content by doing Function.toString() later. Lets say the karma pre-processor saw the content `/*var x = /[\u{61}-b][\u0061-b][a-\u{62}][a-\u0062]\u{1ffff}/u;*/` it would replace it with `function() {/*var x = /[\u{61}-b][\u0061-b][a-\u{62}][a-\u0062]\u{1ffff}/u;*/}` that way, `toString()` would return the body of the function as a string that could then be trimmed. I think this has a decent chance of working, thoughts?

**Comment by ariya** [comment]
Thanks the heroic effort of @jasonLaster, this is now implemented! I think we can safely resolve this task as subsequent enhancements can be filed separately (e.g. #1259 for Sauce Labs testing, #1258 for test runner unification).

**Comment by jasonLaster** [comment]
Great!
