### ISSUE TITLE
Parameters in ArrowFunctionExpression are not checked against strict mode in certain circumstances

### ISSUE THREAD

**Issue by ikarienator** [jquery/esprima#1010]
Parameters in ArrowFunctionExpression are not checked against strict mode restrictions if the strict mode is entered by a use strict directive directly inside the body.

For example:
```es6
eval => { "use strict"; }
```
should be an early error.

ArrowFunctionExpression also does not allow duplicate parameters, which is different from other simple parameter list.

**Comment by ariya** [comment]
The harmony branch is deprecated.

Meanwhile, in the master branch, I've tested the following and got the result:

(1) Strict mode restriction:
```
esprima.parse('eval => {"use strict"}')
```
will throw "Parameter name eval or arguments is not allowed in strict mode".

(2) Duplicated parameter name:
```
esprima.parse('(a, a) => y')
```
will throw "Strict mode function may not have duplicate parameter names".

I think it's safe to say that this is now working properly. Nevertheless, I will add extra tests to prevent any future regression.
