### ISSUE TITLE
arrowExpression vs ArrowFunctionExpression

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1013]
From @rreverser in https://code.google.com/p/esprima/issues/detail?id=567

> What steps will reproduce the problem?
> 1. Parse 'x => 1' with esprima.parse to `ast` variable.
> 2. Check out type of `ast.body[0].expression`.
> 
> What is the expected output?
> 'ArrowExpression' (as stated on https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API page)
> 
> What do you see instead?
> 'ArrowFunctionExpression'
> 
> I suppose this is by design, but would be great to fix either MDN wiki page or Esprima's output type so all the AST tools developers could follow the same specification and expect same results.

**Comment by fkling** [comment]
A fix for that is already in the harmony branch: 0e4014d2e0d4c024c3481acdad7e7a813195527b

**Comment by ariya** [comment]
Related SpiderMonkey issue : https://bugzilla.mozilla.org/show_bug.cgi?id=913617.

**Comment by ariya** [comment]
With https://github.com/estree/estree/issues/2 resolves to Mozilla/SM changing to `ArrowFunctionExpression`, we don't need to change Esprima's to `ArrowFunction`.
