### ISSUE TITLE
VariableDeclarator + ArrowFunctionExpression with named parameter throw 'Unexpected token =>'

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1014]
From  @termi in https://code.google.com/p/esprima/issues/detail?id=483

> What steps will reproduce the problem?
> Parse 'let test1 = ({a}) => ([a])' using esprima#harmony
> 
> What is the expected output?
> AST
> 
> What do you see instead?
> Error: Line 1: Unexpected token =>

Suggested Fix:
https://github.com/termi/es6-transpiler/blob/e99435f45aad8cac89c04208d1c33b4a7a57422f/lib/esprima_harmony.js#L3130#L3131

**Comment by fkling** [comment]
A fix for that is already in the harmony branch: 0e4014d2e0d4c024c3481acdad7e7a813195527b

**Comment by mikesherov** [comment]
Thanks @fkling!

**Comment by ikarienator** [comment]
I recently found out that all the cases can be handled together directly in `parseGroupExpression`. We will have a much elegant way of dealing with `ArrowFunctionExpression`s soon.
