### ISSUE TITLE
Travis CI should run the tests with Node.js 0.12 and io.js

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1015]
Now that Node.js 0.12 has been [released](http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/), that is what should be used instead of 0.11.

In addition, io.js should be tested as well.

**Comment by michaelficarra** [comment]
There are still a lot of people running `0.11`. You should keep that one around for a while until more people adopt `0.12`.
