### ISSUE TITLE
ES6: `as` in token list listed as "Identifier"

### ISSUE THREAD

**Issue by Attamusc** [jquery/esprima#1020]
While working through adding tokens to the `harmonymoduletest` file, I've stumbled on something that I'm not sure is a bug, but seems off: In all `import` and `export` statements, `as` is listed as an "Identifier", when it seems like it should be a "Keyword".

The spec doesn't seem to list it as a keyword, but the syntax section of export (https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports) seems like, given the export/import context, it should be one.

**Comment by michaelficarra** [comment]
It is not a keyword, it is a contextual keyword. It can be used as an identifier in most places.

**Comment by mikesherov** [comment]
Cool, so then not a bug. Just making sure! Thanks @michaelficarra
