### ISSUE TITLE
As part of CI, run the test suite of major downstream projects

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1023]
Known consumers:

 * ESLint
 * JSCS
 * Istanbul
 * Escope (https://github.com/estools/escope)
 * Escodegen (https://github.com/estools/escodegen)
 * jstransform 
 * 6to5?
 * recast?
 * @ariya @ikarienator @jeffmo others?

**Comment by ariya** [comment]
As long eslint is using espree, it won't be easy (requires some tweaking).

**Comment by nzakas** [comment]
The parser is configurable: http://eslint.org/docs/configuring/#specifying-parser

If that's not enough, let me know what you need.

**Comment by ariya** [comment]
@nzakas If that is enough to run ESLint unit tests, I think it should be sufficient.

**Comment by nzakas** [comment]
It probably depends on how you run the tests, but I think it should work. We set the parser in this file: https://github.com/eslint/eslint/blob/master/conf/eslint.json

**Comment by mikesherov** [comment]
@nzakas only problem is that the suite currently relies on behavior only espree provides.

If we're dedicated to doing this, it would make sense for us to begin work on converging the two projects, at least for the parts that aren't add ons like jsx.

**Comment by nzakas** [comment]
Outside of JSX and `globalReturn`, the rest are ES6 features that Esprima harmony already supports.

**Comment by mikesherov** [comment]
Right, my point being we'd need a way to ignore those tests. Thoughts?

**Comment by ariya** [comment]
@mikesherov It might need a simple pre-processing step, e.g. removing files for unsupported tests.

**Comment by jeffmo** [comment]
Can we add `jstransform` and `6to5` in that list too?
(I suppose we need to just get to writing code and pull requesting here...)

**Comment by mikesherov** [comment]
Exactly. @jeffmo add at to the description at will, and let's turn it into a checklist :-)

**Comment by fkling** [comment]
`recast`, although it is using esprima-fb by default.

**Comment by mikesherov** [comment]
@fkling how can we configure it to use regular esprima?

**Comment by fkling** [comment]
@mikesherov: it's `parse` method accepts an `esprima` [option](https://github.com/benjamn/recast/blob/master/lib/options.js). However, the tests don't seem to be configurable, but I guess one could simply alias `esprima-fb` to `esprima` in the test environment. cc @benjamn who wrote recast.

**Comment by benjamn** [comment]
Happy to make the tests configurable, but not immediately sure what the best way to do that is…

**Comment by ariya** [comment]
Also, if `jstransform`and `recast` have some tests requiring features not yet supported, then we need a mechanism to exclude those tests.

**Comment by jeffmo** [comment]
Oh right, I forgot that these CI tests will need to run with master -- maybe we should hold off on adding them to CI until master is close enough to harmony that we can switch esprima-fb over to tracking master (and then perhaps it would make more sense to just make esprima-fb include `recast` and `jstransform` in it's forked form of the CI tests)

**Comment by fkling** [comment]
> perhaps it would make more sense to just make esprima-fb include recast and jstransform in it's forked form of the CI tests

That's what I was thinking as well.
