### ISSUE TITLE
Destructuring Defaults

### ISSUE THREAD

**Issue by xjamundx** [jquery/esprima#1028]
All of the following are valid ES6 and fail in current `harmony`:

- `function a({x = 10}) {}` 
- `function a({x = 10, y: { z = 10 }}) {}`
- `({x = 10}) => x`
- `({x = 10, y: { z = 10 }}) => [x,y]`
- `[a=10] = 0`
- `var {a = 10} = {}`

Much more information about the expected implementation can be found here:
https://github.com/estree/estree/issues/13

**Comment by sebmck** [comment]
None of those are default parameters, they're destructuring defaults.

**Comment by xjamundx** [comment]
Yes, that's what I meant :-p

**Comment by ariya** [comment]
Define "in current Esprima": which  branch etc?

**Comment by xjamundx** [comment]
`harmony` and `master` (I'm sort of unclear as to which I should be targetting)

**Comment by xjamundx** [comment]
Latest `master`

```
>  var e = require('./esprima'); e.parse('function a({x = 10}) {}');
Error: Line 1: Unexpected token {
    at createError (/Users/jamuferguson/dev/esprima/esprima.js:2004:21)
    at unexpectedTokenError (/Users/jamuferguson/dev/esprima/esprima.js:2072:13)
    at throwUnexpectedToken (/Users/jamuferguson/dev/esprima/esprima.js:2077:15)
    at parseVariableIdentifier (/Users/jamuferguson/dev/esprima/esprima.js:2981:17)
    at parseParam (/Users/jamuferguson/dev/esprima/esprima.js:3693:17)
    at parseParams (/Users/jamuferguson/dev/esprima/esprima.js:3722:22)
    at parseFunctionDeclaration (/Users/jamuferguson/dev/esprima/esprima.js:3764:15)
    at parseSourceElement (/Users/jamuferguson/dev/esprima/esprima.js:3841:24)
    at parseSourceElements (/Users/jamuferguson/dev/esprima/esprima.js:3877:29)
    at parseProgram (/Users/jamuferguson/dev/esprima/esprima.js:3894:16)
```

**Comment by ariya** [comment]
If it's master, then isn't it to be expected? After all, there is no destructuring support at all in the master branch as of now.

**Comment by ariya** [comment]
For the harmony branch, this is the old bug: https://code.google.com/p/esprima/issues/detail?id=565. We shall start tracking it from here onwards.

**Comment by xjamundx** [comment]
Great, yes, sorry I wasn't sure if `harmony` was still supported with `master` having so much ES6 support now.

**Comment by xjamundx** [comment]
FWIW the shift-parser implementation for `var {x = 10} = x` looks like:

```js
{ type: 'Script',
  body: 
   { type: 'FunctionBody',
     directives: [],
     statements: 
      [ { type: 'VariableDeclarationStatement',
          declaration: 
           { type: 'VariableDeclaration',
             kind: 'var',
             declarators: 
              [ { type: 'VariableDeclarator',
                  binding: 
                   { type: 'ObjectBinding',
                     properties: 
                      [ { type: 'BindingPropertyIdentifier',
                          identifier: 
                           { type: 'BindingIdentifier',
                             identifier: { type: 'Identifier', name: 'x' } },
                          init: { type: 'LiteralNumericExpression', value: 10 } } ] },
                  init: 
                   { type: 'IdentifierExpression',
                     identifier: { type: 'Identifier', name: 'x' } } } ] } } ] } }
```

**Comment by xjamundx** [comment]
The acorn implementation of `var {x = 10} = x` looks like:

```js
{ type: 'Program',
  start: 0,
  end: 16,
  body: 
   [ { type: 'VariableDeclaration',
       start: 0,
       end: 16,
       declarations: 
        [ { type: 'VariableDeclarator',
            start: 4,
            end: 16,
            id: 
             { type: 'ObjectPattern',
               start: 4,
               end: 12,
               properties: 
                [ { type: 'Property',
                    start: 5,
                    end: 11,
                    method: false,
                    shorthand: true,
                    computed: false,
                    key: { type: 'Identifier', start: 5, end: 6, name: 'x' },
                    kind: 'init',
                    value: 
                     { type: 'AssignmentPattern',
                       start: 5,
                       end: 11,
                       operator: '=',
                       left: { type: 'Identifier', start: 5, end: 6, name: 'x' },
                       right: { type: 'Literal', start: 9, end: 11, value: 10, raw: '10' } } } ] },
            init: { type: 'Identifier', start: 15, end: 16, name: 'x' } } ],
       kind: 'var' } ] }
```

**Comment by xjamundx** [comment]
Here's the PR for espree that fixes this. Code should be pretty reusable here:
https://github.com/eslint/espree/pull/62

**Comment by ariya** [comment]
> This seems pretty trivial to add to harmony. Is this just waiting for someone to copypasta PR?

The harmony branch won't be maintained anymore, see #1172 for details.

**Comment by ariya** [comment]
All the 6 example snippet is now working properly in the current master branch, implemented by @ikarienator in #1045. Since the harmony branch is obsoleted, I'm also closing this issue.

**Comment by chriscoyier** [comment]
Excuse my ignorance here, but I'm trying to figure something out about destructuring and esprima.

Running master branch / v3.1.2

Start with:

```
const {a=1, b=2} = {a:2};
```

Output from esprima:

```
const {a, b} = { a: 2 };
```

Which leaves `b` undefined. 

That's a problem, yeah?

**Comment by hydroper** [comment]
@chriscoyier CSSTricks author here xº

**Comment by ariya** [comment]
@chriscoyier Are you perhaps thinking of Escodegen? Esprima parser is only one way, _code-to-AST_, and not in the other direction.

**Comment by chriscoyier** [comment]
Ah yes, see, I knew you'd have to excuse my ignorance. Indeed that is the library involved here. I was able to upgrade to 1.8.0 of it and the problem remains.

It seems like both libraries are involved in a conversion though? (At CodePen, we use both to instrument the JS to attempt to do things like catch infinite loops). So it's fairly certain that esprima is doing it correctly to the AT side but Escodegen is doing it incorrectly back to JS?

**Comment by ariya** [comment]
@chriscoyier From Esprima side, the easiest way to verify it is to use http://esprima.org/demo/parse.html. Your snippet does not present any problem (it produces the correct AST).
