### ISSUE TITLE
ES6 feature: Generator: Tracking Issue

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1033]
## Syntax:

Per Rev 32 (Feb 2, 2015) of the draft spec, the relevant grammar is on [Section 14.4](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions) *Generator Function Definitions*:

<pre>
<i>GeneratorMethod</i><sub>[Yield]</sub> :
    <b>*</b> <i>PropertyName</i><sub>[?Yield]</sub> <b>(</b> <i>StrictFormalParameters</i><sub>[Yield,GeneratorParameter]</sub> <b>)</b>  <b>{</b> <i>GeneratorBody</i><sub>[Yield]</sub>  <b>}</b>

<i>GeneratorDeclaration</i><sub>[Yield, Default]</sub> :
    <b>function</b> <b>*</b> <i>BindingIdentifier</i><sub>[?Yield]</sub> <b>(</b> FormalParameters<sub>[Yield, GeneratorParameter]</sub> <b>)</b> <b>{</b> <i>GeneratorBody</i><sub>[Yield]</sub> <b>}</b>
    [+Default] <b>function</b> <b>*</b> <b>(</b> <i>FormalParameters</i><sub>[Yield, GeneratorParameter]</sub> <b>)</b> <b>{</b> <i>GeneratorBody</i><sub>[Yield]</sub> <b>}</b>

<i>GeneratorExpression</i> :
    <b>function</b> <b>*</b> <i>BindingIdentifier</i><sub>[Yield]</sub><sub>opt</sub> <b>(</b> <i>FormalParameters</i><sub>[Yield,GeneratorParameter]</sub> ) <b>{</b> <i>GeneratorBody</i><sub>[Yield]</sub> <b>}</b>

<i>GeneratorBody</i><sub>[Yield]</sub> :
    <i>FunctionBody</i><sub>[?Yield]</sub>

<i>YieldExpression</i><sub>[In]</sub> :
    <b>yield</b>
    <b>yield</b> [no LineTerminator here] [Lexical goal InputElementRegExp] <i>AssignmentExpression</i><sub>[?In, Yield]</sub>
    <b>yield</b> [no LineTerminator here] <b>*</b> [Lexical goal InputElementRegExp] <i>AssignmentExpression</i><sub>[?In, Yield]</sub>

<i>AssignmentExpression</i><sub>[In, Yield]</sub> :
    [+Yield] <i>YieldExpression</i><sub>[?In]</sub>
</pre>

## Spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions

Relevant AST interfaces (from https://github.com/estree/estree):

Functions:

```js
extend interface Function {
    defaults: [ Expression ];
    rest: Identifier | null;
    generator: boolean;
}
```

```js
interface ArrowExpression <: Function, Expression {
    type: "ArrowExpression";
    params: [ Pattern ];
    defaults: [ Expression ];
    rest: Identifier | null;
    body: BlockStatement | Expression;
    generator: boolean;
    expression: boolean;
}
```

YieldExpression:

```js
interface YieldExpression <: Expression {
    type: "YieldExpression";
    argument: Expression | null;
}
```
See also:
  * Esprima generator support from harmony branch: https://code.google.com/p/esprima/issues/detail?id=287
  * V8 generator support: https://code.google.com/p/v8/issues/detail?id=2355

## Remaining Tasks:

 - [ ] Review V8 error messages on generator early error
 - [ ] Ensure the proper handling of `yield*` (old issue [617](https://code.google.com/p/esprima/issues/detail?id=617))

**Comment by ariya** [comment]
@jeffmo Here's the generator tracking issue, in case you want to grab this.

**Comment by jeffmo** [comment]
David (@dhe128) mentioned he'd be interested in giving generator support a go -- so cc'ing him here for reference

**Comment by nzakas** [comment]
Was ArrowExpression vs. ArrowFunctionExpression resolved?

**Comment by jeffmo** [comment]
Hmm, well there isn't such a thing as generator arrow functions in ES6...

**Comment by nzakas** [comment]
Good point, my comment was based on the inclusion of ArrowExpression as part of the relevant AST information in the description. It seems like `generator` is still there so all nodes representing functions have the same properties?
