### ISSUE TITLE
In the benchmark, the "holding on" array should be cleared each run to reduce swapping overhead.

### ISSUE THREAD

**Issue by ikarienator** [jquery/esprima#1035]
In the benchmark:

```js
function () {
    var syntax = esprima.parse(source, { range: true, loc: true });
    tree.push(syntax.body.length);
}
```

The "holding on" array `tree` should be cleared each run to reduce swapping overhead. `gc()` should be called right after it.

**Comment by ikarienator** [comment]
The difference should have been existing in principle but turned out to be not significant in experiments.

before:
<pre>
Has exposed gc().
    Underscore 1.5.2    42.5 KiB      4.71 ms ± 1.66%
      Backbone 1.1.0    58.7 KiB      4.49 ms ± 0.63%
      MooTools 1.4.5   156.7 KiB     23.20 ms ± 0.87%
        jQuery 1.9.1   262.1 KiB     23.63 ms ± 0.59%
          YUI 3.12.0   330.4 KiB     23.11 ms ± 0.82%
 jQuery.Mobile 1.4.2   442.2 KiB     86.33 ms ± 6.54%
       Angular 1.2.5   701.7 KiB     63.25 ms ± 7.09%
                     ------------------------
                      1994.3 KiB    228.72 ms ± 5.50%
</pre>

after:
<pre>
Has exposed gc().
    Underscore 1.5.2    42.5 KiB      4.65 ms ± 1.42%
      Backbone 1.1.0    58.7 KiB      4.45 ms ± 0.85%
      MooTools 1.4.5   156.7 KiB     23.82 ms ± 1.43%
        jQuery 1.9.1   262.1 KiB     25.23 ms ± 1.81%
          YUI 3.12.0   330.4 KiB     23.95 ms ± 1.18%
 jQuery.Mobile 1.4.2   442.2 KiB     82.84 ms ± 5.03%
       Angular 1.2.5   701.7 KiB     64.53 ms ± 8.33%
                     ------------------------
                      1994.3 KiB    229.46 ms ± 5.43%
</pre>

**Comment by ariya** [comment]
Seems that the difference hardly matters. Do you also think it's because that `tree` array is so small anyway (and storing just plain numbers).

**Comment by ikarienator** [comment]
The `tree` array really small. I was wrong about this. So since we are not storing the tree, the gc cost is actually low. Changing the behavior shouldn't have a significant difference. I'll close this issue.
