### ISSUE TITLE
ES6 feature: computed property name

### ISSUE THREAD

**Issue by ikarienator** [jquery/esprima#1037]
## Syntax:
<pre>
<i>ComputedPropertyName</i>[Yield] :
    <b>[</b> <i>AssignmentExpression</i><sub>[In, ?Yield]</sub> <b>]</b>
</pre>

**Referred to by:**
<pre>
<i>PropertyName</i>[Yield,GeneratorParameter] :
    <i>LiteralPropertyName</i>
    [+GeneratorParameter] <i>ComputedPropertyName</i>
    [~GeneratorParameter] <i>ComputedPropertyName</i><sub>[?Yield]</sub>
</pre>

## Early errors:

None.

## Spec:
[12.2.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer) Object Initializer

## See also
[Esprima issue on Google Code](https://code.google.com/p/esprima/issues/detail?id=552)
[V8 support for computed property names](https://code.google.com/p/v8/issues/detail?id=3754)
[Error messages in V8](https://github.com/v8/v8-git-mirror/blob/4.2.70/src/messages.js)

**Comment by ikarienator** [comment]
Continuing on the discussion, some issues:

0. the value is alway computed. Therefore to me a `computed` flag does not feel like its referring to the value.
0. type `Literal | Identifier | Expression` will be simply `Expression`.

My suggestion will be:

```webidl
interface ObjectExpression <: Expression {
    type: "ObjectExpression";
    properties: [ Property ];
}

interface Property {
    kind: "init" | "get" | "set";
    name: Expression;
    computed: boolean;
    value: Expression;
}
```

**Comment by mikesherov** [comment]
@ikarienator is the proposal here diff from SpiderMonkey? If so, file an issue at estree too please?

**Comment by ariya** [comment]
@ikarienator I agree with @mikesherov. Since `computed` flag is already becoming almost the de-facto standard, we should stick with this for now and brainstorm the further enhancement at estree.

**Comment by ikarienator** [comment]
This is only migrating the google code issue to here. I have checked estree yet.

**Comment by ikarienator** [comment]
I checked estree and it does not include much es6 contents. It does not include computed property name among other features. Why do we want to keep sync with it? https://github.com/shapesecurity/shift-spec/tree/es6 has a very complete and up to date definition of ES6 AST and very few issues if any. It is described in a compilable WebIDL. We can probably be more compliant to that than estree.

**Comment by mikesherov** [comment]
Let's discuss at the meeting on Wednesday then. The idea is compat with acorn and spidermonkey, several of which have living breathing es6 implementations in current versions.

**Comment by ariya** [comment]
@ikarienator Unfortunately that how's been implemented in the harmony branch so far. It seems to be less troublesome to support incremental addition, even it's not perfect, in the current situation.

**Comment by ikarienator** [comment]
Make sense. I will create issues in estree to address missing features that
has been implemented in harmony and master. Michael, what is the problem
preventing us from having a maximally additive ES6 AST in shift spec?

**Comment by ariya** [comment]
BTW, the more proper old bug to be referred is this one: https://code.google.com/p/esprima/issues/detail?id=480. The corresponding harmony branch implementation is in commit 2bb17ef9a4.

**Comment by ikarienator** [comment]
Thanks! Interesting... I may want move `computed` to the end of the `finishProperty` method.

**Comment by ariya** [comment]
There is also commit `54f49ada87`, make sure we include the test case so that it is also covered.
