### ISSUE TITLE
ES7 feature: Array Comprehension

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1038]
## Syntax:

(TBD)

## Spec:

(TBD)

Relevant AST interfaces (from https://github.com/estree/estree): (TBD)

## Early Errors:

(TBD)

## Related Tasks:

- [ ] Ensure that binding patterns are supported (old [issue 570](https://code.google.com/p/esprima/issues/detail?id=570))

**Comment by ariya** [comment]
Since the harmony branch is gone and Facebook is moving away from its fork of Esprima, I'd say we put this on hold. I'm also not sure at which stage (of https://github.com/tc39/ecma262) this feature already is.

**Comment by michaelficarra** [comment]
Stage 0, unlikely to happen in the next few years.
