### ISSUE TITLE
Tolerate missing ) for if/for/while

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1042]
Consider the following test code (parsing in tolerant mode):

```js
require('./esprima').parse('if(foo.bar === 1', { tolerant: true })
```

The current master branch will thrown an exception due to the error `Line 1: Unexpected end of input`.

If this feature is implemented, it will return an AST because the missing `)` is tolerated. The error will be still listed in the `errors` array.

(Migrated from https://code.google.com/p/esprima/issues/detail?id=553, as reported by @mrennie)

**Comment by ariya** [comment]
> It would be extremely helpful for content assist / linting / occurrence computations if we could tolerate the missing ')'. 
>
> A real and very common scenario for this kind of recovery is:
> 
> `if(myobj.` activate content assist

**Comment by gorkem** [comment]
After this change I was expecting `if(foo() {}` to be tolerated and parsing to finish without throwing exceptions. I am getting a  `Unexpected token }` is this the expected result?
