### ISSUE TITLE
`export default class A {}` should treat `class A {}` as a ClassExpression, not a ClassDeclaration

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1049]
**What steps will reproduce the problem?**

```js
esprima.parse("export default class A {}")
```

**What is the expected output?**

The AST node for `class A {}` should be a ClassExpression because the thing that follows `export default` is an AssignmentExpression.

**What do you see instead?**

Currently the tip of the harmony branch does not work properly with `export default`. However, with a working `export default` (SHA=4be906f1abcbb), the AST node for `class A {}` is a ClassDeclaration.

**What version of the product are you using? On what operating system? Which
browser?**

As mentioned above, esprima#harmony is broken for `export default` (#410). The SHA I've been using for `export default`, 4be906f1abcbb, works for everything I've checked except classes. This is tested in Node.js v0.10.x, but I doubt that matters.

(Migrated from https://code.google.com/p/esprima/issues/detail?id=543, as filed by @eventualbuddha)

**Comment by ikarienator** [comment]
By the current spec, it should be a `ClassDeclaration`. https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports

**Comment by eventualbuddha** [comment]
@ikarienator is correct. This issue is no longer relevant and should be closed.

**Comment by ariya** [comment]
Closing as it doesn't apply anymore.
