### ISSUE TITLE
Function declarations are mistakenly allowed in non-{function,program} contexts

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1051]
Filed by @michaelficarra previously as [issue 422](https://code.google.com/p/esprima/issues/detail?id=422).

**What steps will reproduce the problem?**

```js
try {} catch(e) { function a() }
if(b) { function c(){} }
if(d) function e(){}
```

**What is the expected output?**

Syntax Error

**What do you see instead?**

A parse with `FunctionDeclarations` throughout.

**What version of the product are you using? On what operating system? Which browser?**

Online parser demo.

**Comment by ikarienator** [comment]
This is one of the intentional difference between the spec and our implementation. We should close this. cc @michaelficarra

**Comment by michaelficarra** [comment]
By *our*, you mean the Shfit parser. This is esprima. Also, duplicate of #1053?

**Comment by ikarienator** [comment]
No, I meant esprima. It is also a JavaScript parser instead of a ECMAScript
parser. It supports let/const and XML style comment in ES5 branch.

**Comment by ariya** [comment]
Documented as intentional compatibility (#1436).
