### ISSUE TITLE
FunctionDeclaration parsing too permissive

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1053]
Filed by @michaelficarra previously as [issue 464](https://code.google.com/p/esprima/issues/detail?id=464).

**What steps will reproduce the problem?**

FunctionDeclarations are allowed pretty much wherever a Statement is allowed, which causes esprima to accept strings that are not JavaScript programs, such as the following:

```js
  { function a(){} }
```
or
```js
  while(0) function a(){}
```

**What is the expected output?**

I'd expect a parse failure.

**What do you see instead?**

Invalid SpiderMonkey ASTs.

**What version of the product are you using? On what operating system? Which browser?**

master

**Comment by ariya** [comment]
A possible compromise might be needed here. See also ES5 [Section 12](http://es5.github.io/#x12) *Statements*:

> NOTE Several widely used implementations of ECMAScript are known to support the use of FunctionDeclaration as a Statement. However there are significant and irreconcilable variations among the implementations in the semantics applied to such FunctionDeclarations. Because of these irreconcilable difference, the use of a FunctionDeclaration as a Statement results in code that is not reliably portable among implementations. It is recommended that ECMAScript implementations either disallow this usage of FunctionDeclaration or issue a warning when such a usage is encountered. Future editions of ECMAScript may define alternative portable means for declaring functions in a Statement context.

**Comment by michaelficarra** [comment]
The former is allowed as of ES6. The latter is still an error.

**Comment by ariya** [comment]
Documented as intentional compatibility (#1436).
