### ISSUE TITLE
Do not allow duplicate labels across function expression boundaries

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1054]
Filed by @michaelficarra previously as [issue 561](https://code.google.com/p/esprima/issues/detail?id=561).

**What steps will reproduce the problem?**

Attempt to parse `a: !function(){ a:; }`.

**What is the expected output?**

A parse failure.

**What do you see instead?**

An AST.

What version of the product are you using? On what operating system? Which browser?

esprima.org: http://esprima.org/demo/parse.html?code=a%3A%20!function%20a()%20%7B%20a%3A%3B%20%7D

**Please provide any additional information below.**

Remember that duplicate labels are allowed across function declaration boundaries, as in `a: function a(){ a:; }`.

**Comment by bakkot** [comment]
I believe that program is valid. At least, browsers and [Shift](http://shift-ast.org/parser.html?code=a:%20!function(){%20a:;%20}&type=Script) accept it, and [per spec](https://tc39.github.io/ecma262/#sec-statement-semantics-static-semantics-containsduplicatelabels) `ContainsDuplicateLabels` of `ExpressionStatement` is unconditionally `false`.

@michaelficarra, can you clarify?

**Comment by michaelficarra** [comment]
@bakkot This was true during ES5. See ES5 §[12.12](http://es5.github.io/#x12.12).

> An ECMAScript program is considered syntactically incorrect if it contains a LabelledStatement that is enclosed by a LabelledStatement with the same Identifier as label. This does not apply to labels appearing within the body of a FunctionDeclaration that is nested, directly or indirectly, within a labelled statement.

I think we fixed it in the ES6 timeframe, and that appears to be confirmed by the section of the spec that you linked.

**Comment by ariya** [comment]
Closing this as it does not apply anymore.
