### ISSUE TITLE
Do not allow function declarations to be labelled

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1055]
Filed by @michaelficarra previously as [issue 562](https://code.google.com/p/esprima/issues/detail?id=562).

**What steps will reproduce the problem?**

Attempt to parse `a: function b(){}`.

**What is the expected output?**

A parse failure.

**What do you see instead?**

An AST.

**What version of the product are you using? On what operating system? Which browser?**

esprima.org: http://esprima.org/demo/parse.html?code=a%3A%20function%20b()%7B%7D

**Please provide any additional information below.**

Relevant spec section: https://es5.github.io/#x12.12

**Comment by michaelficarra** [comment]
These are now allowed in ES6.
