### ISSUE TITLE
[ES6]: Simplify implementation of ArrowFunctionExpression

### ISSUE THREAD

**Issue by ikarienator** [jquery/esprima#1056]
The current implementation of ArrowFunctionExpression checks the placeholder in many places. In fact the placehold is only needed to be checked in `parseAssignmentExpression`.

**Comment by mikesherov** [comment]
@ikarienator can you also handle implementing rest parameters in this issue?

**Comment by ikarienator** [comment]
Yes, I will handle RestParameter in this issue as well.

**Comment by mikesherov** [comment]
This work was done in #1093
