### ISSUE TITLE
Spread element should be allowed as non-last argument

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1057]
Filed by @RReverser previously as [issue 569](https://code.google.com/p/esprima/issues/detail?id=569).

**What steps will reproduce the problem?**
Try to parse `f(-1, ...args, 2, ...[3])`.

**What is the expected output?**
Successful parsing to AST (as of http://people.mozilla.org/~jorendorff/es6-draft.html#sec-argument-lists-runtime-semantics-argumentlistevaluation and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator).

**What do you see instead?**
Error: Line 1: Spread must be the final element of an element list

**Comment by RReverser** [comment]
Given that this issue is open - I don't think so.

**Comment by paulrouget** [comment]
This is blocking us from using jscs. I'm not familiar with Esprima code. Is it an easy fix or does it require some changes in the parser logic? Like, how to make the difference between `[...a, b] = v` (not valid) and `v = [...a, b]` (valid)?

**Comment by ariya** [comment]
@ikarienator Do you have any comment on the issue mentioned by @paulrouget above?

**Comment by ariya** [comment]
This is now supported in version 2.4. You can also try it on the online parser demo.

**Comment by jiyinyiyong** [comment]
Confirmed :)
