### ISSUE TITLE
Patterns in for in / of statements

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1060]
kamicane wrote in https://code.google.com/p/esprima/issues/detail?id=558

This is on the harmony branch.

This does not parse for for in / of statements:

    for ([a,b] in x) a;
    for ([a,b] of x) a;
    for ({a,b} in x) a;
    for ({a,b} of x) a;

Same for comprehensions:

    [for ([a,b] of x) a];

Esprima errors out with:

   Invalid left-hand side in for-in

for for in statements, and it parses the ArrayPattern / ObjectPattern as ArrayExpression / ObjectExpression in for of statements, while it should maybe probably be:

    "type": "ForInStatement",
    "left": {
      "type": "ArrayPattern"

This is the tree i tested on:

https://github.com/ariya/esprima/tree/f1b3150aa43205d511e3452b8c1cead96d2925d4

**Comment by ariya** [comment]
We don't support the harmony branch anymore (see #1172). Patterns support for for-in has been covered by #1045 and for-of will be part of #1047.
