### ISSUE TITLE
match v8 error messages for DefaultRestParameter and ObjectPatternAsRestParameter

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1062]
Currently, v8 has no error messages for DefaultRestParameter and ObjectPatternAsRestParameter. Once they do, we should match them.

**Comment by ariya** [comment]
Might be related: #1057.

@ikarienator Does Shift allow rest parameter to have a default?

**Comment by michaelficarra** [comment]
ES6 doesn't allow for that. Nor does Shift.

**Comment by mikesherov** [comment]
Right, just seems like v8 hasn't caught up yet. I can find an error message there in the source.

**Comment by ikarienator** [comment]
I think we can just throw `"Unexpected token ="` in this case.

**Comment by mikesherov** [comment]
And for the object pattern case, unexpected token `{`? @ikarienator ?

**Comment by mikesherov** [comment]
I'll do that for now, but I want to leave this issue open to revisit it in the future once v8 *does* have something to say.

**Comment by ariya** [comment]
Sounds good, I like the idea!

**Comment by ariya** [comment]
According to https://www.chromestatus.com/feature/5937087912083456, rest parameters would be supported by default on Chrome 47 (using V8 version 4.7).

For the default rest parameter error (see http://jsbin.com/donobewoco/edit?js,console), Chrome 47 gives the following error message:
```
Unexpected token =
```
For object pattern as rest parameter error (see http://jsbin.com/hekenuvido/edit?js,console), Chrome 47 gives the following error message:
```
Unexpected token {
```

With this information, I think it is clear that Esprima is already using the expected official error message when there is a syntax error processed by V8.
