### ISSUE TITLE
ES6 feature: Let and Const Declaration

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1065]
## Syntax:

Per Rev 32 (Feb 2, 2015) of the draft spec, the relevant grammar is on [Section 13.2.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations) on *Let and Const Declarations*:

```
LexicalDeclaration[In, Yield] :
  LetOrConst BindingList[?In, ?Yield] ;

LetOrConst :
  let
  const

BindingList[In, Yield] :
  LexicalBinding[?In, ?Yield]
  BindingList[?In, ?Yield] , LexicalBinding[?In, ?Yield]

LexicalBinding[In, Yield] :
  BindingIdentifier[?Yield] Initializer[?In, ?Yield]opt
  BindingPattern[?Yield] Initializer[?In, ?Yield]
```

**Referred to by:**

Declaration:

```
Declaration[Yield] :
  HoistableDeclaration _[?Yield]
  ClassDeclaration[?Yield]
  LexicalDeclaration[In, ?Yield]
```

StatementListItem:

```
StatementListItem[Yield, Return] :
  Statement[?Yield, ?Return]
  Declaration[?Yield]
```

Iteration:

```
for ( LexicalDeclaration[?Yield] Expression[In, ?Yield]opt ; Expression[In, ?Yield]opt ) Statement[?Yield, ?Return]
for ( ForDeclaration[?Yield] in Expression[In, ?Yield] ) Statement[?Yield, ?Return]
```

whereas:

```
ForDeclaration[Yield] :
  LetOrConst ForBinding[?Yield]

ForBinding[Yield] :
  BindingIdentifier[?Yield]
  BindingPattern[?Yield]
```

## Early errors:

* [x] const without initializer: `const x;` (from Esprima 1.x)
* [x] for-in with multiple let identifiers: `for (let x,y in z){}`
* [x] for-in with multiple const identifiers: `for (const x,y in z){}`
* [x] for-in with let initializer: `for (let i = 1 in x){}`
* [x] for-in with const initializer: `for (const i = 1 in x){}`
 * More TBD

## Spec:

[13.2.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations) *Let and Const Declarations*.

Relevant AST interfaces (from https://github.com/estree/estree):

```js
interface VariableDeclaration <: Declaration {
    type: "VariableDeclaration";
    declarations: [ VariableDeclarator ];
    kind: "var";
}
```

```js
extend interface VariableDeclaration {
    kind: "var" | "let" | "const";
}
```

## See also

* [Error messages in V8](https://chromium.googlesource.com/external/v8/+/master/src/messages.js)
* Harmony branch: [switch case accepting declaration](http://code.google.com/p/esprima/issues/detail?id=288)

Note that V8 doesn't yet support various early errors for lexical declarations. In the mean time, we may need to use the generic `Unexpected token...` message for such an error.

**Comment by ariya** [comment]
Note that Esprima is always able to parse `let` and `const` hitherto (as variable declaration). However, it does not yet have the formalized lexical declaration. Thus, implementing this feature finally allows `const` to be used in other places (switch case, etc).

**Comment by ariya** [comment]
@ikarienator Just to confirm, there is also this grammar:

```
for ( [lookahead ∉ {let [}] LeftHandSideExpression[?Yield] in Expression[In, ?Yield] ) Statement[?Yield, ?Return]
```

Does this mean that the code like `for (let i in [1, 2, 3]){}` is not valid?

**Comment by ikarienator** [comment]
That example is valid but does not fall into that production. It falls into:
<pre>
<b>for</b> <b>(</b> <i>ForDeclaration</i><sub>[?Yield]</sub> <b>in</b> <i>Expression</i><sub>[In, ?Yield]</sub> <b>)</b> <i>Statement</i><sub>[?Yield, ?Return]</sub>
</pre>

The lookahead is for disambiguous.
Note that the lookahead is actually of two tokens <b>`let`</b> and <b>`[`</b>.

**Comment by ariya** [comment]
Ah you're right. And technically it's not even a `LexicalDeclaration` because `ForDeclaration` only permits one binding, not multiple.

**Comment by ariya** [comment]
How about `for (const i in x) {}`? Not sure how valid it should be, using the `const` there is a bit unnatural.

**Comment by ikarienator** [comment]
Weirdly enough, it is allowed. The semantics is that it can only be assigned once. I think the spec should clarify it more on in what occasion it could be used. https://people.mozilla.org/~jorendorff/es6-draft.html#sec-for-statement-runtime-semantics-labelledevaluation

**Comment by ariya** [comment]
> Weirdly enough, it is allowed.

Let's keep it invalid for now, until there is a better clarification.

Now with that, please review this PR @ikarienator :wink:

**Comment by michaelficarra** [comment]
No classification needed. It should definitely be allowed.

**Comment by ikarienator** [comment]
I meant the clarification on the use case. The definition is clear.

**Comment by ariya** [comment]
Tasks in this ticket have been implemented. Further enhancements and more early errors will be filed separately.
