### ISSUE TITLE
it's not clear what unit ranges are provided in

### ISSUE THREAD

**Issue by ianthehenry** [jquery/esprima#1069]
Or, rather, "it seems that I'm getting ranges of UTF-16 codepoints, even when my input is a UTF-8-encoded buffer."

    ~/src/esprima ➜ node
    > var esprima = require('./');

Alright. Now we want to investigate how the `range` behaves with multi-byte sequences:

    > var ascii = 'var a = "x";';
    > var fancy = 'var a = "☃";';
    > JSON.stringify(esprima.parse(ascii, { range: true }))
    '{"range":[0,12],"type":"Program","body":[{"range":[0,12],"type":"VariableDeclaration","declarations":[{"range":[4,11],"type":"VariableDeclarator","id":{"range":[4,5],"type":"Identifier","name":"a"},"init":{"range":[8,11],"type":"Literal","value":"x","raw":"\\"x\\""}}],"kind":"var"}]}'
    > JSON.stringify(esprima.parse(fancy, { range: true }))
    '{"range":[0,12],"type":"Program","body":[{"range":[0,12],"type":"VariableDeclaration","declarations":[{"range":[4,11],"type":"VariableDeclarator","id":{"range":[4,5],"type":"Identifier","name":"a"},"init":{"range":[8,11],"type":"Literal","value":"☃","raw":"\\"☃\\""}}],"kind":"var"}]}'

Okay. That's fine. That's what I'd expect, as I passed in a JavaScript UTF-16 string.

But what if I pass in a Buffer?

    > var asciiBuf = new Buffer(ascii, 'utf8');
    > var fancyBuf = new Buffer(fancy, 'utf8');
    > asciiBuf.length
    12
    > fancyBuf.length
    14

ASCII works fine:

    > JSON.stringify(esprima.parse(asciiBuf, { range: true }))
    '{"range":[0,12],"type":"Program","body":[{"range":[0,12],"type":"VariableDeclaration","declarations":[{"range":[4,11],"type":"VariableDeclarator","id":{"range":[4,5],"type":"Identifier","name":"a"},"init":{"range":[8,11],"type":"Literal","value":"x","raw":"\\"x\\""}}],"kind":"var"}]}'

But then, chaos strikes!

    > JSON.stringify(esprima.parse(fancyBuf, { range: true }))
    '{"range":[0,12],"type":"Program","body":[{"range":[0,12],"type":"VariableDeclaration","declarations":[{"range":[4,11],"type":"VariableDeclarator","id":{"range":[4,5],"type":"Identifier","name":"a"},"init":{"range":[8,11],"type":"Literal","value":"☃","raw":"\\"☃\\""}}],"kind":"var"}]}'

What do those ranges mean? They certainly aren't ranges in my input:

    > fancyBuf.slice(0, 12).toString()
    'var a = "☃'

Why, that omits the last two bytes of my input!

It appears that, even though I passed in a buffer of UTF-8 text, I'm getting ranges of UTF-16 codepoints. Choosing a character that encodes to a UTF-16 surrogate pair:

    > var surrogate = 'var a = "𦕈";'

(That's `U+26548`)

    > JSON.stringify(esprima.parse(surrogate, { range: true }));
    '{"range":[0,13],"type":"Program","body":[{"range":[0,13],"type":"VariableDeclaration","declarations":[{"range":[4,12],"type":"VariableDeclarator","id":{"range":[4,5],"type":"Identifier","name":"a"},"init":{"range":[8,12],"type":"Literal","value":"𦕈","raw":"\\"𦕈\\""}}],"kind":"var"}]}'
    > JSON.stringify(esprima.parse(new Buffer(surrogate, 'utf8'), { range: true }));
    '{"range":[0,13],"type":"Program","body":[{"range":[0,13],"type":"VariableDeclaration","declarations":[{"range":[4,12],"type":"VariableDeclarator","id":{"range":[4,5],"type":"Identifier","name":"a"},"init":{"range":[8,12],"type":"Literal","value":"𦕈","raw":"\\"𦕈\\""}}],"kind":"var"}]}'

So it's not even by codepoints -- it's by UTF-16 words?

It would be nice if the range output were given in terms of the input, but at the very least the current behavior should probably be documented.

**Comment by ariya** [comment]
Internally, Esprima may convert the input to a string. Take a look at the first few lines of `parse`:

```js
    function parse(code, options) {
        var program, toString;

        toString = String;
        if (typeof code !== 'string' && !(code instanceof String)) {
            code = toString(code);
        }
```

Could it be the source of confusion when `code` above is a `Buffer`?

**Comment by ianthehenry** [comment]
I get that; it's just -- it seems like it's leaking an implementation detail into the interface. It manifested as a kinda-hairy-bug here:

https://github.com/ianthehenry/browser-unpack/commit/7ca231af39eab56ede6ad7b80f8619033e5e2eaf

Where a module was using the output of `range` to index into a buffer (and getting bad results because of it).

A more succinct summary: I would expect that I could use the range output to interact with the input, regardless of the input format.

I don't *really* think the current behavior is that troubling -- once you realize that what units the range is given in -- but it seems like a problem of the documentation.

It would be *nice* if the range were given relative to the actual input, instead of a differently-encoded version, but that's probably very cumbersome internally due to the nature of JS, and I can't really think of a time where it's not sufficient to just encode it into a string first. (So long as you know to do that!)

**Comment by ariya** [comment]
We could definitely have Esprima rejects anything that is not a legitimate string. That allows a quick discovery of passing e.g. a `Buffer` instance.

However, it is a breaking change and it could be done only on the next major version bump.
