### ISSUE TITLE
ES6 Feature: Template Strings: tracking Issue

### ISSUE THREAD

**Issue by JacquesMarais** [jquery/esprima#1074]
### Template Literal

```
TemplateLiteral[Yield] :
  NoSubstitutionTemplate
  TemplateHead Expression[In, ?Yield] TemplateSpans[?Yield]
TemplateSpans[Yield] :
  TemplateTail
  TemplateMiddleList[?Yield] TemplateTail
TemplateMiddleList[Yield] :
  TemplateMiddle Expression[In, ?Yield]
  TemplateMiddleList[?Yield] TemplateMiddle Expression[In, ?Yield]
```

### Template Literal Lexical Components

```
Template ::
  NoSubstitutionTemplate
  TemplateHead
NoSubstitutionTemplate ::
  ` TemplateCharactersopt `
TemplateHead ::
  ` TemplateCharactersopt ${
TemplateSubstitutionTail ::
  TemplateMiddle
  TemplateTail
TemplateMiddle ::
  } TemplateCharactersopt ${
TemplateTail ::
  } TemplateCharactersopt `
TemplateCharacters ::
  TemplateCharacter TemplateCharactersopt
TemplateCharacter ::
  $ [lookahead ≠ { ]
  \ EscapeSequence
  LineContinuation
  LineTerminatorSequence
  SourceCharacter but not one of ` or \ or $ or LineTerminator
```

## Spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literals
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literal-lexical-components

## Remaining Tasks:

- [x] Review and Test Token Generation
- [x] Review Error Messages 
- [x] Fix #1002
- [x] estree/estree#25

**Comment by garlicnation** [comment]
https://github.com/jquery/esprima/pull/1078

Needs tests - working on that right now.

**Comment by ariya** [comment]
The feature needs more information (spec, syntax, etc). See other ES6 for some examples.
Also estree has not started/finalized the AST format for template string yet.
