### ISSUE TITLE
Use `Literal` instead of `ModuleSpecifier` for `ImportDeclaration`'s `source` field.

### ISSUE THREAD

**Issue by impinball** [jquery/esprima#1077]
This will align Esprima with both Acorn and SpiderMonkey on this issue. I can't find the initial bug from Google Code with relevant discussion, though, or I would bring it up here. This is highly relevant to estree/estree#35 with regards to the fixme under `ImportDeclaration`.

**Comment by mikesherov** [comment]
This is now resolved.
