### ISSUE TITLE
Use AssignmentExpression for default parameter value

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1081]
In estree/estree#3 and estree/estree#37, it was decided to replace `Function.defaults` with an array with `AssignmentPattern` as a formal parameter and remove the `Function.defaults` member. 

(This can not go into a release earlier than 3.0, because 2.0 was already released with support for defaults in the old fashion)

The relevant part of the AST format:

```js
interface Function <: Node {
    id: Identifier | null;
    params: [ Pattern ];
    body: BlockStatement;
}
```

where `Pattern` is either a `RestElement` (already implemented #1011) or `AssignmentExpression`.

As an example, the following code:
```js
esprima.parse('function f(x=42){}').body[0]
```
*currently* produces this output:
```js
FunctionDeclaration {
  type: 'FunctionDeclaration',
  id: Identifier { type: 'Identifier', name: 'f' },
  params: [ Identifier { type: 'Identifier', name: 'x' } ],
  defaults: [ Literal { type: 'Literal', value: 42, raw: '42' } ],
  body: BlockStatement { type: 'BlockStatement', body: [] },
  generator: false,
  expression: false }
```
*After* this feature will be implemented, the output would look like:
```js
FunctionDeclaration {
  type: 'FunctionDeclaration',
  id: Identifier { type: 'Identifier', name: 'f' },
  params: [ AssignmentPattern { type: 'AssignmentPattern', left: [Object], right: [Object] } ],
  body: BlockStatement { type: 'BlockStatement', body: [] },
  generator: false,
  expression: false }
```

**Comment by ariya** [comment]
For the downstream test, we have to exclude js2coffee temporarily until this one is fixed: https://github.com/js2coffee/js2coffee/issues/427.

**Comment by mikesherov** [comment]
Woah!
