### ISSUE TITLE
data structure for `export default AN_EXPRESSION`

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1088]
Right now, e.g. `export default 42;` produces a `literal` as the value of the `declaration` field. Should it produce an `expressionStatement` node instead, which has a literal inside it?

If no, then it seems we're unwrapping arbitrary expressions inside the `export default` syntax, and something like `export default (1 + 42);` should be similarly unwrapped to have a `binaryExpression` be the value of the `declaration` field>

**Comment by ariya** [comment]
Harmony branch is deprecated. Here is the situation on the master branch.
```js
> require('esprima').parse('export default 42;', { sourceType: 'module'}).body[0]
{ type: 'ExportDefaultDeclaration',
  declaration: { type: 'Literal', value: 42, raw: '42' } }
```

and for binary expression:
```js
> require('esprima').parse('export default (1+2);', { sourceType: 'module'}).body[0]
{ type: 'ExportDefaultDeclaration',
  declaration: 
   { type: 'BinaryExpression',
     operator: '+',
     left: { type: 'Literal', value: 1, raw: '1' },
     right: { type: 'Literal', value: 2, raw: '2' } } }
```


According to ESTree:

```js
interface ExportDefaultDeclaration <: Node {
    type: "ExportDefaultDeclaration";
    declaration: Declaration | Expression;
}
```

Thus, it seems that we are already doing the right thing and there is no issue anymore.
