### ISSUE TITLE
ES6 feature: Update to ES6 identifier grammar

### ISSUE THREAD

**Issue by mathiasbynens** [jquery/esprima#1089]
Esprima currently implements ES5 identifier grammar. It would be nice to update to ES6.

In case it’s helpful — I just wrote a blog post that documents the differences between ES5 and ES6 identifiers, with examples: https://mathiasbynens.be/notes/javascript-identifiers-es6

**Comment by ikarienator** [comment]
@mathiasbynens You might be interested in this as well https://bugs.ecmascript.org/show_bug.cgi?id=4097#c4

**Comment by mathiasbynens** [comment]
@ikarienator Thanks for the heads up!

**Comment by mathiasbynens** [comment]
@ikarienator Is this observable? How?

E.g. how should the following code behave:

```js
Function('var var;'); // grammar error → doesn’t throw (until executed)?
Function('var v\\u0061r;'); // early error → throws (before execution)?
```

**Comment by michaelficarra** [comment]
@mathiasbynens They should both throw. I can't think of any way someone would be able to distinguish an early error from a grammar error.

**Comment by ariya** [comment]
Since this is quite a big topic, I'll spawn few new tickets which will tackle the individual issues separately.

**Comment by ariya** [comment]
This is now covered by all the most recent commits.
