### ISSUE TITLE
ClassDeclaration/ClassExpression name doesn't align with ESTree

### ISSUE THREAD

**Issue by nzakas** [jquery/esprima#1095]
The 2.0 implementation uses `name` for the class name (https://github.com/jquery/esprima/pull/1061/files#diff-7c9336e4324ea31118ce749be055b6a3R1754) whereas ESTree prescribes using `id` for the class name (https://github.com/estree/estree/blob/master/es6.md#classdeclaration).

I couldn't find any reference to a discussion about a spec change. Is this a bug?

**Comment by ikarienator** [comment]
Ah, probably my fault. Let me confirm it.
