### ISSUE TITLE
esprima accepts invalid/incomplete string escape sequences

### ISSUE THREAD

**Issue by michaelficarra** [jquery/esprima#1106]
Some invalid string escape sequences that esprima currently parses:

```js
"\x";
"\x0";
"\xx";
"\u";
"\u0";
"\ux";
"\u00";
"\u000";
"\8";
"\9";
```

**Comment by mikesherov** [comment]
@michaelficarra thanks for the report. We'll look into it shortly. Are you interested in submitted a patch for this?

**Comment by michaelficarra** [comment]
I tried working on this, but it appears the `invalid-syntax` tests aren't being run. There's no mention of `invalid-syntax` anywhere in `test`. :confused:

**Comment by mikesherov** [comment]
@michaelficarra all the tests run automatically when you do `npm test`, no?

**Comment by michaelficarra** [comment]
@mikesherov: @ikarienator is working on fixing the issue I mentioned above. He'll open an issue for it shortly.
