### ISSUE TITLE
Remove the compatibility tests

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1109]
Historically, `test/compat.js` is used to verify that Esprima output matches to that of SM AST using the adopted `test/reflect.js` (from Mozilla) as the baseline. With a growing number of in-house unit tests (almost 900 so far) and considering that ES6 features coming in and its syntax being standardized via ESTree, there is little to no benefit of running these compatibility tests anymore.

**Comment by mikesherov** [comment]
:+1:

**Comment by nzakas** [comment]
:+1: very hard to work with
