### ISSUE TITLE
Distinguish between scanning regex for parsing vs tokenization

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1111]
Function `scanRegExp()` can return two completely different objects, depending whether it is invoked from `tokenize` and `parse`. This run-time-dependent return value is confusing, for both human and type inference tool.

It shall be separated into two different functions (scanning vs parsing). The decision to use the right one should happen inside `collectRegex()`.

**Comment by ikarienator** [comment]
The two different objects are the token used later in parsing and the token returned by having `token: true`. I believe that they are both tokenization. We didn't do anything to parse the structure of regex as defined in [B.1.4](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-regular-expressions-patterns).

**Comment by ariya** [comment]
Yeah, what I meant is not regex parsing, but consuming regex as part of the parsing process (vs tokenizing). I will probably change the title to make it more explicit.
