### ISSUE TITLE
missing name after . operator (esprima#4059)

### ISSUE THREAD

**Issue by nimajneb-relleum** [jquery/esprima#1120]
When I try to evaluate esprima.js 2.1 with Rhino I get the message "missing name after . operator (esprima#4059)". Same code is working with esprima.js 2.0.
Same issue when using 2.1 release with the ANT task from https://github.com/ariya/ant-javascript-validate

**Comment by ariya** [comment]
Thank you @nimajneb-relleum for reporting this issue. Let me take a look at 2.1 and Rhino.

**Comment by ikarienator** [comment]
I tried to parse esprima using esprima in rhino and I had no problem. What is the file you are parsing?

**Comment by nimajneb-relleum** [comment]
I got the error for "esprima.js". Same error in Rhino and ANT.
The issue did not occur after commenting out line 4059 "method.static = isStatic;"

**Comment by mikesherov** [comment]
@nimajneb-relleum what was the source code you were trying to parse?

**Comment by ikarienator** [comment]
I see... static is a keyword in Rhino and it doesn't support keyword in
IdentifierName position. I recommend you to completely ditch Rhino and
start to use nashorn or similar technology. We will consider to fix this in
2.2.
