### ISSUE TITLE
Merge `BooleanLiteral` and `NullLiteral` into `Keyword`

### ISSUE THREAD

**Issue by ikarienator** [jquery/esprima#1127]
We can expect a performance enhancement due to simplification on the logic of `scanIdentifier`, which is the biggest bottleneck for lexer.

**Comment by nzakas** [comment]
This would be a breaking change for downstream projects. Is it necessary?

**Comment by michaelficarra** [comment]
@ikarienator Remember that the tokeniser is part of esprima's public interface.

**Comment by mikesherov** [comment]
Yeah, I don't think we can do this change.

**Comment by ikarienator** [comment]
Oh, I meant the `Token.NullLiteral` and `Token.BooleanLiteral`. They are used internally and not exposed. When we expose the types, we always use strings.

**Comment by mikesherov** [comment]
OHHHH, right, the props dangling off the token internally. :+1:

**Comment by mikesherov** [comment]
no, this is still breaking, because that type gets converted to a string at the end.

**Comment by ikarienator** [comment]
Well, I think I convert them in an BC way. :)

**Comment by ariya** [comment]
I don't think we're pursuing this. Let's bring it back whenever the opportunity present itself.
