### ISSUE TITLE
Destructured argument property shorthand value incorrect

### ISSUE THREAD

**Issue by nzakas** [jquery/esprima#1148]
Given this code:

```js
function x({a}) {
  try {
    var {b} = a;
  }
  catch({stack}) {
  }
}
```

Each of the destructured properties in this example has `shorthand` equal to `false`. I believe they should be `true`.

Tested with current Esprima master.

**Comment by mikesherov** [comment]
Thanks for the report, @nzakas. We'll be looking into this shortly... /cc @ikarienator
