### ISSUE TITLE
The parser is blowing up on a shebang

### ISSUE THREAD

**Issue by dijs** [jquery/esprima#1151]
Can this "#!/usr/bin/env node" not throw a parse error?

**Comment by michaelficarra** [comment]
No, that is not valid JavaScript. You can strip shebangs yourself before giving input to esprima.

**Comment by dijs** [comment]
Sounds good.

**Comment by ariya** [comment]
For an illustrative example on how to do this (taken from [jsparser](https://bitbucket.org/ariya/jsparser/src/master/jsparser.js)):

```js
function trimHashbang(code) {
    if (code.substring(0, 2) === '#!') {
        var end = code.indexOf('\n');
        var filler = '';
        for (var i = 0; i < end; ++i) {
           filler += ' ';
        }
        code = filler + code.substring(end, code.length);
    }
    return code;
}
```

Of course, you also need to account for a possible `return` not inside a function. Check the above referred `jsparser` for details.

**Comment by michaelficarra** [comment]
eslint uses essentially

```js
function trimShebang(text) {
  return text.replace(/^#!([^\r\n]+)/, function(match, captured) { return "//" + captured; });
}
```

**Comment by ariya** [comment]
"I know, I'll use regular expressions." :wink:

**Comment by dmethvin** [comment]
`problems++`
