### ISSUE TITLE
Destructured rest argument throws syntax error

### ISSUE THREAD

**Issue by nzakas** [jquery/esprima#1155]
The following throws an error using Esprima 2.1.0:

```js
(function x(...[ a, b ]){});
```

"Unexpected token ["

This is a bit strange since `parseRestElement()` explicitly checks for use of an ObjectPattern (and throws an appropriate message), but ArrayPatterns are left to fail with an unexpected token error.

Using ArrayPattern is an error, I'm just not sure why ObjectPattern gets special treatment while ArrayPattern is left to a normal tokenization error.

**Comment by mikesherov** [comment]
Esprima attempts to match v8 error messages. The latest v8 throws unexpected token errors because it doesn't yet parse rest elements. As soon as it does, we'll upgrade the error messages to match v8.



Mike Sherov

**Comment by nzakas** [comment]
Got it, thanks.

**Comment by mikesherov** [comment]
Closing for now. Thanks again!
