### ISSUE TITLE
Fix Acorn in speed comparison

### ISSUE THREAD

**Issue by marijnh** [jquery/esprima#1162]
It appears the 1.0 Acorn package was pulled in without updating the paths. The `acorn.js` file now lives under `dist/` in the installed file structure. Simply adding that to the script tag should solve the issue.

**Comment by ariya** [comment]
Isn't `dist/` content generated from the build process?

**Comment by marijnh** [comment]
Ah, I didn't notice you were directly linking to the github repo. That indeed doesn't have the dist/ files. There's a built copy of Acorn at ternjs.net ([here](http://ternjs.net/node_modules/acorn/dist/acorn.js)), you can use that if you want.

**Comment by ariya** [comment]
That will do, thanks!

**Comment by marijnh** [comment]
Great. I see Esprima got a _lot_ faster since the last time I looked (1.1). What'd you do? (Anything Acorn could steal?)

**Comment by michaelficarra** [comment]
@marijnh Just wait until two-phase parsing :wink:. We're going to be landing it in the Shift parser soon, and if all goes well, porting it to esprima. Also, @ikarienator plans to optimise the token handling even more, which should be another noticeable improvement.

**Comment by ariya** [comment]
Also, mostly avoid doing useless processing and allocation, based on the idea of not optimizing for the use case of no location info anymore.
