### ISSUE TITLE
Best way to parse foreign code (unknown source type)?

### ISSUE THREAD

**Issue by lukehorvat** [jquery/esprima#1167]
I've started building a Google Chrome extension to view the AST of any JavaScript code on GitHub, using Esprima for parsing. Since I don't know the source type of "foreign" (not written by me) code, I need to do some [slightly ugly stuff](https://github.com/lukehorvat/github-ast-viewer/blob/master/src/content-script/index.js#L47-L58) to facilitate a successful parse. :sweat: Just wondering, is there a better way for me to do this?

**Comment by michaelficarra** [comment]
<del>Try to parse it as a module. If it fails, parse it as a script.</del>

Looks like that's what you're doing already.

**Comment by ariya** [comment]
That's the best way to do it.
