### ISSUE TITLE
ES6: Spread Element (for function argument)

### ISSUE THREAD

**Issue by markelog** [jquery/esprima#1169]
## Syntax:

To be written.

## Spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-array-initializer

Relevant AST interfaces (from https://github.com/estree/estree):

```js
interface SpreadElement <: Node {
    type: "SpreadElement";
    argument: Expression;
}

extend interface CallExpression {
    arguments: [ Expression | SpreadElement ];
}
```

## Early Errors:

The following early errors should be detected: (to be written)

## Related Tasks:

- [ ] Error message

**Comment by michaelficarra** [comment]
Spread is not just allowed in function argument position, but also as an array initialiser element.

```js
[...a]
```

**Comment by markelog** [comment]
As i see it, spread operator is not supported for the function calls. Arrays and fe are.

**Comment by markelog** [comment]
So for the expression `a(...b)` correct AST should look like that - 

```js
{
  "type": "Program",
  "body": [
    {
      "type": "ExpressionStatement",
      "expression": {
        "type": "CallExpression",
        "callee": {
          "type": "Identifier",
          "name": "a"
        },
        "arguments": [
          {
            "argument": {
              "name": "b",
              "type": "Identifier",
            },
            "type": "SpreadElement",
          }
        ]
      }
    }
  ]
}
```

@mikesherov, @ariya ?

**Comment by markelog** [comment]
Does cherry-picking <a href="https://code.google.com/p/esprima/issues/detail?id=378#hc2">these</a> commits is sufficient?

/cc @Benvie

**Comment by markelog** [comment]
@mikesherov @ariya could one of you confirm my proposal?

**Comment by ariya** [comment]
@markelog Probably not. Much has changed since and master has diverged much vs the old harmony branch.

**Comment by ariya** [comment]
Apparently spread element for array initializer has been done by @ikarienator as part of #1045. Thus, let's scope this only for function argument.
