### ISSUE TITLE
Remove harmony branch

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1172]
With no further maintenance planned for Facebook's esprima-fb (https://github.com/facebook/esprima/issues/111), there is little to no value maintaining the upstream harmony branch. In addition, the master branch starts to get more and more ES6 features (#1099) and hence there is no good reason for a new project to use the unofficial harmony branch anymore.

Other issues affecting the harmony branch will be closed as well (as wontfix).

**Comment by jeffmo** [comment]
:clap:

**Comment by ariya** [comment]
This is completed, harmony branch no more.

**Comment by jeffmo** [comment]
\0/
