### ISSUE TITLE
Modularize the source code

### ISSUE THREAD

**Issue by markelog** [jquery/esprima#1176]
And use robust third-party libs as much as possible. Same goes for the test code too.

It's hard to navigate over the code, fix bugs and add new features otherwise, it would be also more contribution friendly.

**Comment by markelog** [comment]
Ref https://github.com/jquery/esprima/issues/1168

**Comment by ariya** [comment]
Yes! This definitely needs to be the priority as soon as the support for ES6 features is completed.
