### ISSUE TITLE
Minifying a file, the simple way

### ISSUE THREAD

**Issue by yamsellem** [jquery/esprima#1187]
Looking [at this demo](http://esprima.org/demo/minify.html), it seems straightforward to minify a file with esprima. But there is not a single line of code explaining how anywhere. 

Is this a game where only brave  developers who find it in the page source are allowed to used it?
Have I missed something?

Thanks.

**Comment by ariya** [comment]
Questions are always better sent to the [mailing-list](http://groups.google.com/group/esprima).

To answer the question, check the sidebar in that demo page that contains this information:

> Minification is carried out using [escodegen](https://github.com/estools/escodegen) and [esmangle](https://github.com/estools/esmangle) projects.
