### ISSUE TITLE
Incorrect error when using destructuring multiple times in params

### ISSUE THREAD

**Issue by webbedspace** [jquery/esprima#1193]
The following ES6 code will wrongly produce an error when parsed by esprima:
`(function({A}, B, {C}) {'use strict';})`
The error is:
`Error: Line 1: Strict mode function may not have duplicate parameter names`

**Comment by ariya** [comment]
An obscure bug indeed! I really appreciate the excellent reduced test case.

**Comment by ikarienator** [comment]
In fact, also `(function([], []) {'use strict';})` and `(function({}, {}) {'use strict';})`.
