### ISSUE TITLE
request to undelete the harmony branch

### ISSUE THREAD

**Issue by jmonster** [jquery/esprima#1197]
hello there,

I am opening this issue to let you know that the removal of all the files in in [the harmony branch](https://github.com/jquery/esprima/tree/harmony) has broken a number of dependencies in a project I'm working on -- while I understand the need for the deprecating notice, is there any harm in putting the rest of the project back so that all of these dependencies continue working?

To be clear -- it's not simply a matter of updating the package.json for my project, there are things we depend on which depends on other things which ultimately depend on esprima.

Please and thank you :)

**Comment by ariya** [comment]
Do we have an understanding of which dependencies/packages require the harmony branch?

**Comment by jmonster** [comment]
For example...

+ https://github.com/jmonster/recast/commit/ca0aaf926bb3798fc7b3b183d771324140855c4c
+ https://github.com/jmonster/es6-module-transpiler/commit/27ef176aea225a914e2d5a5979320b5844ddd6b0

I have a recursive nightmare of these -- yes, there are newer versions of these modules available that do not depend on harmony but no, I cannot update to them without significant effort which is a time consuming process that is unfeasible to do right now.

**Comment by ariya** [comment]
Did you try to switch its dependency to [esprima-fb](https://www.npmjs.com/package/esprima-fb)?

**Comment by jmonster** [comment]
As I mentioned, we have multiple dependencies which recursively depends on other modules which, eventually, depend on the harmony branch. The only way I can switch any dependency is to fork *many* repositories, point them all at other forks, and ultimately find the children and point them at, for example, `esprima-fb`.

Is there any negative consequence to including the files in the harmony branch, as they were a few days ago, along with the deprecation README notice? It would solve a lot of problems with very little work.

**Comment by JackCA** [comment]
We (the Heroku dashboard team) have been running at a stand-still today because of this code deletion (as harmless as it may seem).

@ariya please reconsider restoring the code on the branch and rewording the readme to portray the fact that that branch will no longer be supported or developed :angel:

**Comment by ariya** [comment]
@jmonster Are you sure this is about to this repo's harmony branch ("upstream") and not my own fork (https://github.com/ariya/esprima)? Upstream harmony has been gone since May 1, there wasnt' any issue for the last few weeks of its non-existence.

@JackCA For the immediate workaround, will it be sufficient to restore the source file only (i.e. `esprima.js`)?

**Comment by jpatzer** [comment]
I started having issues this morning as well. Not sure why it didn't kick in sooner if the branch has been gone a while, but as mentioned, this is a circular nightmare.

I think you'll need to add back in the package.json file for this to be happy as most of the build issues appear to be ENOENT

Another repo with a circular ref (https://github.com/nickmerwin/node-coveralls).

A branch restore would be much appreciated.

**Comment by appleton** [comment]
+1 I've also been running into this issue starting today.

**Comment by Dhaulagiri** [comment]
@ariya you may be right that it was your fork of esprima as [this is one of the dependencies](https://github.com/benjamn/recast/blob/fc3d332cbdc64fbccb2ae6b7f187628968ae0ffc/package.json#L28) we are seeing with the problem

**Comment by R2c** [comment]
+1 Restore the branch please

**Comment by ariya** [comment]
I've restored `esprima.js` and `package.json` in the harmony branch of https://github.com/ariya/esprima. See if the world order is restored :-)

**Comment by Dhaulagiri** [comment]
![57257332](https://cloud.githubusercontent.com/assets/1672302/8310979/85655840-1990-11e5-97ab-a64d1c4f761c.jpg)

Thanks @ariya!  Trust that we are trying to remove this gnarly dependency graph from our project asap, but this is a huge help in the short term.

**Comment by JackCA** [comment]
thank you very much @ariya!

**Comment by ariya** [comment]
No worries. Once you have figured out the packages that still depend on that branch, please share with us so that we can figure out the best transition path!

**Comment by Dhaulagiri** [comment]
@ariya would it be possible for you to restore the file `bin/esparse.js` as well?  We are seeing issues trying to resolve this dependency:

`node_modules/karma-es6-module-preprocessor/node_modules/recast/node_modules/esprima/bin/esparse.js`

**Comment by ariya** [comment]
@Dhaulagiri Sure. Do you think it's helpful to tweak `package.json` to include only `esprima.js` (and not things like `bin`)?

**Comment by Dhaulagiri** [comment]
I'm not really sure whether recast needs that file or not

**Comment by ariya** [comment]
I made some minor tweak and then ran `npm install karma-es6-module-preprocessor` without any problem.
