### ISSUE TITLE
ES6 feature: Meta property

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1203]
## Syntax:

<pre>
NewTarget : new . target
</pre>

## Spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-meta-properties

Relevant AST interfaces (from https://github.com/estree/estree):

```js
interface MetaProperty <: Expression {
    type: "MetaProperty";
    meta: Identifier;
    property: Identifier;
}
```

**Comment by ariya** [comment]
There is a problem. The lengthy discussion https://github.com/estree/estree/pull/32 reached the consensus to go with the generic `MetaProperty` node. In the mean time, according to https://bugzilla.mozilla.org/show_bug.cgi?id=1141865, Mozilla SpiderMonkey is going with `NewTargetExpression`. See the code at https://hg.mozilla.org/mozilla-central/file/tip/js/src/jsast.tbl.

@jorendorff Is this decision final? Shall I file a Bugzilla issue? Please advise.

**Comment by jorendorff** [comment]
No, the decision was out of pure expedience. We don't want to keep it. It's a matter of someone finding time to fix it. See https://bugzilla.mozilla.org/show_bug.cgi?id=1168992 .

**Comment by jorendorff** [comment]
Eric Faust reminded me that one reason we've held off fixing it is that our internal parse tree doesn't contain location information for each individual part of the `new.target`. Some of that has been fixed as we implemented `super()`.

**Comment by ariya** [comment]
@jorendorff Thank you for the prompt response and excellent explanation! In mean time, we will go ahead and implement it as `MetaProperty`.
