### ISSUE TITLE
Regression: "\8", "\9" - Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by xzo** [jquery/esprima#1226]
2.4.1
See https://github.com/jquery/esprima/issues/1106
https://github.com/jquery/esprima/commit/bf5c615c3ee1dbc0077d46e5acce3ede3ef1d1f3
```javascript
// Error: Line 1: Unexpected token ILLEGAL
var esprima = require('esprima');
esprima.parse('"\\8"');
```

Some valid strings that esprima currently does not parse:
```
"\8"
"\9"
```

**Comment by michaelficarra** [comment]
Those are not valid. If you feel otherwise, show me the grammar production that allows them.

**Comment by xzo** [comment]
No, it is valid. "\8\9" works in the wild.

**Comment by dmethvin** [comment]
Seems like the `\` *DecimalDigit* production would apply? Things are complicated a bit because in non-`strict` mode there's also *LegacyOctalEscapeSequence* but none of those productions apply since `8` is not an octal digit. In `strict` a valid octal sequence generates a syntax error but an invalid one like `\8` silently converts to `8`.

**Comment by xzo** [comment]
Standard ECMA-262 June 1997 http://tecfa.unige.ch/guides/js/e262-pdf.pdf
7.7.4 String Literals
```
EscapeSequence ::
CharacterEscapeSequence
OctalEscapeSequence
HexEscapeSequence
UnicodeEscapeSequence

CharacterEscapeSequence ::
\ SingleEscapeCharacter
\ NonEscapeCharacter

NonEscapeCharacter::
SourceCharacter but not EscapeCharacter or LineTerminator

EscapeCharacter ::
SingleEscapeCharacter
OctalDigit
x
u

SingleEscapeCharacter :: one of
'"\ b f n r t
```

**Comment by mathiasbynens** [comment]
https://bugs.ecmascript.org/show_bug.cgi?id=2792

**Comment by dmethvin** [comment]
This is what i saw in [ES2015 RC1](http://wiki.ecmascript.org/lib/exe/fetch.php?id=harmony:specification_drafts&cache=cache&media=harmony:ecma-262_edition_6_02-20-15-releasecandidate1.pdf):
```
SingleStringCharacter ::
\ EscapeSequence

EscapeSequence ::
CharacterEscapeSequence

CharacterEscapeSequence ::
NonEscapeCharacter

NonEscapeCharacter ::
SourceCharacter but not one of EscapeCharacter or LineTerminator

EscapeCharacter ::
SingleEscapeCharacter
DecimalDigit
x
u
```

**Comment by ariya** [comment]
@dmethvin Good analysis! That means `\8` does not fulfill any production since `8` is a DecimalDigit and NonEscapeCharacter can't be it.

**Comment by xzo** [comment]
@dmethvin
>but an invalid one like \8 silently converts to 8.

because it is valid in old spec - ECMA-262 1997. since `8` is SourceCharacter
```
NonEscapeCharacter ::
SourceCharacter but not one of EscapeCharacter or LineTerminator

EscapeCharacter ::
OctalDigit
```

**Comment by dmethvin** [comment]
Yeah, I meant `\8` was invalid *octal*.

**Comment by ariya** [comment]
@xzo That's very old. ES 5.1 already specified EscapeCharacter to be exactly like above (see [7.8.4](http://es5.github.io/#x7.8.4))

I don't think Esprima needs to support ECMAScript < 5 at all.

**Comment by xzo** [comment]
Why parser doesn't need to support it, If ECMAScript engines support it?

**Comment by ariya** [comment]
Do we have some information as to how many scripts out there still utilizing such an escape sequence?

In all cases, even if we want to support, at best this is an error that should be tolerated, aka when `tolerant` is set to true in the parsing options.

**Comment by mathiasbynens** [comment]
This is on the table for ES7: https://bugs.ecmascript.org/show_bug.cgi?id=3477
