### ISSUE TITLE
ES6 Updated identifier name

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1232]
Relevant lexical grammar:

```
IdentifierName ::
    IdentifierStart
    IdentifierName IdentifierPart

IdentifierStart ::
    UnicodeIDStart
    $
    _
    \ UnicodeEscapeSequence


IdentifierPart ::
    UnicodeIDContinue
    $
    _
    \ UnicodeEscapeSequence
    <ZWNJ>
    <ZWJ>
```

where

* UnicodeIDStart: any Unicode code point with the Unicode property `ID_Start` or `Other_ID_Start`
* UnicodeIDContinue: any Unicode code point with the Unicode property `ID_Continue`, `Other_ID_Continue`, or `Other_ID_Start`

**Comment by mathiasbynens** [comment]
https://gist.github.com/mathiasbynens/6334847#file-javascript-identifier-regex-js-L65-L105 may be of use.
