### ISSUE TITLE
invalid-yield-generator-function-declaration.js ends with a colon

### ISSUE THREAD

**Issue by adko-pl** [jquery/esprima#1239]
While running `npm install` inside my project I got the following error:

	[INFO] C:\projects\my-project\src\main\webapp\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\projects\my-project\node\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
	[ERROR] npm ERR! tar.unpack untar error C:\tools\cygwin64\tmp\npm-9392-0b443f12\github.com\ariya\esprima\tarball\master
	[ERROR] npm ERR! Windows_NT 6.1.7601
	[ERROR] npm ERR! argv "C:\\projects\\my-project\\node\\node.exe" "C:\\projects\\my-project\\node\\npm\\bin\\npm-cli.js" "install" "--color=false"
	[ERROR] npm ERR! node v0.12.7
	[ERROR] npm ERR! npm  v2.13.1
	[ERROR] npm ERR! path C:\tools\cygwin64\tmp\npm-9392-0b443f12\unpack-777577e7a692\test\fixtures\ES6\yield\invalid-yield-generator-function-declaration.js:
	[ERROR] npm ERR! code ENOENT
	[ERROR] npm ERR! errno -4058
	[ERROR]
	[ERROR] npm ERR! enoent ENOENT, open 'C:\tools\cygwin64\tmp\npm-9392-0b443f12\unpack-777577e7a692\test\fixtures\ES6\yield\invalid-yield-generator-function-declaration.js:'
	[ERROR] npm ERR! enoent This is most likely not a problem with npm itself
	[ERROR] npm ERR! enoent and is related to npm not being able to find a file.
	[ERROR] npm ERR! enoent

Quick question, inside https://github.com/jquery/esprima/tree/master/test/fixtures/ES6/yield all the files end with `.js` expect for `invalid-yield-generator-function-declaration` which ends with `.js:`, is it intentional?

**Comment by benco03** [comment]
Getting this problem as well.

**Comment by jameslnewell** [comment]
I have the same problem on Windows. `git clone https://github.com/ariya/esprima.git` is failing to create afile ending in `:`.

**Comment by jelliefei** [comment]
Started getting this exact error suddenly and build failing since Friday morning 17 July 2015 with untar error and failing to find invalid-yield-generator-function-declaration.js

**Comment by furzeface** [comment]
Same since Friday afternoon - we'll track the issue until it's fixed and if we can help let us know!

**Comment by adko-pl** [comment]
This problem occurs only in the `master` branch, right? I am wondering which npm package has a dependency to the `master` branch, did anyone investigate that?

**Comment by lukaszmrowka** [comment]
For me is jshint.

**Comment by furzeface** [comment]
Same - JSHint :+1:

**Comment by michaelficarra** [comment]
I hope you all know that it took me about 30 seconds on my phone to submit a PR for this issue. Any one of you could have done that in the time it took you to post a comment. Also, the :+1:s are not helping anything, as the PR is already open.

**Comment by furzeface** [comment]
Sweet, nice one. People were just raising awareness by commenting on the issue. 

I'm guessing you're more familiar with the project/codebase as to how it was so quick and easy? - personally I'd be afraid of breaking changes to an unfamiliar project.

Nevertheless, I'm sure everyone is very grateful. Thank you.

**Comment by mikesherov** [comment]
Hey everyone, thanks for letting us know. The fix will be out shortly!

**Comment by RamyElkest** [comment]
Is there a way to mitigate this in the meantime?

**Comment by dorrellg** [comment]
Same issue here, thanks for the update mikesherov

**Comment by mikesherov** [comment]
@RamyElkest @dorrellg this is best mitigated by filing a bug against JSHint to not track master.

**Comment by dorrellg** [comment]
Is that the fix or can something be done inside master since that's what's being tracked?

**Comment by mikesherov** [comment]
Us fixing the issue is what will fix it. Mitigating it involves other packages not tracking an unstable master.

**Comment by ariya** [comment]
@lukaszmrowka @furzeface Seems that JSHint doesn't depend on Esprima. Is it an indirect dependency? Can you share your `npm ls` output?

**Comment by RamyElkest** [comment]
I can confirm this works now. Thank you all :+1:

**Comment by jelliefei** [comment]
The ariya fork still contains the filename errors – which the original post reports. I’m pretty new to all of this, I presume the ariya fork needs updating too, can someone help do this please?

**Comment by ariya** [comment]
@jelliefei Should be resolved now.

**Comment by RamyElkest** [comment]
my bad I confirm this works **now**

**Comment by zephyrweb** [comment]
In my case it was an old version of jshint tracking master (from grunt-contrib-jshint@0.4.3 actually). I was pulling my hair out because I didn't see any possible way that commit could have made it in because I was using shrinkwrap.

For npm noobs: if you use `npm shrinkwrap`, make sure you don't have any modules linked to a master branch in github, which you can see using `npm ll > deps.txt`. Just make sure there's nothing that looks like this:
`https://github.com/ariya/esprima/tarball/master`

**Comment by jameslnewell** [comment]
For me it was an v1.0.1 of [degenerator](https://github.com/TooTallNate/node-degenerator/blob/1.0.1/package.json#L16) (used in [component](https://github.com/componentjs/component)) referencing the #harmony tag. Updating to v1.0.2 no longer references the Git URL and resolved the issue for me.

**Comment by ariya** [comment]
@jameslnewell You may get things mixed up, this one has nothing to do with harmony branch.

**Comment by ariya** [comment]
@zephyrweb Confirmed, the culprit is here JSHint 1.1.0 (which is being installed by grunt-contrib-jshint@0.4.3): https://github.com/jshint/jshint/blob/1.1.0/package.json.

**Comment by RamyElkest** [comment]
@zephyrweb you're corrrect
