### ISSUE TITLE
Downstream test: failing JSCS tests

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1247]
This is discovered via #1245 (fails for me with Node.js v0.12.0, npm 2.9.1).

```
git clone https://github.com/jscs-dev/node-jscs.git
cd node-jscs
npm install
npm test
```

**Comment by ariya** [comment]
In the interim, we disable JSCS in the downstream tests.

**Comment by ariya** [comment]
Seems that this is now working again so I'm going to re-enable it.

**Comment by ariya** [comment]
It's failing again, see e.g. https://circleci.com/gh/jquery/esprima/30. Thus I likely will exclude JSCS from the downstream test, at least temporarily.

**Comment by ariya** [comment]
This is becoming a problem again.

**Comment by ariya** [comment]
This happens again, see PR #1448. For the build log: https://circleci.com/gh/jquery/esprima/235. The last few lines are:

```
========== jscs

Cloning https://github.com/jscs-dev/node-jscs.git ...
Cloning into 'jscs'...
remote: Counting objects: 549, done.
remote: Compressing objects: 100% (421/421), done.
remote: Total 549 (delta 189), reused 256 (delta 75), pack-reused 0
Receiving objects: 100% (549/549), 392.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (189/189), done.
Checking connectivity... done.

HEAD is
commit b19b33e749ee4e715b70f44c5c2ef40569cbaf40
Author: David Harkness <dharkness@gmail.com>
Date:   Wed Jan 6 17:43:02 2016 -0800

    disallowKeywordsOnNewLine: fix documentation format
    
    Two of the examples had an extra space before the comment `*` which messes u
    
    Closes gh-2052

(END)command npm run circleci took more than 1200 seconds since last output
```

@mikesherov Is JCSS test suite known to be reliable when running under Node.js 0.12 (what CircleCI is set to use)?

**Comment by hzoo** [comment]
Yeah haven't seen any issues other than this - cc @markelog?

**Comment by markelog** [comment]
jscs, with all those dependencies is pretty big, like 250M big, 200 of them are dependencies, probably the biggest package of your integration tests and since results are non-deterministic... i think you need to start to use the cache or increase the timeout

**Comment by ariya** [comment]
OMG 250 MB dependencies! I think CircleCI already caches `~/.node_modules`, not sure what's going on there. Perhaps I shall run the `npm install` step in verbose mode to get more details?

**Comment by ariya** [comment]
> Perhaps I shall run the npm install step in verbose mode to get more details?

Watch this build log for the details: https://circleci.com/gh/jquery/esprima/239.

**Comment by ariya** [comment]
Bah, that one got stuck. Look at this one instead: https://circleci.com/gh/jquery/esprima/240.

**Comment by ariya** [comment]
From the above build log, looks like the process got stuck at the `git clone` step. It didn't even start `npm install` yet.

**Comment by ariya** [comment]
Ah never mind, I misunderstood the log. I think it got stuck between `git log -n1` and `npm install`.
Not sure how or why :cry:

**Comment by jpaulin** [comment]
Why in general are the deps so big? Noticed this phenomena in many projects. Is it something that's likely to be changed in near future? I started living with the Javascript ecosystem just about a year ago, and first things that really surprised me was the largish trees of dependencies. Out of blue I'd estimated projects wouldn't contain more than a few megabytes of JS source.

**Comment by hzoo** [comment]
Well without npm 3/npm dedupe for 2 it will be pretty big. We are also bundling babel for babel-jscs rather than making it a separate thing.

**Comment by ariya** [comment]
> Why in general are the deps so big?

This is devDependencies, you only care if you are developing or testing JSCS. If you just *use* JSCS, the dependencies look rather different (quite compact actually).

In all cases, let's stay on topic. This downstream test should be only mildly affected by the dependencies.

**Comment by jpaulin** [comment]
Any new information with a verbose install? 

I got these results:
Running 'npm install --only=dev' on
a) Ubuntu Linux, npm version 3.5.2 got stuck forever after few initial packages done right
b) Windows 7, npm version 2.7.4 installed all of devDependencies o.k. in about ~20-30 seconds.

**Comment by markelog** [comment]
> Not sure how or why

If you run `npm i` with npm 2.x, it will show only the spinner while dependencies are installed. So i think `npm i` still could be a culprit

**Comment by ariya** [comment]
> Any new information with a verbose install?

What are you trying to do? I hope you're also troubleshooting JSCS failing tests, which should be actually reproduced using `npm run downstream` on Node.js v0.12.

**Comment by ariya** [comment]
Ha, my latest trick (see #1452) seems to work. Apparently, `git log` is potentially detecting the terminal as interactive tty and thus it may get stuck there. I've executed this trick twice on CircleCI and it successfully finished JSCS tests. Thus, I deem this speculative fix as good enough and will land it on master.

**Comment by hzoo** [comment]
Ah that's interesting! hopefully that fixes it then
