### ISSUE TITLE
Add intro videos to esprima.org

### ISSUE THREAD

**Issue by jasonLaster** [jquery/esprima#1249]
I'm not sure if this is the right place for esprima.org issues, but it'd be great if some of the instructional videos about esprima were on esprima.org

https://www.youtube.com/watch?v=XA8_hZfVecI
https://www.youtube.com/watch?v=UqTlToUYK1E

[Marionette.js](marionettejs.com) has improved it's video section a lot over the past six months. @jdaudier would you be interested in helping out?

**Comment by jdaudier** [comment]
@jasonLaster sure, just LMK more details about what you need me to do.  tks!

**Comment by ariya** [comment]
We should totally do this! How about `/doc/videos.html` or even `/doc/tutorials.html` (I don't have any strong preference on the name).

**Comment by ariya** [comment]
Some more useful ones:

* Using JavaScript to Teach JavaScript: https://www.youtube.com/watch?v=H4sSldXv_S4
* Unlocking the structure of your React applications with the AST: https://www.youtube.com/watch?v=OZGgVxFxSIs
* avaScript Syntax Tree Demystified: https://www.youtube.com/watch?v=954lRqSI_Ro

**Comment by ariya** [comment]
My old talks:

* Javascript Code Analysis with Esprima: https://www.youtube.com/watch?v=ACYZFkvq0Sk
*  Improving JavaScript Code Quality: https://www.youtube.com/watch?v=AyoLqC1U8Cc

**Comment by jasonLaster** [comment]
@ariya where are the other esprima.org files? When you say `/doc/videos.html` do you mean creating a doc folder in this repo?

**Comment by ariya** [comment]
@jasonLaster Look at the gh-pages branch: https://github.com/jquery/esprima/tree/gh-pages.

**Comment by ariya** [comment]
Those videos are now enjoyable at https://github.com/jquery/esprima/issues/1249.

If someone wants to improve it (include more relevant videos, add some short description), feel free to do so! Just make sure to create a pull request to the gh-pages branch.
