### ISSUE TITLE
Share code between Node.js test runner and Karma test runner

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1258]
Current the test runner for Node.js-based command-line (`test/unit-tests.js`) and Karma-based browser tests (`test/browser-tests.js`) do not share a lot of code, although some of the functionalities are similar. This issue tracks the effort to unify same bookkeeping activities in both runners.

**Comment by jasonLaster** [comment]
Here's a local branch that's tracking the work
https://github.com/jasonLaster/esprima/tree/unify-tests

**Comment by ariya** [comment]
Anything else to be done regarding this issue?

**Comment by jasonLaster** [comment]
Done

**Comment by jasonLaster** [comment]
It looks like `generateTestCase` was broken when two runners were unified. I'll have a patch soon.

**Comment by ariya** [comment]
I think we can safely resolve this one.
