### ISSUE TITLE
is it possible to get the list of declared variables in the code?

### ISSUE THREAD

**Issue by Prashanth-Nelli** [jquery/esprima#1268]
Right now i am using

 ```esprima.tokenize(code, options)```
but it is giving other details also along with variables.

i tried to use
```esprima.parse(code, options)```
it is giving nested tree structure so am unable to get the list of  declared variables.

**Comment by mikesherov** [comment]
Thanks for contributing, @Prashanth-Nelli ! There are plenty of 3rd party tools that analyse the tree structure (known as an ast) that gets the list of declared variables. For example: https://github.com/estools/escope

Please let me know if you have further questions

**Comment by Prashanth-Nelli** [comment]
Thanks @mikesherov for your help.
