### ISSUE TITLE
Customizing parsing options for the test case generator

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1272]
For a new test case, currently the baseline (`.tree.json`) is always created with the following parsing options: `{loc: true, range: true}`. This is not ideal because we want to generate the test case for e.g. tolerant parsing.

**Comment by ariya** [comment]
One proposal than @jasonLaster and I were discussing is an out-of-band information for the parsing options. Thus, each test case is arranged as in this example:

  * `foo.js` is the source to be parsed
  * `foo.options.json` is the parsing options used to parse it
  * `foo.tree.json` is the expected syntax tree (baseline)

If the corresponding options file does not exist, it is assumed to be the above default.

**Comment by ariya** [comment]
Side note: this is probably necessary so that we can complete #1270.

**Comment by jasonLaster** [comment]
https://gist.github.com/jasonLaster/10e46802c08de1d99e9d

**Comment by ariya** [comment]
Looks like we are not pursuing this at all. Will reopen if the idea is revived.
