### ISSUE TITLE
"Unexpected token" with import statements

### ISSUE THREAD

**Issue by nebrius** [jquery/esprima#1273]
Running the following gives an "Unexpected token" error:

```
esprima.parse('import foo from "bar"');
```

esprima 2.5.0
node 0.12.7
npm 3.2.0

The online parser demo at http://esprima.org/demo/parse.html also gives this error.

Is import/export syntax not supported yet?

**Comment by ariya** [comment]
You need to specify that it is a module that is being parsed (vs a script):

```js
esprima.parse('import foo from "bar"', { sourceType: 'module'} );
```

**Comment by nebrius** [comment]
Thanks, figures I was missing something simple :)

**Comment by ariya** [comment]
@nebrius Glad to know it's working for you :-)

**Comment by ramsunvtech** [comment]
Use like below.

```
esprima.parseModule('import foo from "bar"');
```
