### ISSUE TITLE
integrate an "issue closer" bot

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1277]
https://github.com/twbs/no-carrier seems interesting, similar to "trac-o-bot", the same bot jQuery has used for years which much success.

**Comment by ariya** [comment]
Is that a hosted version of such a bot already? If not, I'm not sure we have the time + effort to set it up.

**Comment by ariya** [comment]
I can't find a hosted instance of this that we can use right away. As of now, I don't think anyone of us has some bandwith to implement this. Thus, let's resolve this for now and revisit it again at some point when the opportunity presents itself.
