### ISSUE TITLE
Mocha Browser Runner does not complete

### ISSUE THREAD

**Issue by jasonLaster** [jquery/esprima#1278]
The mocha browser runner does not complete.

![](https://www.dropbox.com/s/xkmad55y5h9dzer/Screenshot%202015-08-12%2012.23.51.jpg?dl=1)

It fails on the ES6 Identifier invalid-lone-surrogate test `var source = '\uD800!';` because the source is not URI encodable. 

Why does mocha care that the source is URI encodable? Because, we're including the source in the test name and test names should be greppable in the URL.

**Comment by ariya** [comment]
@jasonLaster Is this now considered as resolved?

**Comment by jasonLaster** [comment]
Yes
