### ISSUE TITLE
Add a source runner

### ISSUE THREAD

**Issue by jasonLaster** [jquery/esprima#1280]
When I want to debug something in Esprima, I use a small page w/ esprima loaded. I believe @mikesherov does something similar.

Would it be nice to improve this process with a shared source runner? I've shared what I use here, but it could obviously be a lot better. If we want to move forward, I can polish and add a `package.json` script for launching the runner.

[source runner](https://gist.github.com/jasonLaster/32ece63e5b08698095e6)

![](https://www.dropbox.com/s/77lo07js8u3ie1a/Screenshot%202015-08-12%2017.44.57.jpg?dl=1)

**Comment by mikesherov** [comment]
Now that we can run the test suite in the browser though I don't need my run script!

**Comment by ariya** [comment]
:+1: 

It's useful for debugging! My main workflow is still using Node.js for troubleshooting (via WebStorm, thanks to its excellent V8 debugger support), but we still need such a runner if there is a bug e.g. only affecting a certain browser.

Right now, the practical way is to use http://esprima.org/demo/parse.html, perhaps with your own version of esprima.js. This runner will bridge the gap.

I think we can name the runner as `test/runner.html` or something along that line.

**Comment by jasonLaster** [comment]
@mikesherov, the test suite runs in ~2 seconds each reload, which can be frustrating if you're just looking to test one scenario.

@ariya `parse` is a good example, but being in `gh-pages` it's tough to test your changes. I like the parse options for comments, tolerate errors, etc and the tree viewer. The ideal solution would be to have one demo tool that is in master branch, but I don't wanto necessarily encur more overhead.

**Comment by ariya** [comment]
I'm fine with such a runner. `test/runner.html` is my proposed name, but feel free to suggest a better one :-)

**Comment by ariya** [comment]
@jasonLaster I think this can be safely marked as resolved?
