### ISSUE TITLE
Creating errors breaks in Safari (strict mode)

### ISSUE THREAD

**Issue by mgh** [jquery/esprima#1284]
Creating an `Error` and assigning to the `column` property breaks on the latest mobile and desktop Safari.  Removing `"use strict"` in esprima is a workaround, but seems like not the ideal solution.

Relevant line:
https://github.com/jquery/esprima/blob/master/esprima.js#L2395

Test case:
```
(function () { "use strict"; var e = new Error(); e.column = 1; })();

--> TypeError: Attempted to assign to readonly property.
```

The effect is that `esprima.parse` on invalid code throws the above `TypeError` rather than the expected `SyntaxError` in Safari.

**Comment by ariya** [comment]
Ouch, this is really bad. Thanks for catching this issue!
Let's see if we can come up with a workaround.

**Comment by michaelficarra** [comment]
I'm sure it's configurable. Just redefine it.

**Comment by gibson042** [comment]
`defineProperty` alone fails, but combining it with `Object.create` works: http://jsfiddle.net/krujd0gn/

**Comment by ariya** [comment]
@gibson042 I think you need to throw the error object to provoke Safari.

**Comment by ariya** [comment]
@gibson042 Ah never mind, I was mistaken! Your fiddle already demonstrated the issue (without throwing the error).

**Comment by ariya** [comment]
Related WebKit issue: https://bugs.webkit.org/show_bug.cgi?id=146047

**Comment by ariya** [comment]
@gibson042 I have a better understanding now regarding thrown Error object, see #1290.

**Comment by michaelficarra** [comment]
@ariya Why do we have two issues open for this problem?

**Comment by ariya** [comment]
> @ariya Why do we have two issues open for this problem?

Safari 8 vs WebKit nightly/Safari 9. Just to make sure that we understand the differences.
