### ISSUE TITLE
Safari: Error#column is read only

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1290]
This is related to #1284. See also: https://bugs.webkit.org/show_bug.cgi?id=146047

Some unit tests (that check for invalid syntax) fail on Safari. This is because `column` property of an `Error` object is read only.

Run this on Safari (or check this snippet: http://jsbin.com/pexocaruce/edit?js,console):

```js
function createError(msg) {
  var error = new Error(msg);
  error.column = 42;
  console.log('error.column', error.column);
 return error;
}

function throwError(msg) {
  throw createError(msg);
}

try {
  throwError('Hello Universe');
} catch (e) {
  console.log('e.column', e.column);
}
```

It should say that column is 25, despite the fact that its value is set to 42. Chrome and Firefox behave as expected, showing 42.

**Comment by ariya** [comment]
With this situation, any Error object that Esprima is throwing is going to have a wrong value for `column` on Safari >= 8. While we need a long term solution for this, for now we need to workaround it by having the test suite excludes `column` when comparing expected vs actual, if this situation is detected.

**Comment by gibson042** [comment]
Why not use the `Object.create` + `Object.defineProperty` solution from https://github.com/jquery/esprima/issues/1284#issuecomment-131298377 in strict-mode Safari so the property is correct there too?

**Comment by ariya** [comment]
@gibson042 Because that doesn't change the value of `column` property. In other word, the result for the above example is still 25, not the expected 42.

**Comment by michaelficarra** [comment]
@ariya It should, as long as the property is configurable. The problem with leaving it this way for now is that, in strict mode, the write throws an error instead of just silently failing. I think the best thing to do for now would be either use `Object.defineProperty` as @gibson042 suggests or testing whether it is writable using `Object.getOwnPropertyDescriptor`. If we can't depend on ES5+ stdlib functions, we'll just have to wrap the assignment with a try-catch.

**Comment by gibson042** [comment]
@ariya http://jsbin.com/zihasukaku/edit?js,console
```js
function createError(msg) {
  var error = Object.create(new Error(msg));
  Object.defineProperty(error, 'column', { value: 42 });
  return error;
}
```

**Comment by ariya** [comment]
@gibson042 With Safari 8, your JSBin snippet produces:

```
"e.column"
33
```

With Chrome and Firefox, the output is
```
"e.column"
"Corinthian"
```

**Comment by gibson042** [comment]
Ah, I didn't see the problem introduced by `throw`ing the error in Safari 8 (Safari 9 was fine). But it too can be resolved: http://jsbin.com/tecusujowu/edit?js,console

And note that even though the above works on other browsers, it is only needed for Safari.

**Comment by ariya** [comment]
> The problem with leaving it this way for now is that, in strict mode, the write throws an error instead of just silently failing.

That's the difference between Safari 8 and 9:
* Safari 8: no TypeError is thrown, but column has the wrong value
* Safari 9: "TypeError: Attempted to assign to readonly property."
