### ISSUE TITLE
NumericLiteral, several improvements

### ISSUE THREAD

**Issue by Mr21** [jquery/esprima#1298]
Hi :)

I think we can make some improvements about the **numeric literal**.
I have done this jsPerf here: http://jsperf.com/isdigit-opti to understand what is the best way to test some digits.

The PR related is #1297

I hope you like it

**Comment by ariya** [comment]
Thanks for the proposed idea!

We usually care about overall performance and not just microbenchmarks. Try to run `node test/benchmark.js` to get the understanding of the benchmark suite that we have. Usually, unless those numbers improve noticeably, there is not much incentive to optimize.

I do agree that a consistent set of function is good, at least from the readability stand point. I think your proposed change is already covered by the big forthcoming refactoring, see e.g. https://github.com/ariya/esprima/tree/typescript/src.

**Comment by Mr21** [comment]
Ahh it mean, actually the version `jquery/esprima` is outdated.

**Comment by ariya** [comment]
@Mr21 that's my experimental branch, we still want to explore the pros and cons, and also solving any kind of e.g. performance regression. This repo is still the upstream + stable version.

If you want to propose something, best is to either open a ticket here first or post a message to the [mailing list](https://groups.google.com/forum/#!forum/esprima).

**Comment by ariya** [comment]
Based on the discussion, this will be covered anyway in the forthcoming big refactoring.
