### ISSUE TITLE
Prohibit variable declaration with initializer in a for-in statement

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1309]
With ES 2015, initializer in a variable declaration of a for-in statement is a grammar error. Example:
```js
for (var x = 1 in y) {}
```

**Comment by ariya** [comment]
This is spawn from pull request #1302. We intentionally don't disallow now because doing that means that Esprima 2.x can't process any legacy valid ES5 code that happens to use the feature. As an illustration, there is a test in Esmangle that has the said construct.

**Comment by michaelficarra** [comment]
It's not an early error, it's a grammar error. And it applies to both for-of and for-in.

**Comment by ariya** [comment]
> It's not an early error, it's a grammar error.

Correct. Thanks for the notice.

**Comment by ariya** [comment]
Let's do this for 3.0, no more excuse!

As for the failing esmangle test, let's just use the principle: "If a test does not work, let's get rid of it" :smile:

**Comment by michaelficarra** [comment]
You might want to hold off, actually. There's discussion about reverting this because of web compatibility.

**Comment by ariya** [comment]
> You might want to hold off, actually.

Thanks for the heads-up.

**Comment by bakkot** [comment]
This form is [now permitted](https://github.com/tc39/ecma262/pull/614) in sloppy mode only, and only in its most basic form. The following should all be errors and are unlikely to change:

```js
"use strict"
for (var a = 0 in {});
```

```js
for (a = 0 in {}); // This was never legal; not sure why esprima accepts it.
```

```js
for (var {a} = 0 in {});
```

```js
for (var [a] = 0 in {});
```

**Comment by ariya** [comment]
I confirm the following behaviors with Node.js/V8:

`var` initializer in *sloppy mode* is **not** causing an error:
```js
$ node -e 'function f() { for (var i = 0 in []) {} }'
```

`var` initializer in *strict mode* is causing an error:
```js
$ node -e 'function f() { "use strict"; for (var i = 0 in []) {} }'
[eval]:1
function f() { "use strict"; for (var i = 0 in []) {} }
                                      ^^^^^
SyntaxError: for-in loop variable declaration may not have an initializer.
```

This is checked with the following versions:
```js
$ node -e "console.log(process.versions)"
{ http_parser: '2.7.0',
  node: '6.4.0',
  v8: '5.0.71.60',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }
```

Looking at [V8 error messages](https://chromium.googlesource.com/v8/v8/+/master/src/messages.h), this is an error named `ForInOfLoopInitializer`.

**Comment by ariya** [comment]
For clarity, I spawned the problem `for (a = 0 in {})` as #1561.
