### ISSUE TITLE
Ambiguous results for simple MemberExpressions

### ISSUE THREAD

**Issue by pieterhendrickx** [jquery/esprima#1319]
Consider the output of esprima.parse() of the following inputs:

1) a.b    -->  "property": {"type": "Identifier", "name": "b"}
2) a['b']   -->  "property": {"type": "Literal", "value": "b", "raw": "'b'" }
3) a[b]   --> "property": { "type": "Identifier", "name": "b"}

Issue 1: While 1 and 2 have the same javascript meaning, the output of the parse function is different. 
Issue 2: While 1 and 3 have a different javascript meaning, the output of the parse function is the same.

**Comment by ariya** [comment]
This is a problem in Esprima, but rather a flaw in the format inherited from [SpiderMonkey Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API), or as tracked in the [ESTree](https://github.com/estree/estree) project these days.

To properly distunguish all these cases, use the `computed` property of `MemberExpression` node.
