### ISSUE TITLE
Unicode/Hex Automatic Conversion?

### ISSUE THREAD

**Issue by bluesheeva** [jquery/esprima#1330]
Hi,
I use Esprima in a webpage to generate JavaScript AST. I passed the following JS code with Unicode characters for a variable initialization.

var ast = esprima.parse("var y = '\u004B';");

I got the following result for the init:
"init": {
                        "type": "Literal",
                        "value": "K",
                        "raw": "K'"
                    }
                }

The problem is I wish to get "raw": "'\\u004B'" instead of "K".  I run the code (var y = '\u004B';) in the online Esprima parser (http://esprima.org/demo/parse.html) and get the the result that I wanted. Question is why I didn't get the unicode characters for the "raw" in my implementation? I use Internet Explorer and the webpage is developed in Asp.Net. 

Also I should add that I did put a pointer on function parse(code, options) in esprima.js and found that the code parameter has the converted "K" in it instead of the unicode characters. 

Appreciate any pointer. Thanks!

**Comment by michaelficarra** [comment]
You wanted `var ast = esprima.parse("var y = '\\u004B';");`. Notice the extra backslash to escape the backslash in the string.

**Comment by ariya** [comment]
As @michaelficarra wrote, this is not a problem in Esprima.
