### ISSUE TITLE
API: Token delegator

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1332]
A consumer might want to process a token as it is being produced by the tokenizer. This can be achieved by using the [delegation pattern](http://best-practice-software-engineering.ifs.tuwien.ac.at/patterns/delegation.html).

Note: this is related to `tokenize()` and not `parse()`.

**Comment by ariya** [comment]
The delegator can be supplied in two different ways (though ideally we choose one and stick with it). In the following examples, it is assumed that:
```js
function processToken(token) {
  console.log('Receiving', token);
  return token;
}
```

**Alternative 1**: as another property to the options object. Example:
```js
esprima.tokenize(code, { range: true, delegate: processToken });
```

**Alternative 2**: as a third parameter. Example:
```js
esprima.tokenize(code, { range: true }, delegate: processToken );
```

There is a slight advantage of 2 as it is being explicit. This however can introduce a minor hassle of the need to use `null` (or another falsy value) if the second parameter is not necessary.

Other prior art examples of 2: [Mozilla Parser API Builder object](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API#Builder_objects) and [JSON.stringify's replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).

**Comment by ariya** [comment]
The main use case for the delegator is streaming processing of the incoming tokens. Waiting for the token array to be fully populated will consume both time and memory (see #1019).

In a tool such as a syntax highlighter (e.g. as a plugin to a text editor), the tool also wants to handle the token information directly and map it into its internal data structure, without the need to care for the return value of `tokenize`.

**Comment by mikesherov** [comment]
My opinion: I'd prefer it'd be "just another option", and I'd name it `tokenDelegate`. An additional positional parameter introduces the aforementioned trouble with second param null.

**Comment by gibson042** [comment]
I agree with @mikesherov.

**Comment by ariya** [comment]
On the other hand, almost likely the delegate function requires some sort of location information, hence the most common options object will be practically either `{ range: true }` or `{ loc: true }`.

A minor argument against "another option" is because the other options are typically of a primitive value (Boolean, in this case). Stuffing a function in there (where the function behaves more or less like a callback, in a typical practices) feels out of place.

**Comment by mikesherov** [comment]
But then, what about when we want to add a commentDelegate or even a nodeDelegate? Are those new parameters too? Or does the third parameter become an options object too, but just for callbacks?

**Comment by ariya** [comment]
@mikesherov In the context of this pure tokenizer, only a simple delegate (that accepts a token) makes sense.

**Comment by michaelficarra** [comment]
:-1:, we shouldn't be creating new interfaces that use callbacks like this. This is the perfect use case for a generator. The consumer will be able to consume tokens at their own pace, and the tokeniser will perform no more work than the consumer requires.

**Comment by ariya** [comment]
@michaelficarra Hyphotetical code example please?

**Comment by michaelficarra** [comment]
```js
for (let token of esprima.tokens(myCode)) {
  if (isTheTokenIWant(token)) break;
  // do something else with token?
}
```

**Comment by ariya** [comment]
Ah, but for-of is only ES2015 and surely we still want to support ES5.

**Comment by ariya** [comment]
It turns out that this requires some more work. Apparently, `advanceSlash()` relies on historical tokens for its work, thus it requires some bits of refactoring as well. I'll file a separate issue for that.
