### ISSUE TITLE
 parsed data doesn't have 'id' field in nodejs app(using the npm package version)

### ISSUE THREAD

**Issue by ranacseruet** [jquery/esprima#1335]
Try parsing this:

```
function abcd(){return "hello world"}
```
on the demo parser online(http://esprima.org/demo/parse.html), it shows that, the first 'body' element has an 'id' field with 'name' as the function name('abcd'). But when I try it with the esprima npm package in nodejs app, the parsed version doesn't have anything in the id filed, its set to 'null'.

**Comment by ariya** [comment]
Is there any test program that demonstrates the problem?

I defintely can't reproduct this. See the following (in Node.js REPL):

```js
> require('esprima').parse('function abcd(){return "hello world"}').body[0]
{ type: 'FunctionDeclaration',
  id: { type: 'Identifier', name: 'abcd' },
  params: [],
  defaults: [],
  body: { type: 'BlockStatement', body: [ [Object] ] },
  generator: false,
  expression: false }
```

**Comment by ranacseruet** [comment]
ah, I found the issue, it was on my app side. thanks for replying promptly!
