### ISSUE TITLE
Works online but not within Node?

### ISSUE THREAD

**Issue by kraftwer1** [jquery/esprima#1336]
I'm using the latest version of Esprima (2.6.0 as of now). This line of code compiles just fine online on http://esprima.org/demo/parse.html:

```javascript
export default 'test';
```

But it won't using it within my Node script. It spits `Line 1: Unexpected token` instead:

```javascript
var esprima = require("esprima");

try {
    esprima.parse("export default 'test';");
} catch (e) {
    console.log(e.message);
}
```

How's that possible? Am I missing any config option?

**Comment by michaelficarra** [comment]
You need to parse that text as a module.

**Comment by kraftwer1** [comment]
...what? :-)

**Comment by ariya** [comment]
See https://github.com/jquery/esprima/issues/1273#issuecomment-128443381.
