### ISSUE TITLE
MetaProperty implemented incorrectly

### ISSUE THREAD

**Issue by nzakas** [jquery/esprima#1338]
According to the spec, MetaProperty is:

```
interface MetaProperty <: Expression {
    type: "MetaProperty";
    meta: Identifier;
    property: Identifier;
}
```

However, Esprima uses strings for both `meta` and `property` rather than `Identifier` objects. (Espree also does this incorrectly.)

See http://esprima.org/demo/parse.html?code=function%20f()%20%7B%0A%20%20%20%20var%20x%20%3D%20new.target%3B%0A%7D%0A for an example.

**Comment by ariya** [comment]
Thanks for the notice! I think we ought to change this in 3.0.
