### ISSUE TITLE
Parse Error: ES6 Arrow Function Bind

### ISSUE THREAD

**Issue by jbest84** [jquery/esprima#1343]
`var fn = () => { return 'foo'; }.bind(window);`

Returns an error:
`Unexpected token .`

Work around:
Wrap the expression in parens: `var fn = (() => { return 'foo'; }.bind(window));`

**Comment by ariya** [comment]
Hmm, is this even valid?

**Comment by michaelficarra** [comment]
Nope, not a program.

**Comment by jbest84** [comment]
You are right. Chrome and Babel allow the syntax, but it does not bind and follows the spec.
