### ISSUE TITLE
Does this support whitespace?

### ISSUE THREAD

**Issue by limeblack** [jquery/esprima#1348]
Does this support whitespace?

**Comment by michaelficarra** [comment]
I don't know what this is supposed to mean.

**Comment by limeblack** [comment]
@michaelficarra Tokenization of white space so linebreaks are preserved when converting between the tokens and the original code.

**Comment by ariya** [comment]
White spaces won't be treated as a special token. However, you can refer to them if you infer the location of each node. Play with http://esprima.org/demo/parse.html while checking the "Index-based range" box.
