### ISSUE TITLE
Why filterTokenLocations?

### ISSUE THREAD

**Issue by sterpe** [jquery/esprima#1355]
I've been wondering for a while, why the tokens array from the parser provides tokens stripped of their location data?

**Comment by ariya** [comment]
It is perfectly valid of the user to request the list of tokens without the location information, e.g.:
```js
> esprima.parse('x', { tokens: true }).tokens
[ { type: 'Identifier', value: 'x' } ]
```

However, internally the parser needs the token location (e.g. for error reporting). Hence, unless `range` or `loc` is specified in the parsing options, then each token's location data will be filtered.

**Comment by ariya** [comment]
Note that this extra filtering post-processing is going away in the most recent refactoring (#1418).

**Comment by sterpe** [comment]
@ariya, cool.  Thanks.
