### ISSUE TITLE
TypeScript integration, suggested approach?

### ISSUE THREAD

**Issue by SamuelMarks** [jquery/esprima#1356]
3+ years ago this fork was created: https://github.com/Diullei/esprima-typeScript, but not maintained.

Pretty certain that both esprima and TypeScript have diverged sufficiently to warrant a completely new approach.

Unsure if I'll have the time, but want to give it a go. How should one approach adding TypeScript support to Esprima?

Thanks for all suggestions.

PS: Once complete, do you want it in `master`, a branch, or not at all? - If not at all, any advice on keeping the TypeScript components mostly independent, so it doesn't need to be updated on a similar frequency to jquery/esprima?

**Comment by michaelficarra** [comment]
@SamuelMarks: This is already completed on `master`. See https://github.com/jquery/esprima/commit/053975953ec0a5ff0d127f78c85f881a45bb3be6.

**Comment by SamuelMarks** [comment]
Fantastic news! :D

**Comment by SamuelMarks** [comment]
@michaelficarra: I've failed thus far, can you show me the estree output you get from this basic bit of TypeScript:

```
interface Bar {
    can: string;
    haz: boolean;
}

export const bar: Bar = { can: 'foo', haz: true };
```

Thanks

**Comment by mikesherov** [comment]
Hi @SamuelMarks @michaelficarra! I think what @SamuelMarks meant was using Esprima to parse typescript, whereas @michaelficarra meant we just re-implemented Esprima using typescript.

**Comment by ariya** [comment]
It is thus a reminder for all us to be careful with the choice of word. In this particular case, "integration" is an overloaded term and it is not immediately clear what it is supposed to mean.

For parsing TypeScript code, it is still recommended to use the official TypeScript itself (see [Using the Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)). Two TypeScript tools which every TypeScript project tends to use, [TSLint](https://github.com/palantir/tslint) and [tsfmt](https://github.com/vvakame/typescript-formatter), use this approach with quite a success.

There is another reason why it is better not to implement TypeScript parsing in Esprima. Esprima uses the de-facto AST format called [ESTree](https://github.com/estree/estree). Extending ESTree to support TypeScript-specific features not standardized by TC-39 (e.g.: type annotation) will be a lot of work, particularly since ESTree is designed with plain JavaScript in mind.

@SamuelMarks Any particular reason to parse TypeScript code with Esprima style of AST instead of the official TypeScript?

**Comment by SamuelMarks** [comment]
Thanks for your comments.

@ariya et al.: I am planning to bidirectionally code-generate TypeScript; from a DSL to TypeScript; then back from TypeScript to that DSL.

So it's important that I have an AST that's simple to mutate and emit. The TypeScript compiler API is not [yet] this... I did ask them.

Last night I begun work on reading the JavaScript to produce specialised TypeScript interfaces [for `d.ts` files] from Node.js using `esprima.parse` in a TypeScript project.

Should be able to hack together a solution this way, by just overwriting the `d.ts` whenever the `.js` changes.


PS: This codegen project will be open-sourced

**Comment by ariya** [comment]
@SamuelMarks In that case, I suggest creating a (friendly) fork so that you can experiment with the changes while we all can watch for the sideline as to how to ESTree gets extended and how the rest of the tools (parser, code generator) will be tweaked.

**Comment by SamuelMarks** [comment]
FYI: I've decided to put developing this fork to one side. Your comments espouse that extending esprima with TypeScript is nontrivial.

For now I'm happy enough to generate basic interfaces inferred from very specific objects. Here's the relevant snippet from my `README.md`:

>Example with "models/TUser.js", contains two variables `FFOOOOOOOOOOOOOOOOOOOO` and `BARRRRRR` containing:

```typescript
{
    identity: 'user_tbl',
    connection: 'postgres',
    attributes: {
        email: {
            type: 'string',
            required: true
        },
        password: {
            type: 'string',
            required: false
        },
        name: {
            type: 'string'
        }
    }
};
```

>Generating the interfaces; extending with `waterline.Record, waterline.Model`:

    tsc --sourcemap --module commonjs codegen/model_to_def.ts
    node codegen/model_to_def.js models/TUser.js 'extends waterline.Record, waterline.Model'

>Will create file "models/TUser.d.ts" containing:

```typescript
export interface FFOOOOOOOOOOOOOOOOOOOO extends waterline.Record, waterline.Model {
    email: string;
    password?: string;
    name?: string;
}

export interface BARRRRRR extends waterline.Record, waterline.Model {
    email: string;
    password?: string;
    name?: string;
}
```

Now that I have `Models` being well-enough generated, I'll be generating `Routes` then `Tests`.

I'll reopen this thread if I end up going back to the "extend esprima with typescript support" route.

**Comment by kristianmandrup** [comment]
Doesn't look like TypeScript is supported or it ever will, except when TypeScript and Javascript are merged some day in the future??...

**Comment by ayoreis** [comment]
> Doesn't look like TypeScript is supported or it ever will, except when TypeScript and Javascript are merged some day in the future??...

Looks like they will: https://github.com/tc39/proposal-type-annotations 😉
