### ISSUE TITLE
Parenthesized destructured assignments should fail to parse

### ISSUE THREAD

**Issue by nzakas** [jquery/esprima#1359]
The following code parses okay with the latest Esprima, but should throw an error:

```js
({Object = 0, String = 0}) = {};
```

The destructured lefthand sides cannot be surrounded by parentheses. (See https://github.com/ternjs/acorn/pull/258#issuecomment-143948423 for more.)

**Comment by ariya** [comment]
Is the same as #1164?

**Comment by michaelficarra** [comment]
Looks like it.

**Comment by nzakas** [comment]
Oops, sorry about that.
