### ISSUE TITLE
Add some library to autocomplete demo.

### ISSUE THREAD

**Issue by xgrommx** [jquery/esprima#1362]
Hello @ariya. How can I add some autocomplete for `lodash` in your example `autocomplete`?

**Comment by ariya** [comment]
Do you mean for http://esprima.org/demo/autocomplete.html? It may not easily work, because that autocompletion is done using [Orion](http://wiki.eclipse.org/Orion).

**Comment by ariya** [comment]
After taking another look, now I can fully confirm that you need to extend [Orion](http://wiki.eclipse.org/Orion) to do that. Please consult the Orion development team for further details. Thanks!
