### ISSUE TITLE
Revisit state tracking in the parser vs scanner

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1374]
For a better distribution of responsibilities, the state tracker needs some refactoring.

Token lookahead is necessary to determine the proper grammar production. This needs to exist in the parser as the scanner has no business regarding the production. The same goes for the extraneous location tracking for syntax node's location information.

The implementation of the reader algorithm for the pure tokenizer (i.e. `tokenize` API) shall not be in the parser as well. One day we will separate the tokenizer and find a new home for it, but for now it is sufficient to include it as part of the scanner.

**Comment by mikesherov** [comment]
Wonder if we need to think about how this effects template token production. `}` is ambiguous without a object/template stack.

**Comment by ariya** [comment]
> Wonder if we need to think about how this effects template token production

There should not be any conflict, template is handled solely in the scanner.
