### ISSUE TITLE
Bug about use future reserved word as identifier

### ISSUE THREAD

**Issue by spket** [jquery/esprima#1376]
loose mode
```javascript
> require('esprima').parse('let = 1')
Error: Line 1: Invalid left-hand side in assignment
```
Expected: a syntax tree
Actual: an exception

**Comment by fkling** [comment]
What do the comments mean? That those should be valid / invalid or that they are currently valid / invalid in esprima and should or should not be? Please actually describe the issue properly.

**Comment by spket** [comment]
in loose mode, esprima treat 1st as valid, 2nd as invalid, all those should be valid in non-strict mode

**Comment by michaelficarra** [comment]
esprima is correct here. `private` is only reserved in strict mode. `let` is disallowed in a LexicalDeclaration because of static semantic restrictions in [13.3.1.1](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-let-and-const-declarations-static-semantics-early-errors).

**Comment by ariya** [comment]
@spket I suggest using the (test case, expected, actual) form for filing an issue. For an example to follow, see e.g. #1229.

**Comment by spket** [comment]
Thanks for suggestion, edited
