### ISSUE TITLE
Support for Aurelia code

### ISSUE THREAD

**Issue by matanster** [jquery/esprima#1387]
Hi There,

It seems this is the best library for getting an AST (for javascript code). As I understand ES6 is very well supported (?!). However for code using a framework like Aurelia, we'd likely need some special support, or your suggestions. E.g. Aurelia code uses a lot of Annotations, e.g. see in this [sample Aurelia project](https://github.com/CANVE/canve-viz/blob/551ea321088ee58587ab8bf5db6e5f5411355ddd/src/graph/graph.js#L16-L22
) WIP:

A short snippet:
```
@customAttribute('graph')
@inject(Element, EventAggregator, GraphLibD3, GraphModel, GraphFinder, GraphModifier, TaskQueue, ActionManager)
/* jshint ignore:end */
export class Graph {
  /* jshint ignore:start */
  @bindable data;
  @bindable graphInteractionModel;
```

How would you suggest going about it? I would assume this scenario has been brought up regardless of the yet newish Aurelia framework before...

We get Error: `Line 16: Unexpected token ILLEGAL` on [the demo page of ESPRIMA](http://esprima.org/demo/parse.html), for it.

Please be gentle, I'm not heavily immersed in the javascript aspects of all this, coming mostly from the world of Scala...

**Comment by ariya** [comment]
I believe annotations like that haven't been standardized yet.

@michaelficarra Do you where we can find the information on the annotation proposal (e.g. what stage it's in, etc)? I'm sure it's somewhere around https://github.com/tc39/ecma262 but I can't really spot it.

**Comment by michaelficarra** [comment]
It's called decorators and it's at stage 1 (very early).

**Comment by ariya** [comment]
Thus, until it becomes a standard or close enough to become a standard, it is unlikely that we will add support for it.

@matanster You may want to check e.g. TypeScript, which has decorator support.

**Comment by matanster** [comment]
:+1: Thanks!
And we can likely transpile with Babel as a pre-processing step, until then.

**Comment by matanster** [comment]
@michaelficarra would you know where can the "official stage" (e.g. stage 1) of an ES7 feature like this one, be tracked?

**Comment by michaelficarra** [comment]
https://github.com/tc39/ecma262/blob/master/README.md

**Comment by matanster** [comment]
Thanks!!

**Comment by englercj** [comment]
Looks like [Class and Property Decorators](https://github.com/wycats/javascript-decorators/blob/master/README.md) are now stage 2. At what stage will esprima consider including them?

**Comment by michaelficarra** [comment]
Certainly no earlier than 3.

**Comment by englercj** [comment]
Cool, was just curious. Thanks!
