### ISSUE TITLE
Absurd inconistency.

### ISSUE THREAD

**Issue by IngwiePhoenix** [jquery/esprima#1411]
I just....am so confused.

This: http://esprima.org/demo/parse.html?code=import%20foo%20from%20%22bar%22%3B
works fine.

Similar code ran through `esparse` spills
```
Ingwie@Ingwies-Macbook-Pro.local ~/W/oj-tests $ cat t.js
import fs from "fs";
Ingwie@Ingwies-Macbook-Pro.local ~/W/oj-tests $ esparse t.js
Error: Line 1: Unexpected token
```

What is the difference? When I open the JS console on the site and query `esprima.version`, it reports `2.7.0`. But that is also reported by `esparse -v`... I am sooooo confused... It'd be nice to know what's up.

Kind regards,
Ingwie

**Comment by IngwiePhoenix** [comment]
Resolved.

Its super hidden in the docs, but `{sourceType: "module"}` is the way to go.

Plus, the command line tools **don't** support this option. Please add that...that led to a lot of confusion here.

**Comment by ariya** [comment]
It's indeed confusing, but it's dubious how we can extend the CLI to support this without adding a command-line argument. Even in this case, a user will be still left confused. Suggestions for improvements are welcomed.
