### ISSUE TITLE
esprima.js

### ISSUE THREAD

**Issue by cpburnz** [jquery/esprima#1412]
How do you download or build "esprima.js"? Is there a guide somewhere? I see no mention for how you actually get "esprima.js" in the README. I'm not interested in installing it through NPM because I want to run it through Rhino.

**Comment by ariya** [comment]
It's mentioned in [documentation](http://esprima.org/doc/index.html). The easiest way is to grab the one from CDN, e.g. https://cdn.rawgit.com/jquery/esprima/2.7.0/esprima.js.

**Comment by ariya** [comment]
I'll close this. Let me know @cpburnz if you still have difficulties getting the file.

**Comment by simap** [comment]
This is still not very easy to find, and I don't see anything in the docs. I'm not sure I'm doing it right. My best guess is from looking at the package.json and running `npm run compile` but there's no minified version. CDNs don't seem to have v4.

**Comment by ariya** [comment]
@simap It's in the documentation (Chapter 1, search for Using Esprima in a web browser).

**Comment by simap** [comment]
@ariya Ah, I see it there now on a CDN link. I don't know why, but I did spent a lot of time looking for it on the site. I must have been looking for the wrong things, expecting a download, or how to build kind of thing. Thank you.
