### ISSUE TITLE
type Expression should include Identifier

### ISSUE THREAD

**Issue by Nathan-Wall** [jquery/esprima#1420]
The `Expression` type in nodes.ts does not include `Identifier`, but in `parsePrimaryExpression` in parse.ts the `expr: Expression` variable is set to an `Identifier` in many code paths. I think it makes sense to classify `Identifier` as an `Expression` because an `ExpressionStatement`'s `expression` property can just be set to an `Identifier`.

The reason TypeScript doesn't complain is because `Expression` includes `ThisExpression` which only has a `type` property defined on it, making it a super-type of `Identifier` (as least as far as TypeScript's duck-typing is concerned).

Incidentally, this means TypeScript will consider *any* node a valid sub-type of `Expression`. One possible workaround (though ugly) could be to add some breaking property to `ThisExpression` like `__isThisExpression__ = true`. I'm not sure what trade-offs are right for Esprima... just pointing it out.

**Comment by ariya** [comment]
Thanks for the notice! This is indeed a good catch. I think we definitely ought to expand `Expression` to include `Identifier`.

I doubt that distinguishing `ThisExpression` vs `Expression` (e.g. breaking property workaround) is a necessity. We use the type information as additional guidance, not necessarily as the ultimate source of truth.

**Comment by Nathan-Wall** [comment]
It looks like this change was undone in https://github.com/jquery/esprima/commit/38afd2f371cd37f280eef3dfbfbd388676e29ed2 . Bad merge?

Also, should `UpdateExpression` be an `Expression`?

**Comment by Nathan-Wall** [comment]
I also think `Literal` should be a sub-type of `Expression`.

**Comment by ariya** [comment]
Oops, seems like indeed a bad merge. I'll try to rectify it.
