### ISSUE TITLE
Drop-in for OJ

### ISSUE THREAD

**Issue by IngwiePhoenix** [jquery/esprima#1437]
I am a huge fan of [oj](https://github.com/musictheory/oj) - which is an ObjC dialect for JavaScript.

For it's parsing step, it actually uses Esprima, even if it's just a modified version. So I wondered, is `esprima-fb` feature-identical with Esprima 2.7? So that OJ could use `esprima-fb` to understand JSX, too?

**Comment by ariya** [comment]
esprima-fb is Facebook's fork (not official part of this project) and Facebook decided to stop developing and maintaining it. See https://github.com/facebookarchive/esprima.
