### ISSUE TITLE
Traversing AST

### ISSUE THREAD

**Issue by vitaly-t** [jquery/esprima#1441]
Does this library offer an optimized way for traversing through the generated AST tree?

For example, I previously used UglifyJS, which does have that, through their TreeWalker. See here: http://stackoverflow.com/questions/34524618/enumerate-regular-expressions-via-uglifyjs

If I'm trying to parse a file of 30,000 lines (AngularJS 1.5), it takes only 150ms, but traversing the tree with the head-on approach takes a whole 1 minute on top of that, that's like a shot in the head.

Is there way to do it quickly?

In my particular case I need to enumerate all regEx literals.

**Comment by michaelficarra** [comment]
https://github.com/estools/estraverse

**Comment by vitaly-t** [comment]
That works great! Thank you!!! :+1:

**Comment by ariya** [comment]
If you only want to discover every valid regular expression literal, there is a simpler way. You don't even need to walk the entire tree. Take a look at the following example script:
```js
var esprima = require('esprima');
var code = 'var x = /foo/bar/g';
var tree = esprima.parse(code, { loc: true, tokens: true });
tree.tokens.forEach(function (t) {
    if (t.type === 'RegularExpression') {
        console.log('Line', t.loc.start.line, t.value);
    }
});
```

**Comment by vitaly-t** [comment]
@ariya Excellent!WIll it produce the same result is the following code? - 
```js
var esprima = require('esprima');
var estraverse = require('estraverse');

function parseThroughEsprima(code) {
    var parsedCode = esprima.parse(code, {
        range: true,
        loc: true
    });
    var data = {};
    estraverse.traverse(parsedCode, {
        enter: function (node) {
            if (node.type === 'Literal' && node.regex) {
                var name = node.loc.start.line - 1;
                if (!data[name]) {
                    data[name] = [];
                }
                data[name].push({
                    start: node.loc.start.column + 1,
                    end: node.loc.end.column - 1
                });
            }
        }
    });
    return data;
}
```

**Comment by ariya** [comment]
@vitaly-t Yes, the outcome will be the same.

**Comment by ariya** [comment]
And if you feel adventurous, try also this variant. Compare the correctness and the speed, then decide yourself which one (this vs the previous) suits your need.
```js
var esprima = require('esprima');
var code = 'var x = /foo/bar/g';
esprima.tokenize(code, { loc: true }, function (t) {
    if (t.type === 'RegularExpression') {
        console.log('Line', t.loc.start.line, t.value);
    }
});
```
(And yes, I'm still behind w.r.t documenting tokenizer vs parser, the above token delegate, etc. Perhaps some time in the next few weeks...)

**Comment by vitaly-t** [comment]
@ariya Thank you so much!

I'm going to update my code now. By the way, it is for this public library: [decomment](https://github.com/vitaly-t/decomment).

**Comment by vitaly-t** [comment]
@ariya I am amazed that method `tokenie` reports ranges with absolute positioning, as opposed to the relative positioning as method `parse` does.

That means I can throw away a bit of code where I had to translate relative positions to absolute in my code. 

This is really good. Thank you again!

**Comment by vitaly-t** [comment]
@ariya This switch over to `tokenize` gave my library 3 times the performance boost.

Did I already say thank you? :)

**Comment by ariya** [comment]
@vitaly-t Good to know it's working well for you!

I'm not sure I understand the relative vs absolute positioning. Both `parse` and `tokenize` should return the same location information. You have two choices where `loc` set to true adds the location information in a form of line number and column and `range` set to true adds the location information with a zero-based index.

I saw that your `parseRegEx` function only needs the index-based location. In that case, you should set `range` to true and forget about `loc` completely. This optimizes the code even further since the tokenizer doesn't have to prepare the line number and column information.

BTW, since your tool is related to comment handling, the following example script might be interesting for your case :-)
```js
var esprima = require('esprima');
var code = 'answer = 42 // universe';
esprima.tokenize(code, { comment: true, range: true }, function (t) {
    if (t.type === 'LineComment') {
        console.log('at index', t.range[0], t.value);
    }
});
```

**Comment by vitaly-t** [comment]
@ariya Thank you about parameter `loc`, I have removed it now, and it works better :)

As for the comments, my library handles them in its own way, configurable way. I only needed positions of all regular expressions for esprima, to avoid breaking them.

Thank you again!

**Comment by vitaly-t** [comment]
@ariya I'm afraid I have to retract my previous statement about option `loc`. Removing it made `tokenize` perform 40% slower than with `loc`. I don't know why, but that's what my tests are showing.

I have to re-enable it back, even though I do not need location details.

**Comment by ariya** [comment]
> Removing it made tokenize perform 40% slower than with loc.

That's definitely weird. But I agree with you, just keep using the settings that works for decomment.

**Comment by vitaly-t** [comment]
I would take a wild guess here that your algorithm makes a good use of the location when it is requested, i.e. better than it would when location isn't tracked.
