### ISSUE TITLE
Why not esprima support customization  parse the string?

### ISSUE THREAD

**Issue by janryWang** [jquery/esprima#1443]
For example, I just want to parse a single line of expression，But I do not want to use too much redundant code,like this
```
esprima.parse("1 * a  > 10 ? /\d+/.test(b) ? a + b : cc : kk")

or 

esprima.parse("[1,2,3,4].map((a)=>a+5)")
```

**Comment by ariya** [comment]
It's complicated, see https://groups.google.com/d/msg/esprima/0Iyat8NdGxE/s8IbVEFQBQAJ for details.
In short: the parser has an internal state designed only to consume a program or a module, not every possible kind of terminals.
