### ISSUE TITLE
Documentation / missing info

### ISSUE THREAD

**Issue by Marshallx** [jquery/esprima#1456]
I wasn't able to find the parsing option "attachComment" in the Esprima documentation - only found it through a third party's issue list as a request to make use of it.
Is there a more up to date version of the docs? If so, website should probably point to it, else docs need updating!

Thanks.

**Comment by ariya** [comment]
Our documentation needs an overhaul, particularly for the upcoming 3.x series. Meanwhile, I'll check in a quick mention of this particular option.
