### ISSUE TITLE
In variable declaration, in object destructuring, shorthand property with default should have true shorthand field

### ISSUE THREAD

**Issue by zjmiller** [jquery/esprima#1459]
Test case:

```JavaScript
> require('esprima').parse('var {a = b} = c;').body[0].declarations[0].id.properties[0]
```

Actual output:

```JavaScript
{ type: 'Property',
  key: { type: 'Identifier', name: 'a' },
  computed: false,
  value: 
   { type: 'AssignmentPattern',
     left: { type: 'Identifier', name: 'a' },
     right: { type: 'Identifier', name: 'b' } },
  kind: 'init',
  method: false,
  shorthand: false }
```

Expected:

```JavaScript
{ type: 'Property',
  key: { type: 'Identifier', name: 'a' },
  computed: false,
  value: 
   { type: 'AssignmentPattern',
     left: { type: 'Identifier', name: 'a' },
     right: { type: 'Identifier', name: 'b' } },
  kind: 'init',
  method: false,
  shorthand: true }
```

**Comment by ariya** [comment]
Do you mean "...should have *true* shorthand field" instead?

**Comment by zjmiller** [comment]
Right of course. I'll edit it.

**Comment by michaelficarra** [comment]
The shorthand value doesn't mean anything for this node, right? Can't it be either value?

**Comment by ariya** [comment]
It should be consistent with the case without `AssignmentPattern`. Compare to this (correct):

```js
> require('esprima').parse('var {x} = y;').body[0].declarations[0].id.properties[0]
{ type: 'Property',
  key: { type: 'Identifier', name: 'x' },
  computed: false,
  value: { type: 'Identifier', name: 'x' },
  kind: 'init',
  method: false,
  shorthand: true }
```

**Comment by zjmiller** [comment]
The shorthand value is the only thing distinguishing `var {a = b} = c;` from `var {a: a = b} = c;`. These behave the same, but I think it makes sense for a parser to focus on the syntax and pretty much ignore behavior. Also, there's something to be said for uniformity. Esprima, in assignment expressions, gives the property in `{a = b}` a shorthand value of true. Acorn, in both assignment expressions and variable declarations, gives the property in `{a = b}` a shorthand value of true. Given this, it's odd for Esprima, in variable declarations, to give the property in `{a = b}` a shorthand value of false.

This kind of inconsistency can make life harder for downstream projects. For example, escodegen, when generating a property, looks at the shorthand value to determine whether to write just the key field or the key field, a colon, and the value field. So, giving `var {a = b} = c;` to Esprima, and giving the AST to escodgen, results in the string `var {a: a = b} = c;`. The false shorthand field means escodgen adds unnecessary characters here (and doesn't do so when given the Acorn AST).

**Comment by michaelficarra** [comment]
Makes sense. :+1:.

**Comment by ariya** [comment]
Yup, I agree. I'm all for consistency :+1:

**Comment by ariya** [comment]
For completeness: I've backported this and the new Esprima 2.7.2 also contains this fix.
