### ISSUE TITLE
Support for comma first

### ISSUE THREAD

**Issue by asdf23** [jquery/esprima#1465]
I would like to reformat code to have comma-first styling for json objects.
Case in point:
```
var a = ({
     Hello: "hi"
    ,World: "there"
});
```
Preceeding Hello ideally would be 1 tab and 1 space

**Comment by michaelficarra** [comment]
This is a parser. You probably meant to open this issue on a different project.

**Comment by mikesherov** [comment]
Right, this seems like an issue for ESLint, JSCS, or similar. Thanks for contributing!

**Comment by asdf23** [comment]
Your site does this: http://esprima.org/demo/rewrite.html

**Comment by ariya** [comment]
http://esprima.org/demo/rewrite.html is actually only a demo. It's not meant for a full-featured tool.
