### ISSUE TITLE
a ? yield : b fails to parse

### ISSUE THREAD

**Issue by ianwjhalliday** [jquery/esprima#1469]
Try this code on http://esprima.org/demo/rewrite.html

``` javascript
function* gf() {
    var foo = false;
    return foo ? (yield* (yield)) : 10;
}
```

The first rewrite removes the parentheses around the `yield*` and `yield` expressions.  This produces syntactically invalid code which you can see by then pressing the rewrite button again, and esprima complains that an unexpected colon token was found.

**Comment by michaelficarra** [comment]
It doesn't produce syntactically invalid code, actually. It just seems that esprima has trouble parsing

```js
function* g(){ a ? yield : b; }
```

**Comment by ianwjhalliday** [comment]
Oh, whoops, yep you're right.
