### ISSUE TITLE
Tolerate broken after dot.

### ISSUE THREAD

**Issue by gorkem** [jquery/esprima#1480]
The master branch of esprima throws an exception due to the error`Line 1: Unexpected end of input.`

for the following code that is broken after dot on a member access. 

> `var foo = { bar:8};\nfoo.`

It would be greatly helpful to tools such as linters, code editors, if the broken member access is tolerated and the error would only be listed in the errors array when `tolerate:true` is given for config.

A few more example cases to be considered

> `var bar = { ooo:this.}`
> 
> `var foo = { at: { bar: 0} };\nfoo[at.foo.bar].`

**Comment by ariya** [comment]
Unfortunately, this does not seem to be possible without a major surgery and a redesign on how the parser tackles various error. I'm sure we'll get there at some point, but let's hold that off and revisit this again in the near future.
