### ISSUE TITLE
Tolerate unterminated functions

### ISSUE THREAD

**Issue by gorkem** [jquery/esprima#1482]
Functions have two cases that would be great if they can be tolerated on the tolerant mode.
1. When the  closing`}`is missing. An example of this would be `function foo() {\n    return baz;`
2. When the closing ) is missing. An example of this would be `function foo(s) {}\nf("baz"`

**Comment by asdf23** [comment]
I was looking at issues randomly and saw this one. I dont understand why anyone would want this. You can't  parse invalid code. I think that the best c compiler would have to guess at where the error was and would not do anything more than to throw an error. What you probably want instead is some sort of white space fixer. I do not think one exists that can fix this.

**Comment by gorkem** [comment]
esprima is not a c compiler it is a parser that generate AST trees that other tools can operate on. Usually a compiler is the part that converts the AST tree to another format that may be executed. Also tolerant mode does not mean that error is not reported, it just means the resulting AST tree is generated.

In this particular case,  AST generated by esprima is used to provide content assist on editors.

**Comment by jbmonroe** [comment]
Sorry, can't agree.  Given that JS supports interior functions, how would one know when foo() ended?  I don't think the AST tree would be correct.

**Comment by ariya** [comment]
This is similar to #1480. Unfortunately, it may take a while until the underlying error handling can be massively redesigned until we can achieve this. Let's hold off and revisit this again in the near future.
