### ISSUE TITLE
Unable to parse part of a function without a name...

### ISSUE THREAD

**Issue by jogibear9988** [jquery/esprima#1483]
I'd like to generate smth. like IQueryable for Javascript.

For this I need to parse following function (wich I get as a Parameter)

function (x) { return x.content == "aa"; }

this does not work, because function has no name

**Comment by michaelficarra** [comment]
As you've been told elsewhere (https://github.com/ternjs/acorn/issues/390, https://github.com/shapesecurity/shift-parser-js/issues/278), this is not a program and should not parse.
