### ISSUE TITLE
Incorrectly accepts invalid LabeledStatement (ES2015)

### ISSUE THREAD

**Issue by fkling** [jquery/esprima#1484]
If I understand the spec correctly ([§13.13](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-labelled-statements)) , the following statements should result in a syntax errors:

```
a: class abc {}
c: function* bar() {}
```

Grammar:

```
LabelledStatement:
    LabelIdentifier : LabelledItem

LabelledItem :
  Statement
  FunctionDeclaration
```

`let`/`const` declarations, generation functions and class declarations are neither `Statement`s nor `FunctionDeclaration`s.

FWIW, most other parser seem to be behave the same way. Only shift and traceur are throwing errors. This makes me wonder whether this is an intentional deviation from the spec for compatibility reasons? I also opened an issue about this for acorn: https://github.com/ternjs/acorn/issues/393 .

http://astexplorer.net/#/QOCdiNhTai (the second example is commented out because esprima throws the error "Line 6: Use of future reserved word in strict mode", so it seems it got that one right at least?)

**Comment by fkling** [comment]
13.1.1 also disallows the labeled item to be a FunctionDeclaration. I.e `a: function foo() {}` is invalid too. I'm curious whether this should be parsed as function expression though (not that it would make any sense).

**Comment by michaelficarra** [comment]
Confirmed. Each of the LabeledStatements in your link should be errors in both strict and sloppy mode, and the FunctionDeclaration one in your second comment should be an error in strict mode only.
