### ISSUE TITLE
Can't use 'type' as the name of any function variable. (Under special circumstances)

### ISSUE THREAD

**Issue by almosnow** [jquery/esprima#1487]
Check it out trying to parse

    (function(a, b, c) { console.log('WOO'); })() // WORKS

but

    (function(a, b, type) { console.log('SUCKS'); })() // DOESN'T

Using esprima on node, fresh install, `npm install esprima` and didn't mess with anything.

By the way, strict mode is broken but I guess that's 'expected behavior'.

**Comment by fkling** [comment]
Seems to work fine here: http://astexplorer.net/#/7yRUWlUUoo and with my local esprima installation (fresh install).

**Comment by almosnow** [comment]
Thanks fkling,

I tried on a different node project and found that it didn't happen, went to investigate further, turns out I have a dependency that does this:

    Object.defineProperty(Object.prototype, '$type', { configurable:true, enumerable:false, get:function() { ... } });

So apparently this behvior only happens when:

1. You define a property on an object that starts with '$'
2. You then try to use that identifier as the name of a function variable

Weird, would be nice to see why does that happen, I wish I would know more about the internals of esprima.

**Comment by michaelficarra** [comment]
Ha, I know why this is happening. I will submit a fix later.

**Comment by ariya** [comment]
This is fixed in master branch thanks to @michaelficarra.

Although this case might not happen very often, I'm contemplating of backporting the fix to 2.7 for the sake of correctness.
