### ISSUE TITLE
esprima.tokenize throw an "Invalid regular expression: missing /"

### ISSUE THREAD

**Issue by loopArray** [jquery/esprima#1493]
When I used esprima.tokenize to deal with the JS file, it gave me a "regular expression: missing Invalid /" error, but I used the "esprima.parse" to deal with when it is normal. Not very understand why not the same, I should use which one? Attached I deal with the code:
```
function abs(org, count){
    // heading comment
    count = count || 1; 
    return org /= count; // is Regx?
} 
```

**Comment by ariya** [comment]
Thanks for filing the report! Looks like I also discover a very similar defect: #1516.

**Comment by ariya** [comment]
Fixed in 2.x branch.
