### ISSUE TITLE
let declaration in a ForStatement's init has an end location different from a var declaration

### ISSUE THREAD

**Issue by nenionoda** [jquery/esprima#1498]
Hello
There looks to be an inconsistency in marking the "end" locations when parsing var and let declaration in a for's init:
```javascript
var l = require('esprima');
console.log( l .parse('for(var l  ;;)break;',{loc: true, range: true}).body[0].init.range, // [4 ,9 ], despite the space
             l .parse('for(let l  ;;)break;',{loc: true, range: true}).body[0].init.range) // [4 , 12], why?
```
looks like the let declarations ends in the ';', even though the 'var' doesn't. not sure whether it is inconsistent or intentional.

**Comment by michaelficarra** [comment]
I'd say this is expected. See the grammar productions for [IterationStatement](https://tc39.github.io/ecma262/#sec-iteration-statements):

```
for ( var VariableDeclarationList[~In, ?Yield] ; Expression[+In, ?Yield]opt; Expression[+In, ?Yield]opt ) Statement[?Yield, ?Return]
for ( LexicalDeclaration[~In, ?Yield] Expression[+In, ?Yield]opt ; Expression[+In, ?Yield]opt ) Statement[?Yield, ?Return]
```

LexicalDeclaration includes the `;`.

**Comment by nenionoda** [comment]
Thanks a lot  @michaelficarra; Shame on the spec, it made me stand corrected :wink:
