### ISSUE TITLE
Tests that are probably wrong by themselves

### ISSUE THREAD

**Issue by nenionoda** [jquery/esprima#1501]
[should](https://github.com/jquery/esprima/blob/master/test/fixtures/ES6/binding-pattern/array-pattern/for-let-let.js) [themselves](https://github.com/jquery/esprima/blob/master/test/fixtures/ES6/template-literals/literal-escape-sequences.source.js)
 [be](https://github.com/jquery/esprima/blob/master/test/fixtures/statement/iteration/for-let-let.js) [also](https://github.com/jquery/esprima/blob/master/test/fixtures/statement/iteration/migrated_0012.js) [credible](https://github.com/jquery/esprima/blob/master/test/fixtures/ES6/binding-pattern/object-pattern/for-let-let.js)

**Comment by mathiasbynens** [comment]
What makes you think these are wrong?

**Comment by nenionoda** [comment]
* https://github.com/jquery/esprima/blob/master/test/fixtures/ES6/binding-pattern/array-pattern/for-let-let.js
   * let [x = let] has no initializer after it, even though the spec says it must.

* https://github.com/jquery/esprima/blob/master/test/fixtures/ES6/template-literals/literal-escape-sequences.source.js
   * \u0 is not a valid escape sequence; not as far as i know at least

* https://github.com/jquery/esprima/blob/master/test/fixtures/statement/iteration/for-let-let.js
  * this one is not a syntax error; [the parse that corresponds to it](https://github.com/jquery/esprima/blob/master/test/fixtures/statement/iteration/for-let-let.tree.json), though, look to have a slight misunderstanding in where to mark a for's init component's end when the init is a let declaration. compare `esprima.parse('for(let l;;)break;',{loc:true,range:true}).body[0].init.range` and `esprima.parse('for(let l ;;)break;',{loc:true,range:true}).body[0].init.range` with `esprima.parse('for(var l;;)break;',{loc:true,range:true}).body[0].init.range` and `esprima.parse('for(var l ;;)break;',{loc:true,range:true}).body[0].init.range`; you would then agree with me :)

* https://github.com/jquery/esprima/blob/master/test/fixtures/statement/iteration/for-let-let.js
  * same as above, added merely for propaganda's sake ;)

* https://github.com/jquery/esprima/blob/master/test/fixtures/ES6/binding-pattern/object-pattern/for-let-let.js
  * please not the 'let {x: y = let}'; the spec says it must have an initializer unless it is a ForInStatement's init; in the above, it has no no initializer, nor is it a ForInStatement's init.

**Comment by michaelficarra** [comment]
@nenionoda The `\u0` case you pointed out is indeed a broken test. The rest of your claims are wrong. See the [LexicalDeclaration](https://tc39.github.io/ecma262/#prod-LexicalDeclaration) production. It includes the semicolon, and an initialiser is not allowed.

**Comment by michaelficarra** [comment]
Inspired by this issue, I went through and found a bunch of invalid tests. See #1502. Since it includes the one invalid test you mentioned, I think we can close this now.

**Comment by bakkot** [comment]
@michaelficarra, I'm not convinced the first one is valid; this might be [a bug in Shift too](http://shift-ast.org/parser.html?type=Script&code=for%20(let%20[x%20=%20let];;)%20{}).

The LexicalDeclaration production you boils down to a list of [LexicalBindings](https://tc39.github.io/ecma262/#prod-LexicalBinding), and the initializer is not optional in the BindingPattern case of LexicalBinding. What would it even mean?

Note that the test is a `for` statement, not `for-in` or `for-of`.

**Comment by michaelficarra** [comment]
> Note that the test is a for statement, not for-in or for-of.

Ah, right. That combined with the confirmation from the Shift demo confused me. I'll open an issue in Shift.

**Comment by nenionoda** [comment]
@michaelficarra please read issue i have listed above. `for( var [l];; )` break; is wrong; `for ( var [l] in list)break;` is not); `for( var {l: v};; )break;` break is also wrong. what isn't wrong, is `for( var {l: v } in list)break;`; I feel highly disappointed (and frustrated) when I find a person I have faith in calls his faults mine.

**Comment by nenionoda** [comment]
I especially mean #1498

**Comment by michaelficarra** [comment]
@nenionoda Sorry, I did not mean to offend with my terse rejection. I've given my rationale in #1498. For the init related issues, I've already agreed that those are issues after @bakkot cleared up my confusion around the difference between for-in/for-of init and for init.

**Comment by nenionoda** [comment]
@michaelficarra Thanks! Like the saying goes, many find it easier to forgive people for being wrong than being right; I must try my best to forgive you (for being right :wink:)
