### ISSUE TITLE
this is valid: `export {while as id} from "module"` but does not parse

### ISSUE THREAD

**Issue by nenionoda** [jquery/esprima#1504]
hello
`export {while as id}`isn't valid; `export {while as id} from "module"`, though, _is_ valid. Thanks a lot.

**Comment by ariya** [comment]
For clarity (since one is a grammar error and another is an early error), I spawn this into two issues:

 * #1578: IdentifierName should be used for ExportSpecifier
 * #1579: Early error for exported names not part of declared names
