### ISSUE TITLE
Please add this parser to the list of parsers on esprima.org's speed comparison page

### ISSUE THREAD

**Issue by nenionoda** [jquery/esprima#1505]
Hello
please add the [jsRube parser](https://github.com/icefapper/jsRube/blob/master/dist/lube.js) to the list of parsers on [esprima.org's parser speed comparison page](http://esprima.org/test/compare.html).

It:
- always records the location data on every node,
- always records the 'raw' value on tokens that can have values,
- catches as many early errors as it can (actually is going to catch all), and
- has correctly[a] parsed the whole "3rdparty" corpus (in esprima's "test" directory), and
- passes the (non-failure) ".tree.json" and ".module.json" esprima tests, and fails on the fail cases (though without any error message yet), 

so I guess it would be decent enough a parser to have a slot on that venerable list (at least with a 'beta' after it.)

(a) in direct comparison against esprima's parses

**Comment by michaelficarra** [comment]
:+1:

While we're in there, we should add version numbers next to each parser and update them all to the latest version.

**Comment by icefapper** [comment]
Thanks!

**Comment by nenionoda** [comment]
Thanks!
(apologie for first posting with my other, indecent nick.)

**Comment by ariya** [comment]
@nenionoda Once jsRube gets some more adoption, then feel free to create a PR to add it (the site is on the `gh-pages` branch). There are too many parsers out there and we can't include everything.

@michaelficarra Every parser is served from the hosted browser version (often, from CDN). The version number is obtained from the parser itself (if it offers one).

**Comment by michaelficarra** [comment]
@ariya This parser is notable for its performance. In a performance comparison, it would be appropriate to include it.
