### ISSUE TITLE
Return statement containing newline is incorrectly parsed as two statements

### ISSUE THREAD

**Issue by joepie91** [jquery/esprima#1506]
__Version:__ `esprima@2.7.2`

Sample code:

```js
function foo() { return
bar; }
```

Example results with and without a newline between the `ReturnStatement` and the `Identifier`:

```js
> console.log(util.inspect(esprima.parse("function foo() { return\nbar; }").body[0], {colors: true, depth: null}))
{ type: 'FunctionDeclaration',
  id: { type: 'Identifier', name: 'foo' },
  params: [],
  defaults: [],
  body: 
   { type: 'BlockStatement',
     body: 
      [ { type: 'ReturnStatement', argument: null },
        { type: 'ExpressionStatement',
          expression: { type: 'Identifier', name: 'bar' } } ] },
  generator: false,
  expression: false }

> console.log(util.inspect(esprima.parse("function foo() { return bar; }").body[0], {colors: true, depth: null}))
{ type: 'FunctionDeclaration',
  id: { type: 'Identifier', name: 'foo' },
  params: [],
  defaults: [],
  body: 
   { type: 'BlockStatement',
     body: 
      [ { type: 'ReturnStatement',
          argument: { type: 'Identifier', name: 'bar' } } ] },
  generator: false,
  expression: false }
```

This is a case I ran into while deobfuscating in-the-wild JS malware, and while Esprima interpreted it as two *separate* statements, Chrome parses this as a single `ReturnStatement` regardless of whether there's a newline or not. I don't know what the spec says about this, but judging from [this page](http://esprima.org/doc/compatibility.html), it might be desirable to bring Esprima's behaviour in line with that of browsers.

**Comment by mikesherov** [comment]
Thanks for contributing! It is 2 statements due to semicolon insertion. Please see here for proof: https://jsfiddle.net/tywocq5y/

Closing this issue for now, please let me know if you feel this was closed in error.
