### ISSUE TITLE
what should the error be for `function *l() { (yield=12)=>12; } `?

### ISSUE THREAD

**Issue by nenionoda** [jquery/esprima#1507]
Hello
as it currently stands, this results in a 'unexpected =`; i know it's being pedantic, and that it might require extra (and arguably unnecessary) work for it to be implemented, but shouldn't it be 'invalid parameter name: yield' instead?

**Comment by ariya** [comment]
Right now we try to follow V8/Node.js error message (historical reason). With the current design, it's also pretty challenging to provide a more detailed syntax/early error. Follow issue #1214 for any progress on customized/elaborated error message.
