### ISSUE TITLE
Failed to parse regex expression

### ISSUE THREAD

**Issue by jurrinus** [jquery/esprima#1510]
When I parse the following line:
var hackFixForBadEncodingGoalText = c.goal.goalText.replace(/\uFFFD/, '\'');

esprima converts it to:

var hackFixForBadEncodingGoalText = c.goal.goalText.replace([object Object], '\'');

**Comment by ariya** [comment]
Can you share how you got the conversion back?

Note that likely this is not a problem of Esprima. It is the limitation of JavaScript regular expression object which can be (de)serialized properly.

**Comment by ariya** [comment]
Please reopen if this is still an issue.
