### ISSUE TITLE
How to pass wild characters to nodejs esvalidate arguments 

### ISSUE THREAD

**Issue by adityareddyy** [jquery/esprima#1511]
This might be little basic but I am struggling with this. I have a huge javascript project which has thousand of files and I would like to use esvalidate of esprima package to verify the syntax.
I am trying this  
`esvalidate *.js` 
but it says the below error
`Error: ENOENT: no such file or directory, open '<<location>>\*.js'`

**Comment by michaelficarra** [comment]
You mustn't have any `.js` files in your working directory. Your shell is responsible for expanding `*`, not `esvalidate`. When it can't expand it, it will pass the glob as a string, and you don't have a file with that name either.

**Comment by adityareddyy** [comment]
@michaelficarra  The working directory does have `.js` files and pointing esvalidate to a single file is indeed working fine.  I am really not sure where the problem is. Please see the below screenshot which shows the working directory and successful execution on pointing it to a single file.

![image](https://cloud.githubusercontent.com/assets/20510196/17577751/1b0955f4-5f9f-11e6-8867-97729e13dc3f.png)

**Comment by ariya** [comment]
@adityareddyy You are on Windows and its shell does not support wildcard expansion. For some alternative solution, check e.g. http://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths.
In all cases, this is more of a Windows shell usage and not related to Esprima.
