### ISSUE TITLE
Breaks at simple parse

### ISSUE THREAD

**Issue by Delagen** [jquery/esprima#1544]
```
 TypeError: this.source.charCodeAt is not a function
```
```
var parsed = esprima.parse(fs.readFileSync(require.resolve("angular-ui-mask/src/mask")));line no-sync
```

**Comment by michaelficarra** [comment]
Looks like you're not passing a string as the input.

**Comment by ariya** [comment]
Use [readFileSync](https://nodejs.org/api/fs.html#fs_fs_readfilesync_file_options) properly so that it gives a string and not a [Buffer](https://nodejs.org/api/buffer.html). Example (on Node.js REPL):
```
> fs.readFileSync('hello.js')
<Buffer 63 6f 6e 73 6f 6c 65 2e 6c 6f 67 28 22 48 65 6c 6c 6f 2c 20 77 6f 72 6c 64 21 22 29 3b 0a>

> fs.readFileSync('hello.js', 'utf-8')
'console.log("Hello, world!");\n'
```

**Comment by Delagen** [comment]
Strange... before 3.0.0 works, installed version 2.7.3. and it works with Buffer

**Comment by ariya** [comment]
@Delagen That was because of the decision to accept only string as the input (PR #1353).

**Comment by Delagen** [comment]
I think it must be written in Changelog as BREAKING CHANGE

**Comment by ariya** [comment]
@Delagen Agreed. Extensive documentation is in my radar (track #1477).

**Comment by michaelficarra** [comment]
You could make the argument that passing a non-string to esprima before was undefined behaviour. I believe I'm correct in saying that it at least wasn't documented to accept anything other than a string.

**Comment by boris-marinov** [comment]
You could also check your input and tell people what the problem is:
>TypeError: Expected a string, got a String Buffer.
