### ISSUE TITLE
3.0.0: No longer possible to manipulate comments via top 'comments' property?

### ISSUE THREAD

**Issue by papandreou** [jquery/esprima#1546]
It seems like esprima 3.0.0 populates the top level `comments` array with different instances than the `trailingComments`/`leadingComments` that are attached to individual nodes, whereas 2.x used the same instances.

```js
var ast = require('esprima').parse('foo = 123; // bar', {attachComment: true});
console.log('top-level comment', ast.comments[0]);
console.log('trailingComments', ast.body[0].trailingComments[0]);
ast.comments[0].value = 'quux';
console.log('same instance?', ast.body[0].trailingComments[0] === ast.comments[0]);
console.log(require('escodegen').generate(ast, {comment: true}));
```

Output with esprima 2.7.2:

```js
top-level comments { type: 'Line', value: ' bar', range: [ 11, 17 ] }
trailingComments { type: 'Line', value: ' bar', range: [ 11, 17 ] }
same instance? true
foo = 123;    //quux
```

Output with esprima 3.0.0:

```js
top-level comment { type: 'Line', value: ' bar' }
trailingComments { type: 'Line', value: ' bar', range: [ 11, 17 ] }
same instance? false
foo = 123;    // bar
```

Updating `ast.body[0].trailingComments[0].value` instead of `ast.comments[0].value` works with both versions, but I have some code relying on the old behavior, so I wanted to check whether it's an accident before making any changes :). It seems like the top-level comments array loses most of its value because of this.

**Comment by ariya** [comment]
Thanks for the report @papandreou, I'll take a look at it!

**Comment by ariya** [comment]
This is definitely not an accident. It is the intended breaking change to facilitate the modularization of the parser and to move the attachment logic from the core parser (see #1434).

Unfortunately, it does introduce this kind of inconvenience. @papandreou If the new behavior is causing you a hardship, let me know if I can be of any help.

**Comment by papandreou** [comment]
Thanks for getting back to me about this.

I've changed my code so it looks for `leadingComments`/`trailingComments` by traversing the AST instead of going through the top-level `comments` array.

Still, I would consider reinstating the previous behavior or removing the top-level `comments` property. Otherwise I think users will expect to be able to manipulate those comments and serialize the AST.

**Comment by ariya** [comment]
Fair point @papandreou. As the follow-up, we will include AssetGraph as part of our [downstream tests](http://esprima.org/test/ci.html) (for details, track #1554) so that any future breaking changes will be noticed right away. In addition, the comment attachment vs collection issue will be sorted out in the near future (#1553).
