### ISSUE TITLE
Some generic error messages

### ISSUE THREAD

**Issue by sebastienros** [jquery/esprima#1552]
In `messages.ts`, I'd suggest to improve the generic `Unexpected token`:

```
MissingFromClause: 'Unexpected token',
NoAsAfterImportNamespace: 'Unexpected token',
InvalidModuleSpecifier: 'Unexpected token',
IllegalImportDeclaration: 'Unexpected token',
llegalExportDeclaration: 'Unexpected token',
```

_I had created a PR but had not created the issue first._

**Comment by sebastienros** [comment]
c.f. https://github.com/jquery/esprima/issues/1547 for implementation details

**Comment by ariya** [comment]
The messages were left generic because back then V8/Node.js did not have ES6 support. Let's check what V8/Node.js shows when encountering such an error and adopt the same error message.

**Comment by ariya** [comment]
A good reference: https://chromium.googlesource.com/v8/v8/+/master/src/messages.h.

**Comment by ariya** [comment]
Let's just fold this one into #1214.
