### ISSUE TITLE
Esprima.org using an old version?

### ISSUE THREAD

**Issue by sebastienros** [jquery/esprima#1564]
I was testing this expression: http://esprima.org/demo/parse.html?code=var%20x%20%3D%20%2F%5B%5C%5D%2F%5D%2F
But it seems to give a wrong tree, see in `value` it should be `{}` and it's actually a double encoded string version of the pattern.

Is the site up to date with the parser version?

**Comment by ariya** [comment]
It should be using the latest version, running `esprima.version` on the console of that page gives `3.0.0`.

Note that regular expressions are not trivial to serialize/deserialize to/from string. I'm not surprised if there is a problem in the (de)serialization.

**Comment by ariya** [comment]
Running the parser directly in the page gives the following:

![image](https://cloud.githubusercontent.com/assets/7288/18595596/4a3be554-7bfa-11e6-89b3-e21a54b2574d.png)

This seems to be OK. @sebastienros Which property do you think is incorrect?

**Comment by sebastienros** [comment]
I see. So I assume there is an actual issue then. Either the tree should follow the unit test logic and render an empty object, or handle the pattern correctly and not double-encode it.

**Comment by ariya** [comment]
I think it was done in the past and we got complains because `value` of `{}` is confusing to them.
I think the escaping is necessary for the Tree view. I'm not sure what to do there.

**Comment by sebastienros** [comment]
Escaping is necessary, but there is double escaping right now.

`value` should be `[\\]/]` like `regex.pattern`, not `"value": "/[\\]\\/]/"`

**Comment by sebastienros** [comment]
Wait, the issue is somewhere else actualle, the `/` is actually changed to a `\/` which is then encoded in `'\\/`. 

Somehow something is cleaning the regex by changing `/[\]/]/` to `/[\]\/]/` then the encoding kicks in.

**Comment by sebastienros** [comment]
`var r = /[\\]/]/` fails in Chrome with `Uncaught SyntaxError: Unexpected token ]`, not esprima.

**Comment by ariya** [comment]
What do you think of removing the `value` property all together to avoid confusion? There is still `raw` (which is correct, I think. Please double check) as well as the decomposed `pattern` and `flags`.

**Comment by sebastienros** [comment]
Now I can explain the reason, and what is rendered is fine.

In `scanner.ts` the `Regex` object is created from this parsed regex literal `/[\]/]/`. Because Chrome is the host, it understands that the `/` in the range marker is not the RegExp termination be should have been escaped, so it escapes it by itself. Then when the `value` is rendered in JSON, it will be render it based on the pattern of the `RegExp` object, hence the discrepancy between the raw value and the one from the object.

I think this is not a wrong behavior from Chrome, and definitely not an issue with esprima.org or the parser.

I have another question though. I have been through all the unit tests for the regular expressions and I can't explain why some of the trees have `value: {}` and some others `value: null` where the RegExp are valid. Are you actually running these tests? Also some trees don't have `loc` properties, are you just ignoring these when testing?

**Comment by ariya** [comment]
@sebastienros I'm not sure about the unit tests. Perhaps open a new issue or post to the mailing-list?
