### ISSUE TITLE
AssignmentPattern contains a non-standard "operator" property

### ISSUE THREAD

**Issue by mroch** [jquery/esprima#1575]
as far as I can tell, [AssignmentPattern](https://github.com/estree/estree/blob/master/es2015.md#assignmentpattern) should not have an "operator" property, but esprima (as of 3.0.0, at least) has one.

```
(x=1) => x * x
```

```
          {
            "type": "AssignmentPattern",
            "operator": "=",
            "left": ...,
            "right": ...,
            "range": [
              1,
              4
            ],
            "loc": {
              "start": {
                "line": 1,
                "column": 1
              },
              "end": {
                "line": 1,
                "column": 4
              }
            }
          }
```

**Comment by sebastienros** [comment]
I concur, in my unit tests I had to explicitly comment them. The solution is to `delete` the property when the `AssignmentExpression` is morphed to an `AssignmentPattern`, in the `reinterpretExpressionAsPattern` function. Then change all trees to remove the property.

**Comment by ariya** [comment]
Good catch, thank you @mroch!

In the style of our [test case-actual-expected](https://github.com/jquery/esprima/wiki/Filing-a-Defect):

Test case:
```javascript
esprima.parse('(x=y) => z').body[0].expression.params[0];
```

Actual:
```
{ type: 'AssignmentPattern',
  operator: '=',
  left: Identifier { type: 'Identifier', name: 'x' },
  right: Identifier { type: 'Identifier', name: 'y' } }
```

Expected:
```
{ type: 'AssignmentPattern',
  left: Identifier { type: 'Identifier', name: 'x' },
  right: Identifier { type: 'Identifier', name: 'y' } }
```
