### ISSUE TITLE
[API] Explicitly distinguish parsing a module vs a script

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1576]
Since ES2015, a program can be a module or a script. To correctly parse the source input, the `sourceType` option needs to be specified (when omitted, it is assumed to be `script`). This is illustrated in the following example:

```javascript
// parsing a script
esprima.parse('x = 2', { sourceType: 'script' });

// parsing a module
esprima.parse('export const y = 3', { sourceType: 'module' });
```

To encourage the consumer to identify the source input, two new functions shall be introduced, `parseScript` and `parseModule`. The previous code fragment is then equivalent to the following:
```javascript
// parsing a script
esprima.parseScript('x = 2');

// parsing a module
esprima.parseModule('export const y = 3');
```

At the same time, `parse` should be deprecated. It will be still available in the near future for backward compatibility but the use of it should be highly discouraged.

References:
* Shift Parser: http://shift-ast.org/parser.html
* Common misunderstanding: Esprima doesn't understand export/import #1273 #1336
* Original pull request for `sourceType`: #290

--

**Comment by johanssj** [comment]
This is a good idea.

btw. What is the connection between Esprima & Shift parser (if any)?

**Comment by ariya** [comment]
Shift uses a slightly different AST format (see [the rationales](http://engineering.shapesecurity.com/2015/01/a-technical-comparison-of-shift-and.html)).
