### ISSUE TITLE
Object Rest/Spread Properties

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1588]
New productions:
```
PropertyDefinition[Yield] ::
  ...  AssignmentExpression[In, ?Yield]

ObjectAssignmentPattern[Yield] ::
  {AssignmentRestProperty[?Yield]opt}
  {AssignmentPropertyList[?Yield]  ,  AssignmentRestProperty[?Yield]opt}

AssignmentRestProperty[Yield] ::
  ...  DestructuringAssignmentTarget[?Yield]

ObjectBindingPattern[Yield] ::
  {BindingRestProperty[?Yield]opt}
  {BindingPropertyList[?Yield]  ,  BindingRestProperty[?Yield]opt}

BindingRestProperty[Yield] ::
  ...  BindingIdentifier[?Yield]
  ...  BindingPattern[?Yield]
```

AST changes:
```js
extend interface ObjectPattern {
    properties: [ AssignmentProperty | RestElement ];
}

extend interface ObjectExpression {
    properties: [ Property | SpreadElement ];
}
```

References:
- The proposal: http://sebmarkbage.github.io/ecmascript-rest-spread/
- Change to the spec: ?
- ESTree for ES2017: https://github.com/estree/estree/blob/master/es2017.md

**Comment by hzoo** [comment]
ESTree for rest/spread: https://github.com/estree/estree/blob/master/experimental/rest-spread-properties.md

**Comment by hzoo** [comment]
And it's stage-3 right now (not in es2017)

**Comment by ariya** [comment]
**Originally**, the AST changes involved the addition of two new nodes _RestProperty_ and _SpreadProperty_:

```js
interface RestProperty <: Node {
    type: "RestProperty";
    argument: Expression;
}

interface SpreadProperty <: Node {
    type: "SpreadProperty";
    argument: Expression;
}
```

and the modifications to _ObjectPattern_ and _ObjectExpression_:
```js
extend interface ObjectPattern {
    properties: [ AssignmentProperty | RestProperty ];
}

extend interface ObjectExpression {
    properties: [ Property | SpreadProperty ];
}
```

However, based on the discussion in https://github.com/estree/estree/issues/145, the consensus is that the AST change will be **simplified** to the reuse of the existing _RestElement_ and _SpreadElement_ and thus the modifications to _ObjectPattern_ and _ObjectExpression_ are also simplified to:
```js
extend interface ObjectPattern {
    properties: [ AssignmentProperty | RestElement ];
}

extend interface ObjectExpression {
    properties: [ Property | SpreadElement ];
}
```

**Comment by ariya** [comment]
As of March 2017, it's in Stage 3 (https://github.com/tc39/proposals).

**Comment by concubicycle** [comment]
Is this currently working?

**Comment by ariya** [comment]
> Is this currently working?

If you use the master branch. Otherwise, keep an eye on https://github.com/jquery/esprima/projects/2.

**Comment by idevelop** [comment]
Hey @ariya, is version 5.0 scheduled for a release date?

**Comment by LeoEatle** [comment]
When will 5.0 release?

**Comment by danielo515** [comment]
Eslint does support this, and eslint uses (by default) esprima. How are they doing this?

**Comment by asapach** [comment]
ESLint uses Espree: https://github.com/eslint/espree

**Comment by danielo515** [comment]
Oh, a misread from hours of not sleeping. Thanks!

**Comment by christiantjl** [comment]
Three years later, still can't parse a spread operator?

**Comment by mreinstein** [comment]
There aren't any javascript runtimes that support es module syntax but lack the spread operator. At the very least I would expect `esprima.parseModule` to support all of the es6-isms. 

Also, I'm not sure why this issue has been closed when it's not available in any releases. Isn't this kind of indirectly sweeping the problem under the rug?

**Comment by VityaSchel** [comment]
How do I replace it? I tried replacing `...` with `{}.apply()` — `Unexpected identifier {`, with `new Object().apply()` — `Unexpected identifier`, with fake object which does not exist in code: `object.apply()` — `Unexpected identifier .`. None of these work. Is there any workaround?

**Comment by ctjlewis** [comment]
This issue should not be closed.

**Comment by LeoEatle** [comment]
I publish a master version of esprima: https://www.npmjs.com/package/esprima-master
But I still suggest to use Babel or Eslint as parser. I have finished this in my project.

**Comment by 0xCAFEF00D** [comment]
I was getting the same error in the latest version (4.0.1) when using the spread syntax in objects. I patched the first line of Parser.prototype.parseObjectProperty with the following which solved the problem and generated the expected output:

```
Parser.prototype.parseObjectProperty = function (hasProto) {
  // PATCH 
  if (this.lookahead.value === '...') 
    return this.parseSpreadElement();
```

**Comment by 0x00C5** [comment]
There's a solution here https://github.com/jquery/esprima/issues/2034#issuecomment-818542469

**Comment by sophiawisdom** [comment]
Six years and no support for spread operator.

**Comment by VityaSchel** [comment]
> Six years and no support for spread operator.

use babel
