### ISSUE TITLE
\uD83B\uDE00 is an 'IDStart', or is it?

### ISSUE THREAD

**Issue by icefapper** [jquery/esprima#1590]
Hello
U+1EE00 is an id start, if I've not been mistaken; but 
https://github.com/jquery/esprima/blob/master/test/fixtures/ES6/identifier/invalid_escaped_surrogate_pairs.js fails. Looks like it is not just esprima though, as chrome is also failing to parse `var \uD83B\uDE00`.

I'm not sure whether it's me missing something, but I would be glad to know. Thanks!

**Comment by mathiasbynens** [comment]
`ID_Start` code points represented as a surrogate pair are not valid identifiers. `var \u{1EE00}` and `var 𞸀` are valid indeed, but `var \uD83B\uDE00` isn’t.

See:

- [Valid JavaScript variable names in ECMAScript 6](https://mathiasbynens.be/notes/javascript-identifiers-es6)
- [Valid JavaScript variable name validator](https://mothereff.in/js-variables#%F0%9E%B8%80)

**Comment by icefapper** [comment]
I had no idea that was the case; now I know what `UnicodeEscapeSequence` stands for in the spec -- Thanks a lot @mathiasbynens for the clarification!
