### ISSUE TITLE
export MyObject from "./MyObject" fails

### ISSUE THREAD

**Issue by derekdreery** [jquery/esprima#1592]
I believe that the following is valid ecmascript code, but esprima fails to parse it:

```javascript
export MyObject from "./MyObject"
```

**Comment by derekdreery** [comment]
It is semantically equivalent to

```javascript
export { default as MyObject } from "./MyObject"
```

**Comment by mikesherov** [comment]
Thanks for the report! You need to use the "sourceType: module" flag when attempting to parse a module, as Esprima's default parse mode is script. Closing this issue for now, as we have tests confirming this case works in Esprima 3. Thanks again!

**Comment by derekdreery** [comment]
Hi Mike

What is the test called - I couldn't find it.

Thanks

**Comment by ariya** [comment]
@derekdreery It's explained in the documentation: http://esprima.org/doc/index.html (look for `export`).

**Comment by ariya** [comment]
@derekdreery Do you recall which production is supposed to match the case `export x from "x"`?

**Comment by ariya** [comment]
If we look at https://tc39.github.io/ecma262/#sec-exports, the only productions which have FromClause are:
```
ExportDeclaration :: export  *  FromClause;
ExportDeclaration :: export  ExportClause  FromClause;
```
But then, in the second production, ExportClause is always enclosed with `{` and `}`.

Thus, I don't see an ExportDeclaration production that can match `export x from "x"`.

**Comment by mikesherov** [comment]
Sorry, I misread the issue!

Mike Sherov

**Comment by derekdreery** [comment]
The spec does not allow the syntax `export x from y` - I'll raise this issue with the transpiler I use.

Thanks for clarifying
