### ISSUE TITLE
Test fixtures: simplify module parsing

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1593]
Currently, the set of test fixtures (under `test/fixtures`) is not easy to be expanded with additional test cases for module parsing (i.e. `sourceType` of `module`).

The proposed step to fix it is rather easy: indicate `sourceType` by the file name, e.g. `foo.module.js` is treated as a module (instead of a script). This is both used for creating a new test fixture (if the baseline does not exist yet) or to evaluate an existing test case.

**Comment by michaelficarra** [comment]
Instead of looking for ways to improve the esprima silo of tests, it would be a much more prudent use of your time to integrate with [tc39/test262-parser-tests](https://github.com/tc39/test262-parser-tests).

**Comment by ariya** [comment]
@michaelficarra They are not mutually exclusive. Those tests do not verify the AST output, various parsing options, node locations, etc.

**Comment by ariya** [comment]
A notable side effect: there is no need to specialize `module` in the test result, e.g. baseline result such as `foo.module.json` is gone completely since it will be replaced with either `foo.module.tree.json` for a successful parsing or `foo.module.failure.json` for an unsuccessful one.
