### ISSUE TITLE
Invalid left-hand side in assignment: export default a = b + c

### ISSUE THREAD

**Issue by Jianru-Lin** [jquery/esprima#1596]
esprima refuses:

```
export default a = b + c
```

and reports:

```
Error: Line 1: Invalid left-hand side in assignment
```

but it accepts:

```
export default (a = b + c)
```

and it accepts this without any brace:

```
export default a + b
```

I'm just wondering is this a bug? Or I misunderstood it?

I reviewed the [ECMA-262 2016](ecma-international.org/publications/standards/Ecma-262.htm)，I saw:

```
ExportDeclaration:
	export * FromClause;
	export ExportClause FromClause;
	export ExportClause;
	export VariableStatement
	export Declaration
	export default HoistableDeclaration[Default]
	export default ClassDeclaration[Default]
	export default [lookahead ∉ { function, class }] AssignmentExpression[In];
```

So I guess esprima should accept this too:

```
export default a = b + c
```

Thanks.

**Comment by ariya** [comment]
Thanks for the report! Looks like you find a defect in Esprima.
