### ISSUE TITLE
Add a default .gitattributes for LF setting

### ISSUE THREAD

**Issue by sebastienros** [jquery/esprima#1604]
It's hard to run the build scripts on windows as it's converting LF to CRLF in most git environments. The solution is either to set the default `.gitattributes` option globally or on the repository.

Appveyor has an option for this so I assume this is how it works OOB.

Repro:
- Clone the repository from a windows environment which is setup with `autocrlf`
- Run `npm install` then `npm run appveyor`

Result:
- Many tests fail because of wrong ranges (2 bytes instead of 1 when parsing EOL)

NB:
Does it actually make sense to have the `index` of location increased by two because of CRLF?

**Comment by ariya** [comment]
Let's have `.gitattributes` in the repo and see how it goes.

For the CRLF, I believe the current behavior is still correct. There was a long discussion last time: https://github.com/jquery/esprima/pull/1091#issuecomment-78201357.

**Comment by michaelficarra** [comment]
@ariya This issue is different because it is not about line/column but byte offset. The current behaviour of treating CRLF as a single line is still correct. But if we're making assertions about the byte offset, the test files will have to remain byte for byte exactly as-is, so I think this file is necessary if Windows is to be supported as a dev environment. :+1:

**Comment by sebastienros** [comment]
I will submit a PR then.

**Comment by ariya** [comment]
@michaelficarra Good explanation, thank you.
@sebastienros Please do!

**Comment by sebastienros** [comment]
I could configure it without changing the .gitattributes file:

```
git config core.eol lf
```

Then to reset all the local file with `LF` I ran

```
git rm -rf --cached .
git reset --hard HEAD
```

I think we can close this issue. The next thing to do might be to document it.

**Comment by ariya** [comment]
I think we still need a check to verify that a test file (contained CRLF) has the expected content, byte by byte. This check needs to be the first step in `npm test` before running everything else. If the check fails (e.g. on Windows with `autocrlf`), then it blocks the rest of the extensive unit tests.

**Comment by ariya** [comment]
I verified that this is working as expected with the latest master branch (commit 26833ed).

I was using a fresh install (all via Chocolatey) of Git version 2.11.0.windows.1, Node.js v7.2.1 with npm 3.10.10. Running in PowerShell:
```
git clone https://github.com/jquery/esprima.git
cd esprima
npm install
npm run appveyor
```

All steps are completed without any error.

**Comment by ariya** [comment]
Ugh, `.gitattributes` is causing unintentional content change, see #1672.

**Comment by ariya** [comment]
(I reverted the addition of `.gitattributes`).

To summarize: when cloning this repository on Windows, it is still important to use the right line-ending (i.e. via `git config core.eol lf`). Failing to do so will cause `npm test` to stop prematurely due to the above added check.
