### ISSUE TITLE
It's missing "Unexpected token ILLEGAL" exception for 'g', 'G', 'h' and 'H' tokens inside hexadecimal digits

### ISSUE THREAD

**Issue by nicematt** [jquery/esprima#1605]
```javascript
"\u00FG" // No error
```

```javascript
"\xFG" // No error
```

```javascript
0xFG // No error
```

My browser currently throws an "Invalid Unicode escape sequence" / "Invalid or unexpected token" exception for each of these tests above, while Esprima considers it valid. Tested at http://esprima.org/demo/parse.html.

**Comment by nicematt** [comment]
Okay, I'll have to edit exports.Character.isHexDigit return's expressions.

```javascript
exports.Character = {
    isHexDigit: function (cp) {
        return (cp >= 0x30 && cp <= 0x39) ||
            (cp >= 0x41 && cp <= 0x48) ||
            (cp >= 0x61 && cp <= 0x68); // a..h
    }
};
```

**Comment by michaelficarra** [comment]
> Are 'g' and 'h' digits really valid in hexadecimal values?

Haha, no. This is a pretty funny mistake.

**Comment by ariya** [comment]
Good catch, thank you!
The simplest test case for completeness:
```js
esprima.tokenize('0xG')
```
Expected: a thrown exception.
Actual:
```js
[ { type: 'Numeric', value: '0xG' } ]
```
