### ISSUE TITLE
Please update online parser/examples/demos to 4.0

### ISSUE THREAD

**Issue by kristianmandrup** [jquery/esprima#1610]
Was playing with the parser using async/await. Found not to be working, but after investigation notices it has recently been merged into master. Looking forward to 4.0 release, new docs and updated demos :)

**Comment by ariya** [comment]
The website will be updated once 4.0 is officially released (always the case, see the [Release Preparation](https://github.com/jquery/esprima/wiki/Release-Preparation). Thank you for your patience!
