### ISSUE TITLE
No exception for keywords with escaped characters

### ISSUE THREAD

**Issue by hydroper** [jquery/esprima#1612]
**Test input**

```javascript
\u{74}rue
```

**Expected:** an error.

**Actual:** produces a valid AST.

**Comment by ariya** [comment]
Relevant part in the specification: https://tc39.github.io/ecma262/#sec-reserved-words

> The _ReservedWord_ definitions are specified as literal sequences of specific _SourceCharacter_ elements. A code point in a _ReservedWord_ cannot be expressed by a `\` _UnicodeEscapeSequence_.
