### ISSUE TITLE
Docs suggested output VS real output

### ISSUE THREAD

**Issue by pecastro** [jquery/esprima#1617]
Docs say this http://esprima.org/doc/index.html#ast and produce a wonderful parse tree.
Similar code on cfd8eba produces different results ?
`[pecastro@localhost esprima]$ node
> var esprima = require('./dist/esprima');
undefined
> var p2 = 'answer0 = 42;'
undefined
> esprima.parse(p2, { sourceType: 'script' })
{ type: 'Program',
  body:
   [ { type: 'ExpressionStatement',
       expression: [Object] } ],
  sourceType: 'script' }
> esprima.parse(p2)
{ type: 'Program',
  body:
   [ { type: 'ExpressionStatement',
       expression: [Object] } ],
  sourceType: 'script' }
> [pecastro@localhost esprima]$ node --version
v0.10.42
`

**Comment by michaelficarra** [comment]
What is supposedly wrong with that result? Also, you should upgrade to a supported version of node.

**Comment by ariya** [comment]
@pecastro I assume you are comparing the output, where Node.js REPL produces a different representation. This has nothing to do with Esprima, it's just the way Node.js REPL displays an object.

Try this:
```js
> a = { b: { c: { d: { e: 0 } } } }
{ b: { c: { d: [Object] } } }
```

Compare with the result of using `JSON.stringify`:
```js
> console.log(JSON.stringify(a, null, 2));
{
  "b": {
    "c": {
      "d": {
        "e": 0
      }
    }
  }
}
```
The documentation (http://esprima.org/doc/index.html#ast) mentions this already: "...which shows the syntax tree (formatted with JSON.stringify)".

Here is a complete example:
```js
> console.log(JSON.stringify(esprima.parse('answer0 = 42;'), null, 2))
{
  "type": "Program",
  "body": [
    {
      "type": "ExpressionStatement",
      "expression": {
        "type": "AssignmentExpression",
        "operator": "=",
        "left": {
          "type": "Identifier",
          "name": "answer0"
        },
        "right": {
          "type": "Literal",
          "value": 42,
          "raw": "42"
        }
      }
    }
  ],
  "sourceType": "script"
}
```

**Comment by pecastro** [comment]
Ups, I guess I jumped the gun a bit too soon. Apologies for the confusion and thanks @ariya for pointing in the right direction.
