### ISSUE TITLE
Incorrectly accepts \x{0} in string/template literals

### ISSUE THREAD

**Issue by bakkot** [jquery/esprima#1619]
```js
'\x{0}'
```

is not a program; nor is

```js
`\x{0}`
```

----

Fix is to move [this if clause](https://github.com/jquery/esprima/blob/d044f5b5b708451fb24405493777997be887f46e/src/scanner.ts#L824-L827) and [this if clause](https://github.com/jquery/esprima/blob/d044f5b5b708451fb24405493777997be887f46e/src/scanner.ts#L943-L946) into the respective `'u'` cases, I believe.

**Comment by ariya** [comment]
Relevant lexical grammar productions on [string literals](https://tc39.github.io/ecma262/#sec-literals-string-literals):

```
HexEscapeSequence  ::
  x  HexDigitHexDigit

UnicodeEscapeSequence  ::
  u  Hex4Digits
  u  {HexDigits}
```

<hr>

Following [V8 error messages](https://chromium.googlesource.com/v8/v8/+/master/src/messages.h), the exception should _"Invalid hexadecimal escape sequence"_.
