### ISSUE TITLE
Parsing functions without parenthesis fails

### ISSUE THREAD

**Issue by yesman85** [jquery/esprima#1627]
When parsing this function:
`function (m) { return m.test === true; }`

I get the following exception:
`Uncaught Error: Line 1: Unexpected token (`

But when I put it around parenthesis
`(function (m) { return m.test === true; })`

it works fine.

**Comment by ariya** [comment]
This is the correct behavior and it has nothing to do with Esprima. The first example is an invalid function declaration because it does not have a name. The second one is a function expression, and it's valid as is. For more details, please explore e.g. http://kangax.github.io/nfe/.

**Comment by yesman85** [comment]
Ok yeah I figured as much, I recall having similar issues putting functions in an eval with similar results.
