### ISSUE TITLE
[ESTree] UpdateExpression vs UnaryExpression

### ISSUE THREAD

**Issue by crazyhuggins** [jquery/esprima#1630]
Parsing this: `x ** ++y` and I noticed that in the `ESTree` you got a UpdateExpression. 

According to the specs the UpdateExpression is the group, but sub expressions are `UnaryExpression`.

http://www.ecma-international.org/ecma-262/7.0/#sec-12.4

If you parse the same with `Acorn`, you get correct result.

**Comment by ariya** [comment]
Thanks for the report @crazyhuggins.

I'm not following the problem. The source text `x ** ++y` will be parsed into the following syntax tree (after `JSON.stringify`):

```json
{
    "type": "Program",
    "body": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "BinaryExpression",
                "operator": "**",
                "left": {
                    "type": "Identifier",
                    "name": "x"
                },
                "right": {
                    "type": "UpdateExpression",
                    "operator": "++",
                    "argument": {
                        "type": "Identifier",
                        "name": "y"
                    },
                    "prefix": true
                }
            }
        }
    ],
    "sourceType": "script"
}
```
This seems to be correct.

**Comment by ariya** [comment]
Ping  @crazyhuggins.

**Comment by ariya** [comment]
I think it is a misunderstanding. The fact that the specification describes a production such as `UpdateExpression  :   ++ UnaryExpression` does not mean that we need to create something like an UnaryExpression node.
