### ISSUE TITLE
[ES2017] possible spec violation

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1633]
@ariya  If you are using the 'strict directive' in a function with non-simple parameter list, I would expect it to throw. But it got parsed

```js
function foo(a=2) { 'use strict'; }
```

And also if you use  'use strict' directive in function with non-simple parameter list
```js
(a=2) => { 'use strict'; }
```

Here are a few other combos that should fail after the specs
```js

//| "Illegal 'use strict' directive in function with non-simple parameter list
function foo({a}) { 'use strict'; }
//| use strict' directive in function with non-simple parameter list
({a}) => { 'use strict'; }
//| "Illegal 'use strict' directive in function with non-simple parameter list
function foo(a) { 'use strict'; }
```

I also would have expected this one to fail:

```js
'use strict'; if(x) function f() {}
```

**Comment by ariya** [comment]
Thanks for the report @nowindowsowrking!

**Comment by ariya** [comment]
The last case was spawn to a more elaborated issue (see 1657).

**Comment by ariya** [comment]
The first case spawn to a more elaborated issue (see 1677).
