### ISSUE TITLE
Calls to super must be in the class constructor

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1637]
@ariya If the super property doesn't have a contructor, it should throw an syntax error. There are many examples on this if you are looking into the specs.

All this should fail:

```js
class A {
    foo() {
        super()  // Invalid 'super()'.
    }
}

class A {
    static foo() {
        super()  // Invalid 'super()'.
    }

    static prototype() {  // Invalid method.
    }
}

function foo() {
    super()  // Invalid `super`.
    super.foo()  // Invalid `super`.
}
var foo = function() {
    super()  // Invalid `super`.
    super.foo()  // Invalid `super`.
}

function wrap() {
    function foo(a = super(), b = super.foo()) {  // Invalid 'super'.
    }
}
```

Reference: http://www.ecma-international.org/ecma-262/6.0/#sec-class-definitions-static-semantics-early-errors

**Comment by ariya** [comment]
Thanks for the report @nowindowsowrking!

**Comment by hzlmn** [comment]
Hi @ariya, is this fixed? I would like to look into it, if not.

**Comment by ariya** [comment]
@hzlmn Not fixed yet, feel free to give it a try.
