### ISSUE TITLE
ES2017: More syntax and early errors for async/await

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1638]
@ariya 

```js

//| can use 'yield' identifier outside generators.
async yield => 1
//| should handle export - throws  "Unexpected token function"
export async function foo() { }

//| should handle export default - throws  "Unexpected token"
export default async function() { }

//| cannot combine with generators - throws  "Unexpected token"
async function* foo() { }
```

And this should throw syntax error, but does not
```js
//| syntax error if `=>` didn't exist.
async ({a = b})

//| - cannot use 'await' inside async functions.
(async function foo() { return {await} })

//| cannot use 'await' inside async functions.
async await => 1

//| cannot use 'await' inside async functions.
async (await) => 1
//| cannot use 'await' inside async functions.
async ({await}) => 1
//| cannot use 'await' inside async functions.
async await => 1

//| cannot use 'await' inside async functions.
async ({a: await}) => 1
//| cannot use 'await' inside async functions.
async ([await]) => 1

```

There are loads of other similar combinations, but this one is what I had time to find for now.

**Comment by nowindowsowrking** [comment]
The await keyword is a reserved word, and should throw if `{sourceType: 'module'}`. But it throws for both SourceTypes.

**Comment by ariya** [comment]
Thanks for the report @nowindowsowrking! The coverage of early error is not complete yet, as acknowledged in the implementation (PR #1597).

**Comment by ariya** [comment]
@nowindowsowrking  For clarity, I may need to edit some of the descriptions to follow our guide on [Filing a Defect](https://github.com/jquery/esprima/wiki/Filing-a-Defect) (feel free also to adjust the report yourself).
