### ISSUE TITLE
Unicode symbol issues

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1641]
@ariya My guess is that Esprima is suppose to support ECMA 5 to latest version? And not only ES6 and newer?
If so, you have a issue to handle...  Before I explain it, I will paste in a example:

```js
//|  Valid in ES5, but not in ES6+
var ⸯ; // U+2E2F (*vertial tlde*)
var \u2E2F; // U+2E2F (*vertial tlde*)

//|  Valid in ES6+, but not in ES5
var 𐊧; // U+102A7 (*carian letter a2*)
var \u{102A7}; // U+102A7 (*carian letter a2*)

``` 

I tried this on the online parser, and only the ES6 is accepted else it throws. Issue is that in ES5 identifiers (*astral symbols*) are disallowed, even when represented as an escaped surrogate pair 

In ES6+ this has now been changed and this values are now only accepted if they are presented as a raw symbol or using a single \u{…} escape sequence.

The ES5 specs allowed this things and much more, but not allowed in ES6 anymore. E.g. ES5 allows Unicode 3.x but ES6 lists only Unicode 5.1.x as valid.

So for this to work with ES5 and avoid the parser to throw an invalid syntax, it has to be found a workaround. I noticed this when I was reading through the source code, because Esprima started out with ES5 support, but now provide various ES5 conflicts forcing the online parser to throw syntax error.

**Comment by ariya** [comment]
Because of the inherent complexity, it is not the objective of the project to support multiple language versions. As such, every Esprima version is intended to support **only** one particular edition of [ECMA-262 standard](https://www.ecma-international.org/publications/standards/Ecma-262.htm). For the current stable version (3.x), that means its 7th edition (=ES2016).

**Comment by nowindowsowrking** [comment]
I guess you mean different dialects of the same language? I agree in this and for me it's not a huge issue.  There exist workarounds. But maybe inform the end-user about the matter? Example if one is stupid enough to drop a entire module written with ES5 into the parser, and got a lot of errors. Easy enough to open a bunch of issue tickets.
But yes it make sense to use latest Ecma version that is now standardized.

**Comment by mathiasbynens** [comment]
@nowindowsowrking Source for these examples: https://mathiasbynens.be/notes/javascript-identifiers-es6

**Comment by ariya** [comment]
@nowindowsowrking The README and the website both mention only "ECMA-262 7th Edition", no reference to ES5 whatsoever. One day once we have the time to write a detailed documentation, then it can be mentioned explicitly that no other editions are supported.
