### ISSUE TITLE
Can't parse spread operator correctly

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1644]
This one get parsed and shouldn't according to  https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator

```js
var obj = {"key1":"value1"};
var array = [...obj]; // Regarding MDN this should throw because obj is not iterable
```

And for objects, this doesn't work..
```js
     var cleanField = {
          ...field, // this line throws
          config: {...field.config}
        };
```
For Array this works
```js
        var stuff = [...field];
```

And should rest params to be allowed in setter? I expect Esprima to throw

```js
class x {
    set foo(...rest){}  
}

var x = {
    set foo(...rest){}  
}
```

Reference: http://www.ecma-international.org/ecma-262/7.0/#sec-method-definitions

- set PropertyName[?Yield] ( PropertySetParameterList ) { FunctionBody }
- PropertySetParameterList : FormalParameter
- FormalParameter does not include FunctionRestParameter.

**Comment by ariya** [comment]
Thanks for the report @nowindowsowrking!

To avoid confusion ("works", "doesn't work", etc are ambiguous), please state for each case:

* what is the actual output?
* what is the expected output according to the specification?

**Comment by nowindowsowrking** [comment]
@ariya In the rest params cases this should all throw. Esprima is the only parser that does not throw on this. In acorn you get this error message: `Setter cannot use rest params (2:12)`

**Comment by ariya** [comment]
@nowindowsowrking Can you then please revise the description to follow the model (test case, actual, expected) per our [Defect filing guide](https://github.com/jquery/esprima/wiki/Filing-a-Defect)?

**Comment by ariya** [comment]
This is spawn to a more elaborated test case, see 1693.
