### ISSUE TITLE
export edge case issue - module

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1646]
This should throw an error because exporting * requires from and a module name, such as:

`export * from "foo"`

But it get parsed correctly

**Comment by ariya** [comment]
Eh, that line is syntactically valid. Which grammar production did it violate?

**Comment by nowindowsowrking** [comment]
eh. I see you are correct. My flu took me. It was the old Esprima version it  throws in. I close this.

**Comment by ariya** [comment]
Thanks for the clarification @nowindowsowrking.
