### ISSUE TITLE
Async method with non-identifier name as a class element

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1649]
This is similar to #1626 but applying to class instead of object.

Test input:
```
class X { async "f"(){} }
class X { async 1(){} }
class X { async ["f"](){} }
```

Expected: each line produces a valid AST.
Actual: each line triggers an error.

**Comment by ariya** [comment]
@JosephPecoraro You might want to keep an eye on this, too.

**Comment by JosephPecoraro** [comment]
Thanks, I will!
