### ISSUE TITLE
Esprima.org demo inconsistent with esprima module

### ISSUE THREAD

**Issue by CMatias** [jquery/esprima#1656]
Values of property keys are inconsistent when using Unicode characters as JSON keys.

Using the following piece of code on esprima.org `var a = {"\u2028": "u2028"};`

We get the following output on the property key:

```
"key": {
   "type": "Literal",
    "value": " ",
    "raw": "\"\\u2028\""
}
```

However, if we install esprima via npm and run the following:

```
var esprima = require('esprima');

var ast = esprima.parse('var a = {"\\u2028": "u2028"};', {sourceType: 'script'});

console.log(JSON.stringify(ast, null, 2));
```

We get the following output on the property key:

```
"key": {
  "type": "Literal",
   "value": "  ",
   "raw": "\"\\u2028\""
},
```

**Comment by ariya** [comment]
I believe this is only browser display issue, nothing to do with Esprima parsing itself.
Open this example in a web browser:

  https://jsfiddle.net/ss20LyoL/

and it will pop-up the alert dialog twice, first with `1` (of `key.value.length`) and then `82321` (of `key.value.charCodeAt(0)`). That means, despite it looks empty, the `value` property of the `key` is actually a string of one character, as expected.

**Comment by CMatias** [comment]
@ariya Agreed. I thought it would be useful to raise some awareness to it since I (and probably other people) sometimes resort to the online demo feature to do some quick testing, and testing this case lead me to believe that the string should be empty and that somehow my code was doing something wrong.

**Comment by ariya** [comment]
@CMatias Do you have any suggestion? In this case, we're pretty much at the mercy of the browser (on how it displays characters).

**Comment by CMatias** [comment]
@ariya Other than a disclaimer somewhere the only thing would be to replace characters which the browser is unable to display with something. The last suggestion is kind of a pain UX wise so either than a note somewhere there's nothing which can be done.

**Comment by ariya** [comment]
@CMatias Do you want to give a shot and create a pull request? The web site is just GitHub pages, see e.g. https://github.com/jquery/esprima/blob/gh-pages/demo/parse.html.

**Comment by CMatias** [comment]
@ariya Would you opt for the disclaimer? I can do it, no problem. In the meantime feel free to close this.

**Comment by ariya** [comment]
@CMatias Sure thing, just recommend a suitable disclaimer (in a pull request).
