### ISSUE TITLE
parses non valid regular expression

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1662]
@ariya I noticed the parser accept non valid regular expressions. Expected is that the parser should throw a syntax error.

One example:
```js
/[a-z]  /u
```
`LF` and other special chars are also accepted.

It also accepts this regular expressions. I guess you see what is wrong?

```js
/[a-z]/ii

/[a-z]/uu

/[a-z]/mm

/[a-z]/iiiiiiiiiiii
```

**Comment by mathiasbynens** [comment]
What makes you say `/[a-z]  /u` is invalid?

**Comment by nowindowsowrking** [comment]
Well. If you see that regular expression as one, it is not invalid, but a regular expresson is a string value without whitespace. So actually this can also be seen as two regular expression (*due to whitespace*) and then both of them will throw `Error: Line 1: Invalid regular expression: missing /` 

In this case maybe an idea just to you strip out the whitespace, and then validate the regular expression.

**Comment by ariya** [comment]
I'm afraid that this is beyond the scope. According to the specification:

> A regular expression literal is an input element that is converted to a RegExp object (see 21.2) each time the literal is evaluated.

Esprima only tokenizes the regular expression literal. It does not verify whether the constructed RegExp is correct or not (that happens at run-time, in the JavaScript engine). 

(And as @mathiasbynens pointed out, `/[a-z]  /u` is a legitimate regular expression)
