### ISSUE TITLE
Add `illegal continue statement` and `illegal break statement` errors to tolerate mode.

### ISSUE THREAD

**Issue by sanex3339** [jquery/esprima#1668]
In my project a have AST tree.

I want to modify `IfStatement` nodes like described here:
https://github.com/obfuscator-llvm/obfuscator/wiki/Control-Flow-Flattening#implemented-technique

On `IfStatement` nodes, i make some transformations:
1) I extract all `alternate` and `consequence` nodes;
2) convert them to code; 
3) add this code to sting template with switch case code;
4) generate AST tree from result code;
5) return this AST tree instead original `IfStatementNode`.

With this structure i getting errors on `4` stage: `illegal return statement`, `illegal continue statement` when `alternate` and `consequence` statements have `return`, `continue` and `break` statements. 
I understand why this errors happens, but i want to disable them, so i enable `tolerant` option. But this option doesn't affect on `continue` and `break` statement errors.

**Comment by ariya** [comment]
@sanex3339 Please give an illustration of the input that you would like to have it handled. See https://github.com/jquery/esprima/wiki/Filing-a-Defect for more details.

**Comment by sanex3339** [comment]
Right now i abandon the method described above and will try to do such kind of things with raw node objects. If i'll have a need to use this method again i reopen this issue.

**Comment by armaanshah96** [comment]
Hello,

I am running into a similar problem. I am attempting to inject an if-statement after a for loop that breaks out of the loop when a specific variable is set to true.

`esprima.parse('if(window.shouldStopExecuting) { break; }',{ tolerant: true })`

I understand why the error in the above code happens, but I would like to circumvent it. I tried using tolerant mode but I still received: `Error: Line 1: Illegal break statement`

Do you have any suggestions for how I may be able to avoid this error?
