### ISSUE TITLE
Cloning issues after 1604

### ISSUE THREAD

**Issue by aquinum6** [jquery/esprima#1672]
After changes was done to fix #1604, we're getting an error during cloning repo:

> adam@adam-SATELLITE:/tmp/test5$ git clone https://github.com/jquery/esprima.git .
> Cloning into '.'...
> remote: Counting objects: 14662, done.
> remote: Total 14662 (delta 0), reused 0 (delta 0), pack-reused 14662
> Receiving objects: 100% (14662/14662), 47.86 MiB | 13.18 MiB/s, done.
> Resolving deltas: 100% (9840/9840), done.
> Checking connectivity... done.
> adam@adam-SATELLITE:/tmp/test5$ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
>     modified:   test/fixtures/JSX/multiline-crlf-text.js
>     modified:   test/fixtures/comment/migrated_0011.js
>     modified:   test/fixtures/expression/primary/literal/string/migrated_0017.js
>     modified:   test/fixtures/invalid-syntax/migrated_0153.js
>     modified:   test/fixtures/invalid-syntax/migrated_0155.js
>     modified:   test/fixtures/invalid-syntax/migrated_0159.js
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> 

Confirmed on 3 different hosts with Ubuntu.

Adam thinks that problem occurs in the reference to changes done in .gitattributes
`+*.js text eol=lf`

Git diff (git v2.5.0):
```
adam@adam-SATELLITE:/tmp/test5$ git diff
warning: CRLF will be replaced by LF in test/fixtures/JSX/multiline-crlf-text.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/comment/migrated_0011.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/expression/primary/literal/string/migrated_0017.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/invalid-syntax/migrated_0153.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/invalid-syntax/migrated_0155.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in test/fixtures/invalid-syntax/migrated_0159.js.
The file will have its original line endings in your working directory.
diff --git a/test/fixtures/JSX/multiline-crlf-text.js b/test/fixtures/JSX/multiline-crlf-text.js
index ee074f1..7a89afd 100644
--- a/test/fixtures/JSX/multiline-crlf-text.js
+++ b/test/fixtures/JSX/multiline-crlf-text.js
@@ -1,5 +1,5 @@
-<em>
-One
-Two
-Three
-</em>
+<em>
+One
+Two
+Three
+</em>
diff --git a/test/fixtures/comment/migrated_0011.js b/test/fixtures/comment/migrated_0011.js
index 8b7c235..224921a 100644
--- a/test/fixtures/comment/migrated_0011.js
+++ b/test/fixtures/comment/migrated_0011.js
@@ -1,2 +1,2 @@
-/*a
+/*a
 b*/ 42
\ No newline at end of file
diff --git a/test/fixtures/expression/primary/literal/string/migrated_0017.js b/test/fixtures/expression/primary/literal/string/migrated_0017.js
index f9ac49b..7e5e4d1 100644
--- a/test/fixtures/expression/primary/literal/string/migrated_0017.js
+++ b/test/fixtures/expression/primary/literal/string/migrated_0017.js
@@ -1,2 +1,2 @@
-"Hello\
+"Hello\
 world"
\ No newline at end of file
diff --git a/test/fixtures/invalid-syntax/migrated_0153.js b/test/fixtures/invalid-syntax/migrated_0153.js
index 0505244..4edaa42 100644
--- a/test/fixtures/invalid-syntax/migrated_0153.js
+++ b/test/fixtures/invalid-syntax/migrated_0153.js
@@ -1,2 +1,2 @@
-
+
 ]
\ No newline at end of file
diff --git a/test/fixtures/invalid-syntax/migrated_0155.js b/test/fixtures/invalid-syntax/migrated_0155.js
index c5a7dbb..2d6b197 100644
--- a/test/fixtures/invalid-syntax/migrated_0155.js
+++ b/test/fixtures/invalid-syntax/migrated_0155.js
@@ -1,2 +1,2 @@
-//
+//
 ]
\ No newline at end of file
diff --git a/test/fixtures/invalid-syntax/migrated_0159.js b/test/fixtures/invalid-syntax/migrated_0159.js
index db9e136..189843e 100644
--- a/test/fixtures/invalid-syntax/migrated_0159.js
+++ b/test/fixtures/invalid-syntax/migrated_0159.js
@@ -1,2 +1,2 @@
-/*
+/*
 */]
\ No newline at end of file
```

It also affects @ariya fork.

**Comment by ariya** [comment]
Thanks for the quick notice!

This is indeed very strange. A fresh git clone on macOS does not show any problem. Also, the [Travis CI jobs](https://travis-ci.org/jquery/esprima/builds/183818604) (on Linux) as it cloned the repo and ran the tests as part of PR #1670 did not trigger any error .

**Comment by ariya** [comment]
Ah, I understand the problem now: `npm test` is not affected but file contents are being modified unintentionally.
