### ISSUE TITLE
Shouldn't 'LabeledStatement' be named 'LabelledStatement'?

### ISSUE THREAD

**Issue by hydroper** [jquery/esprima#1675]
I don't know how to create a pull request, so I suggest the node type 'LabeledStatement' be renamed to 'LabelledStatement', as in the [ES7 specification](https://tc39.github.io/ecma262/#prod-LabelledStatement).

This is likely a typo.

**Comment by mikesherov** [comment]
Thanks for contributing. Esprima follows the ESTree spec: https://github.com/estree/estree/blob/master/es5.md

Either way, this changing this now would break all the packages that rely on Esprima.

For that reason, I'm going to close this issue. Thanks again!
