### ISSUE TITLE
in vs of

### ISSUE THREAD

**Issue by streamich** [jquery/esprima#1700]
In `ForInStatement` and `ForOfStatement` as I understand the `in` and `of` are `Keyword`s.

In `ForInStatement`: `in` is returned as a `Keyword` token.

However, in `ForOfStatement`: `of` is returned as an `Identifier` token.

I would have expected `of` to be `Keyword` as well, or that should not be the case?

```js
for(var a in b) {}
for(var a of b) {}
```

**Comment by ariya** [comment]
This is actually by design. Looking at specification, `of` is not a keyword (check Section 11.6.2.1 on _Keywords_: http://www.ecma-international.org/ecma-262/7.0/index.html#sec-keywords).
