### ISSUE TITLE
`static` token can occasionaly be a plain identifier even in a class

### ISSUE THREAD

**Issue by icefapper** [jquery/esprima#1725]
in `class A { static static() {} }`, for example, the first `static` should have the type `Keyword` while the next one should have the type `Identifier`; the tokenizer currently gives the latter the same type as the former.

**Comment by mikesherov** [comment]
Does this only apply when tokenizing, or in the ast as well?

**Comment by icefapper** [comment]
my apologies for not giving more detail -- this is only the case with the tokens returned via the `tokens` parser option (e.g, `esprima.parse('class A{static static() {}}',{tokens:true}).tokens`); I am not very familiar with esprima's inner workings, but it guess it won't have any effect on the resulting AST actually.

**Comment by mikesherov** [comment]
Right, thanks. So this is then another example where tokenization doesn't deeply consider context so we rely on what the grammar defines `static` to be as a token regardless of whether it's used as an identifier.
