### ISSUE TITLE
Dynamic import syntax support

### ISSUE THREAD

**Issue by guybedford** [jquery/esprima#1728]
I couldn't find an issue tracking this already, but let me know if it is a duplicate. This may well be implementable now that it is Stage 3 (https://github.com/estree/estree/pull/137).

**Comment by ariya** [comment]
New productions:
```
CallExpression[Yield] :
  ImportCall[?Yield]

ImportCall[Yield] :
    import  (  AssignmentExpression[+In, ?Yield]  )
```

AST format additions: TBD.

References:
- The proposal: https://tc39.github.io/proposal-dynamic-import/
- Change to the spec: ?
- ESTree change: https://github.com/estree/estree/pull/137

**Comment by huochunpeng** [comment]
@ariya is it possible to release a minor version in v4 with this feature?
