### ISSUE TITLE
lambda-view: A New Tool for Reading JavaScript Code (based on esprima)

### ISSUE THREAD

**Issue by Jianru-Lin** [jquery/esprima#1757]
I created an tool for reading javascript code, and it's based on esprima: https://github.com/Jianru-Lin/lambda-view

Is it possible to add it http://esprima.org/demo/index.html ?

Thanks.

**Comment by ariya** [comment]
The website is just GitHub Pages. Feel free to create a PR to the `gh-pages` branch.
