### ISSUE TITLE
Detecting wrapped binary expression

### ISSUE THREAD

**Issue by thetutlage** [jquery/esprima#1775]
Given a situation where I am using `esprima` for parsing Javascript expressions to AST and converting them back to expression with some domain specific modifications. 

I have situation with a binary expression especially when they are nested and wrapped inside `()`. For example

```js
esprima.parse('2 * (3 + 2 * 4)')
// vs
esprima.parse('2 * 3 + 2 * 4')
```

### Steps to reproduce

**For 1st statement**
http://esprima.org/demo/parse.html?code=%2F%2F%20Seems%20tricky%20to%20me%0A2%20*%20(3%20%2B%202%20*%204)%0A

**For 2nd statement**
http://esprima.org/demo/parse.html?code=%2F%2F%20Seems%20tricky%20to%20me%0A2%20*%203%20%2B%202%20*%204%0A

Now there is no way for me to know that the original expression/statement was wrapped inside a `()`. I can go ahead and wrap each side of expression `left` and `right` inside parenthesis whenever it is a nested binary expression but that will introduce different outputs since they are `arithmetic` in nature.

**Comment by michaelficarra** [comment]
That's right. Esprima produces an *abstract* syntax tree, not a concrete syntax tree. You also wouldn't know if a numeric literal was written in base 10, 16, 8, or 2. Or what escape sequences were used in strings and identifiers.

**Comment by thetutlage** [comment]
Ohhh that's tricky. Just a question on what is purpose of esprima? I am trying to use to build a template engine and wrong purposes will collide quite often

**Comment by ariya** [comment]
@thetutlage Esprima provides a parser and a tokenizer. For your purpose where you need more information than what an AST could provide, it might not be sufficient.

Now, there is a rather dirty workaround for this. You can enable node location and also produce the list of tokens. This will allow you to cross reference a node in the token list and to figure out if e.g. there is a `(` before the node. This is considered a very advanced use of Esprima so please read and digest the [documentation](http://esprima.org/doc/) before embracing this adventure. Also, be advised this is impossible to get it right in every case but perhaps it is sufficient for you.

**Comment by thetutlage** [comment]
Yup esprima does a way good job and for sure I have to do some close analysis for edge cases.

But anyways, thanks for your quick help and great work with esprima too.
