### ISSUE TITLE
JSX spread children issue

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1789]
Trying to parse, and my computer ran out of memory.

### Steps to reproduce

```js
esprima.parse('<div {...c}> {...children}{a}{...b}</div>', { jsx: true})
```

### Expected output
Should parse

### Actual output
Throws and run out of memory

**Comment by ariya** [comment]
It should not consume any memory at all. It should throw an exception "Unexpected token ..." because the parser does not known the syntax (adding support for JSXSpreadChild will be tracked as #1819)
