### ISSUE TITLE
[Question] grammar, early errors and precedence climbing

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1792]
@mikesherov I'm trying to understand the Esprima code, and solve all known issues, but no solutions yet. 

Regarding early errors. What is the ideas here? It's own Scope tracker ala Acorn, or a solution ala Shift? See [parseScript](http://www.ecma-international.org/ecma-262/7.0/#sec-parse-script). It says

```js
3. If body is a List of errors, then return body.
```
Under all circumstances it has to return an list of errors if we are following the specs. If we think about performance, scanning the whole AST tree aka Shift maybe too expensive?

Regarding the grammar. Current grammar solution isn't updated to latest specs, and using `this` inside functions like `isolateCoverGrammar()` is expensive. What is the thoughts here, and are the grammar error isolated out, so an error array will be returned? See what I wrote above.

The precedence climbing with all pop and push is also costly. TypeScript have a improved solution seen [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/parser.ts#L2876). Any plans to change this?

**Comment by ariya** [comment]
Please submit questions or other open-ended discussions to the [mailing-list](http://groups.google.com/group/esprima) instead.

**Comment by nowindowsowrking** [comment]
Not much activity there, but will give it a shot.
