### ISSUE TITLE
esprima.parse crashes on import declaration

### ISSUE THREAD

**Issue by smelukov** [jquery/esprima#1826]
### Steps to reproduce

```js
esprima.parse(`import {a, b, c} from 'some'`)
```

### Expected output

Expected the AST

### Actual output

Exception `{index: 0, lineNumber: 1, description: "Unexpected token", column: 1}`

### Relevant references

In the [demo editor](http://esprima.org/demo/parse.html?code=import%20%7Ba%2C%20b%2C%20c%7D%20from%20'some'%3B) there is no error.

**Esprima version:** 3.1.3

**Comment by michaelficarra** [comment]
https://esprima.readthedocs.io/en/latest/syntactic-analysis.html#distinguishing-a-script-and-a-module

**Comment by mikesherov** [comment]
Thanks for contributing! Yes, please use the parseModule method to parse modules.

**Comment by smelukov** [comment]
Thanks!
