### ISSUE TITLE
yield should be parsed as identifier in object methods

### ISSUE THREAD

**Issue by RReverser** [jquery/esprima#1834]
### Steps to reproduce

```js
function *a(){({b(){yield}})}
function *a(){({get b(){yield}})}
function *a(){({set b(c){yield}})}
```

### Expected output
In each of these cases `yield` is parsed as `YieldExpression`.

### Actual output
It should be parsed as regular `Identifier` because object method is a separate function on its own.

**Comment by ariya** [comment]
Thanks for the report @RReverser!
