### ISSUE TITLE
Auto complete support

### ISSUE THREAD

**Issue by amiramw** [jquery/esprima#1848]
Auto complete according to documentation rely on outdated patch.
In the documentation there is a code completion example and it is stated that: 

> Autocompletion (press Ctrl+Space) is provided via a type inferencer, part of Content Assist module of Scripted, hooked into the editor based on Eclipse Orion.

However, it seems that Eclipse orion doesn't use esprima anymore. And the patch done by them only works for older version (I think 1.0.3, the documentation uses http://esprima.org/assets/orion/contentassist/esprima.js).

My question is if there is a plan to support this functionality in esprima latest version and not as a patch from the outside? Will you welcome PRs for such functionality?

### Relevant references
http://esprima.org/demo/autocomplete.html

**Comment by ariya** [comment]
Unfortunately, providing a full autocomplete support is beyond the scope of this project. Technically, code completion is really a different service which can rely on functionalities offered by a parser.
I suggest looking at another autocomplete project such as https://github.com/espadrine/aulx.

**Comment by amiramw** [comment]
Thanks. Shouldn't http://esprima.org/demo/autocomplete.html be removed from documentation or at least state that it is not applicable for current version?
