### ISSUE TITLE
[question] where to publish a bug list?

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1853]
After my research work I  have a list of over 700 bugs found in Esprima. 

The common cases covered by this bugs:

- Not matching TC39
- Parses when they should fail
- Fail when the tests are valid
- Early errors

Is there anywhere I can publish this list so people can use it if the want to fix Esprima?

**Note** Around 130 of this bugs can't be fixed without a refactoring of the code base. Should I skip this from the list I have?

**Comment by michaelficarra** [comment]
@nowindowsowrking Submitting these programs and non-programs to [test262-parser-tests](https://github.com/tc39/test262-parser-tests) would be a good start.

**Comment by nowindowsowrking** [comment]
I'm closing this as I can't see any point to publish the Esprima internal bugs at this point, but will soon push tests to test262 parser-tests.

@michaelficarra Impressed by your ShiftJS parser! Very close to the ECMA specs. It even handle the difference between module code and strict mode correctly. Wich both Acorn and Esprima fails on!
