### ISSUE TITLE
Spread in objects doesn't parse

### ISSUE THREAD

**Issue by aslushnikov** [jquery/esprima#1862]
Expected: The following javascript should parse correctly:

```js
const b = [1,2,3];
const a = {
  ...b
};
```

Actual: esprima throws. ([demo](http://esprima.org/demo/parse.html?code=const%20b%20%3D%20%5B1%2C2%2C3%5D%3B%0Aconst%20a%20%3D%20%7B%0A%20%20...b%0A%7D%3B))

**Comment by vdsabev** [comment]
Related issue: #1588

**Comment by nowindowsowrking** [comment]
@aslushnikov See https://github.com/jquery/esprima/issues/1587. And be aware that @mikesherov can claim you are a troll when you report bugs!

**Comment by ariya** [comment]
As @vdsabev mentioned, this was already tracked in #1588. It's still not part of the latest ECMA-262 spec, hence the stable version of Esprima (and the online demo) doesn't have it. The implementation however already exists in the master branch.

**Comment by nowindowsowrking** [comment]
@aslushnikov You could try Acorn + the spread plugin if you need this to work or are dependent of such feature so you don't have to wait until next year. BTW. Current Esprima implementation isn't up to date with the specs. See my open issue tickets. Or you could try Babylon or Cherow. Both are up to date.

**Comment by 0xCAFEF00D** [comment]
I was getting the same error in the latest version (4.0.1) when using the spread syntax in objects. I patched the first line of Parser.prototype.parseObjectProperty with the following which solved the problem and generated the expected output:

```
Parser.prototype.parseObjectProperty = function (hasProto) {
  // PATCH 
  if (this.lookahead.value === '...') 
    return this.parseSpreadElement();
```

**Comment by 0x00C5** [comment]
There's a solution here https://github.com/jquery/esprima/issues/2034#issuecomment-818542469
