### ISSUE TITLE
Avast is throwing an infection alert while installing lexical-analysis.md

### ISSUE THREAD

**Issue by aramys** [jquery/esprima#1865]
I'm running an `npm install` and hitting the following error.

```
npm ERR! path /Users/aramys/git/acme-b2c-frontend/ui/node_modules/.staging/esprima-5a405500/docs/lexical-analysis.md
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall utime
npm ERR! enoent ENOENT: no such file or directory, utime '/Users/aramys/git/acme-b2c-frontend/ui/node_modules/.staging/esprima-5a405500/docs/lexical-analysis.md'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aramys/.npm/_logs/2017-10-23T21_50_13_333Z-debug.log
```

<img width="319" alt="screen shot 2017-10-23 at 2 47 11 pm" src="https://user-images.githubusercontent.com/108946/31915141-2d4236e8-b802-11e7-883f-b82486761a0e.png">

This is due to my antivirus being kicked off and throwing the attached error.

### Steps to reproduce
`npm install` 

### Expected output
Install continues

### Actual output
Install does not complete

**Comment by michaelficarra** [comment]
This bug report should go to Avast, not us.

**Comment by aramys** [comment]
I wanted to ensure that the repository is not in fact been compromised, and that you and others were aware that this is happening. You can close the bug, but, it would be a good idea to check this with other anti-viruses as well which I don't have the bandwidth to do.

**Comment by michaelficarra** [comment]
I just checked by hand, there's no viruses in that markdown file. Please let Avast know about their bug.

**Comment by mikesherov** [comment]
Try upgrading npm. Some of the more recent versions had a bug on Windows with the way fsync works that triggered spurious AV warnings. Thanks!

**Comment by aramys** [comment]
For the record, this is on a completely fresh install on Mac OS High Sierra. Latest NPM, Latest NodeJS.
