### ISSUE TITLE
Whats`s the average response time?

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1879]
Just wonder what is the average response time from a defect have been reported to it's fixed? 1 month? 1 year or 3 years? I noticed a few issue tickets are 3 years old.

Acorn respond within 1 - 2 days before fixed. Based on the history log ShiftJS seems to respond within 1 - 2 days. Cherow stated in the readme the author (s) will fix any bugs reported within 30 minutes. Thats's insane fast.

I'm not sure about respinse time for Babylon, Espree and Flow.

**Comment by ariya** [comment]
Everyone is rather busy these days, so the answer is probably a big number, trending towards `Infinity`.

To get a more accurate answer, I suggest writing a script utilizing GitHub API to iterate through every single issue and compute the mean of the timestamp delta.

**Comment by ariya** [comment]
Closing this, due to lack of possible follow-up.

**Comment by nowindowsowrking** [comment]
"due to lack of possible follow-up"? Agree. There was no response from the Esprima team on this . But still my question still stand. Some of the issues haven't been fixed for 3 years, yesterday another users compalingin gbecause no response from Esprima team for more than 18 days etc. So highly relevant question. What is the response time?
