### ISSUE TITLE
Inconsistent RegExp parsing behavior

### ISSUE THREAD

**Issue by jugglinmike** [jquery/esprima#1883]
### Steps to reproduce

Run the following code using Node.js version 9.2.0 (or higher):

```js
esprima.parse('/(?<=.)/');
```

### Expected output

Parsing error.

### Actual output

An AST is returned:

```json
{
  "type": "Program",
  "body": [
    {
      "type": "ExpressionStatement",
      "expression": {
        "type": "Literal",
        "value": {},
        "raw": "/(?<=.)/",
        "regex": {
          "pattern": "(?<=.)",
          "flags": ""
        }
      }
    }
  ],
  "sourceType": "script"
}
```

### Relevant references

RegExp Lookbehind Assertions are a new language extension currently at stage
3 in TC39's proposal process. I can't find any documentation regarding
Esprima's commitment to new language features, so it may be that the "bug" is
that the code is not supported in other run times.

Realistically, though, implementing consistent behavior would require extending
Esprima with a complete regular expression parser. I don't think this is
necessarily out of scope for a JavaScript parser, but it is likely far more
complicated (not to mention slow) than is warranted to address these edge
cases.

With that in mind, I'm wondering if the inconsistency warrants some explicit
documentation.

- Identified via https://github.com/jquery/esprima/pull/1880
- Proposal for "RegExp Lookbehind Assertions":
  https://github.com/tc39/proposal-regexp-lookbehind

**Comment by ariya** [comment]
There was a deliberate choice in the beginning of the project to not cover regular expression parsing and validation. Doing such will increase the size of Esprima significantly. Beside, if someone wants such a functionality, it doesn't have to be built in into Esprima. Nothing stops them from doing all forms of post processing, including parsing/validating each regular expression internal, after the parsing is completed.

That said, I completely agree that it should be mentioned in the documentation! Feel free to suggest a modification to the documentation (see `docs` subdirectory, which will be consumed and turned into http://esprima.readthedocs.io/).

**Comment by jugglinmike** [comment]
Sounds good to me. I'm hoping to give this a shot soon
