### ISSUE TITLE
Improvement: Request to redefine parse method in esprima version 4.0+

### ISSUE THREAD

**Issue by nosaj-neirbo** [jquery/esprima#1893]
Quote from documentation:

"Failing to choose the correct parsing function can lead to a mistaken observation that Esprima does not support a certain syntax. Take a look at this example:

    $ node
    > var esprima = require('esprima')
    > esprima.parseScript('export const answer = 42');
    Error: Line 1: Unexpected token

Instead of producing the syntax tree, the parser throws an exception. This is the correct behavior, an export statement can only be part of a module, not a script. Thus, the parser properly determines that such a source program is invalid.

Note: In the previous versions (Esprima <= 3.1), there was a single parsing function, parse. To distinguish between parsing a script and a module, the sourceType property in the configuration object needs to be specified, either as "script" (also the default value) or "module". While this parse function is still supported in Esprima 4 for API backward compatibility, its usage is highly discouraged and the support for it may be removed in a future version."

Request:

Couldn't this just be easily solved by defining parse this way?  ...
    
    esprima["parse"] = function( input, config, delegate ) {

        var ES5Module = Boolean(input.match(/(module\.)*exports\s*\=/));

        if ( !ES5Module ) {
            try {
                var parsedResult = esprima.parseScript( input, config, delegate );
                return parsedResult;
            } catch(err) {}
        }

        return esprima.parseModule( input, config, delegate );

    };

I've actually used this approach in projects where I needed to read a list of files and not know ahead of time which method I must use.

Examples of some tests I ran:

    testData = 'export const answer = 42';
    console.log( esprima.parse(testData) ); // => Module { ...

    testData = 'exports = { answer: 42 }';
    console.log( esprima.parse(testData) ); // => Module { ...

    testData = 'module.exports = { answer: 42 }';
    console.log( esprima.parse(testData) ); // => Module { ...

    testData = 'export const answer = 42';
    console.log( esprima.parse(testData) ); // => Module { ...

    testData = 'export default answer = 42';
    console.log( esprima.parse(testData) ); // => Module { ...

    testData = 'export class myClass { constructor() { this.foo = 42; } }';
    console.log( esprima.parse(testData) ); // => Module { ...

    testData = 'class myClass { constructor() { this.foo = 42; } }';
    console.log( esprima.parse(testData) ); // => Script { ...

    testData = 'const answer = 42';
    console.log( esprima.parse(testData) ); // => Script { ...

**Comment by michaelficarra** [comment]
No, this cannot be done. Modules don't have to have import/export declarations, and are implicitly strict mode code. If you want an interface like the one you describe, which will work in many but not all cases, just use your own implementation.

**Comment by ariya** [comment]
Basically what @michaelficarra just wrote above.

Beside, using a regular expression to look e.g. `export` is definitely not foolproof.

**Comment by nosaj-neirbo** [comment]
@michaelficarra @ariya Just out of curiosity, could you explain "Modules don't have to have import/export declarations". What is an example of a module without exports?

I understand if my solution doesn't seem fullproof, for whatever reason, but definition-wise, what's the distinction then?

I have scoured the web looking for an answer, but all I find are descriptions that are vague, misleading, or describe what happens when something IS a module, the effects.

I am still trying to find some information, somewhere, that contradicts the idea that a module is simply some script that contains exports, period.

The consensus seems to be that this is wrong, but I don't understand why. Could you explain it to me?

Javascript must have a formal definition, somewhere, right? I just can't believe there isn't an algorithm that exists to determine if something is a script or a module, even if there is no automatic solution.

I am trying to develop an algorithm to search for files and parse them, not knowing ahead of time, what they are, which to me seems to be a more common sense use case than knowing.

Help me, Obi- Wan Kenobi, you're my only hope...

**Comment by ariya** [comment]
> Javascript must have a formal definition, somewhere, right?

That is the official ECMAScript specification. If you look at it, it clearly defines that export/import declarations do not have to be in the modules. IOW, a module without such declaration must be considered as valid.

Now, the fact that nobody writes a module without any export is a different matter.
