### ISSUE TITLE
Improve performance and memory usage?

### ISSUE THREAD

**Issue by ghost** [jquery/esprima#1896]
I noticed that Esprima are approx 26% slower than the Cherow parser, and around 52% slower when it comes to parsing huge  libraries (*more than 10 000 lines of code*)

I also compared against Acorn, and even on small libraries it seems that Acorn are faster in a few cases. 

If I run the same tests over and over again the difference in performance between Acorn and Esprima are very clear. This for libraries such as Rollup, Angular 1.6 and even Esprima itself.  
For smaller libraries less than 1000 lines, the difference in performance between Acorn and Esprima are minimal. Almost non-existing.

I further checked the memory usage, and for larger libraries such as TypeScript 2.6.2 and React 16, Esprima eat a lot of RAM. You can measure this yourself.

Any plans to improve this?

**Comment by ariya** [comment]
Closing this for the lack of concrete follow-up.

**Comment by KFlash** [comment]
I come across this issue, and I think it's enough to run any online benchmark to get to the point.

**Desktop computer:**

![bench](https://user-images.githubusercontent.com/31855118/40696410-53daa036-63f8-11e8-9e31-80b3943690ca.png)

**Mobile:**

![mobile](https://user-images.githubusercontent.com/31855118/40696450-7f4fe442-63f8-11e8-8309-1b16cdd3e0e5.jpg)

As far as I noticed. Acorn is for the most part equal in performance except for mobile devices.

**Comment by KFlash** [comment]
The previous benchmarks was done in Chrome. Here is another one I ran with the Microsoft Edge browser.

![edge](https://user-images.githubusercontent.com/31855118/40747375-b143a7e4-648f-11e8-9584-65cbdc772932.png)

Esprima is faster than Acorn in this benchmark.
