### ISSUE TITLE
return keyword and multiline string expression

### ISSUE THREAD

**Issue by akaJes** [jquery/esprima#1897]
[the code](http://esprima.org/demo/parse.html?code=%2F%2F%20Paste%20your%20JavaScript%20code%20here%0Afunction%20hi()%20%7B%0A%20%20return%20%22Hello%20%5C%0A%09World!%22%3B%0A%7D%0Aconsole.log(hi())%3B) parsed separately, but ECMA allow to use [this](https://www.ecma-international.org/ecma-262/5.1/#sec-12.9)
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/154

**Comment by michaelficarra** [comment]
I believe this has already been fixed as part of https://github.com/jquery/esprima/pull/1882.
