### ISSUE TITLE
if (false) (/(/); is valid but won't parse

### ISSUE THREAD

**Issue by rabbihyatt** [jquery/esprima#1902]
this is most probably because esprima validates regex literals, even though validataion must happen in run-time (that is, is not the responsibility of the parser, actually)

> A regular expression literal is an input element that is converted to a RegExp object (viz. 21.2) each time the literal is evaluated

along with

> The RegExp constructor applies the following grammar to the input pattern String. An error occurs if the grammar cannot interpret the String as an expansion of Pattern.

**Comment by michaelficarra** [comment]
Esprima rejects programs with early errors, which this has.

**Comment by rabbihyatt** [comment]
@michaelficarra yeah, looks like it has been a bug with my spec-reading skills rather than with the spec itself
