### ISSUE TITLE
SwitchCase can have null as its test.

### ISSUE THREAD

**Issue by DaramG** [jquery/esprima#1909]
At the document, SwitchCase has only Expression as test like bellow.
```js
interface SwitchCase {
    type: 'SwitchCase';
    test: Expression;
    consequent: Statement[];
}
```
But, "default" which is parsed as SwtichCase has null as test.
So, document should be edited like that.
```js
interface SwitchCase {
    type: 'SwitchCase';
    test: Expression | null;
    consequent: Statement[];
}
```

**Comment by michaelficarra** [comment]
@DaramG I think you want to file this issue over at https://github.com/estree/estree.
