### ISSUE TITLE
Make clear the level of TypeScript + JSX/TSX support (or not?)

### ISSUE THREAD

**Issue by kristianmandrup** [jquery/esprima#1922]
The documentation provides no clue as to whether esprima in the latest release supports TypeScript and TSX.  Please make this clear. No section on typescript in the docs. If not supported, please also make this clear.

https://esprima.readthedocs.io/en/latest/

Browsing the issues, it seems like TypeScript is supported at some level, but not clear from the official docs either, only that JSX is supported. Looking at the code and commits I see a commit such as `Update TypeScript compiler, linter, and formatter to the latest version`, so...

How do I enable TypeScript parsing if available? From the [test fixtures](https://github.com/jquery/esprima/tree/master/test/fixtures), there is no mention of typescript.

What are my best options for traversing a TypeScript AST. The one emitted by typescript itself is extremely hard to work with. I guess my best option is to tweak some ESLint lib?

Thanks.

**Comment by ariya** [comment]
What would you suggest?

Note that Esprima is intended to parse JavaScript/ECMAScript. I do not think that there is any claim in the documentation that Esprima has the ability to parse TypeScript.
