### ISSUE TITLE
Wrong description for ConditionalExpression

### ISSUE THREAD

**Issue by SDemonUA** [jquery/esprima#1929]
`ConditionalExpression` described like `IfStatement` with optional `alternate` and types for `alternate` and `consequent` described as `Statement`. But `ConditionalExpression` represent ternary operator ` ? : ` that always have `alternate` and both `alternate` and `consequent` can be only type of `Expression`.

### Expected output
```
interface ConditionalExpression {
    type: 'ConditionalExpression';
    test: Expression;
    alternate: Expression;
    consequent: Expression;
}
```

### Actual output
```
interface ConditionalExpression {
    type: 'ConditionalExpression';
    test: Expression;
    consequent: Statement;
    alternate?: Statement;
}
```
### Relevant references
https://www.ecma-international.org/ecma-262/6.0/#sec-conditional-operator
https://github.com/estree/estree/blob/master/es5.md#conditionalexpression

**Comment by michaelficarra** [comment]
It looks correct to me: https://github.com/jquery/esprima/blob/529a5f2bcb56bddf9a1b978826646a123a75784e/src/nodes.ts#L260

What version are you using?

**Comment by SDemonUA** [comment]
Documentation
[https://github.com/jquery/esprima/blob/master/docs/syntax-tree-format.md#conditional-expression](url)`

**Comment by SDemonUA** [comment]
It looks like Property documentation is also out of date https://github.com/jquery/esprima/blob/master/docs/syntax-tree-format.md#object-expression
https://github.com/jquery/esprima/blob/529a5f2bcb56bddf9a1b978826646a123a75784e/src/nodes.ts#L609-L626

Property key should be Expression:
http://esprima.org/demo/parse.html?code=var%20a%20%3D%20%7B%0A%09out%3A%202%2C%0A%09%5Ba%2B2%5D%3A%202%0A%7D

**Comment by ariya** [comment]
Thanks for your sharp eyes @SDemonUA! I'll get it fixed soon.

**Comment by SDemonUA** [comment]
@ariya It seems `esprima/src/nodes.ts` also need changes for Property
