### ISSUE TITLE
Possible to support "import.meta"?

### ISSUE THREAD

**Issue by idleman** [jquery/esprima#1938]
How hard would it be to add support for the import.meta proposal: https://github.com/tc39/proposal-import-meta? 

### Steps to reproduce
Online example: http://esprima.org/demo/parse.html?code=console.log(import.meta.props)%3B

**Comment by ariya** [comment]
It should not be difficult if you are knowledgable with parser.
We generally do not implement any proposal until it is mature enough (stage 4).

**Comment by idleman** [comment]
Well, I assume it explained it, the proposal have not been finalized yet.
