### ISSUE TITLE
Implement full fidelity parse trees

### ISSUE THREAD

**Issue by KvanTTT** [jquery/esprima#1952]
Full-fidelity parse tree - such a tree that can be converted back into the same character-for-character code, including spaces, comments and preprocessor directives, even if there are some syntax errors.

It's useful for refactoring and detection of some weaknesses and vulnerabilities in source code. For example, consider the well-known [goto fail vulnerability](https://www.synopsys.com/blogs/software-security/understanding-apple-goto-fail-vulnerability-2/):

```c
if ((err = SSLHashSHA1.update(&hashCtx, &signedParams)) != 0)
    goto fail;
    goto fail;
```

It can be detected in two ways. The first one is a parse tree way, it includes analyzing of incorrect indents of statements. The second one is harder, it analyzes control flow graphs.

So, I want to say that full fidelity trees are important. Also, take a look at the structure of the parse tree in mature [Rosyn C# analyzer](https://github.com/dotnet/roslyn/wiki/Roslyn-Overview#syntax-trees).

**Comment by ariya** [comment]
Thanks to for the suggestion! I think the right place is to discuss this is https://github.com/estree/estree.
I believe there was also some previous proposals (in the ESTree project) along this line.
