### ISSUE TITLE
Support optional try/catch binding as added in Node 10 & V8 6.6

### ISSUE THREAD

**Issue by Avuxo** [jquery/esprima#1953]
[Support for this ECMAScript Stage 4 proposal](https://github.com/tc39/proposal-optional-catch-binding). This has already been implemented in [v8 6.6](https://v8.dev/blog/v8-release-66) and as a result is already implemented in new versions of Google Chrome/Chromium and Node.js 10. This language feature is used in the Node.js `assert' standard library, so any users who attempt to apply the parser to that file will encounter this error.

Previously, try/catch statements required a binding to be syntactically valid. However, with this change they are no longer a requirement as the binding is now optional.
```js
try {
    // something exceptional
} catch {
    // no longer has a required parameter
}
```
This issue would be a fairly simple implementation and would likely not add any significant overhead to the parsing process.

### Steps to reproduce

```js
// run in any environment using V8 6.6: Google Chrome or Node 10.x
esprima.parse('try { new Error(); } catch {}');
```

### Expected output

```
// AST
{
  "type": "Program",
  "body": [
    {
      "type": "TryStatement",
      "block": {
        "type": "BlockStatement",
        "body": [
          {
            "type": "ExpressionStatement",
            "expression": {
              "type": "NewExpression",
              "callee": {
                "type": "Identifier",
                "name": "Error"
              },
              "arguments": []
            }
          }
        ]
      },
      "handler": {
        "type": "CatchClause",
        "param": null,
        "body": {
          "type": "BlockStatement",
          "body": []
        }
      },
      "finalizer": null
    }
  ],
  "sourceType": "script"
}
```
### Actual output

```
/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:1995
	        throw this.unexpectedTokenError(token, message);
	        ^
Error: Line 1: Unexpected token {
    at ErrorHandler.constructError (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.expect (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:2168:19)
    at Parser.parseCatchClause (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:4049:15)
    at Parser.parseTryStatement (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:4080:58)
    at Parser.parseStatement (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:4157:43)
    at Parser.parseStatementListItem (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:3388:39)
    at Parser.parseScript (/Users/ben/workspace/testing/catch-binding/node_modules/esprima/dist/esprima.js:4723:29)
```
### Relevant references

- [Stage 4 ECMAScript TC39 proposal](https://github.com/tc39/proposal-optional-catch-binding) 
- [v8 6.6 change log](https://v8.dev/blog/v8-release-66)

**Comment by ariya** [comment]
Hi @Avuxo, thanks for the report.

For a new language feature, we usually need more details, see [this guide](https://github.com/jquery/esprima/wiki/Maintainer's-Guide#proposing-a-language-feature-for-inclusion). For some examples, see e.g. #1550. Please review the issue description to include the necessary information.

**Comment by JosephPecoraro** [comment]
It has been nearly a year! Lets see what we can do to move this forward.

**Comment by JosephPecoraro** [comment]
## ES2018 Feature: Optional catch binding: Tracking Issue

## Syntax:

```js
try { } catch { }
```

New production for `Catch` that just doesn't require a binding:

```diff
 Catch[Yield, Await, Return]:
     catch ( CatchParameter[?Yield, ?Await] ) Block[?Yield, ?Await, ?Return]
+    catch Block[?Yield, ?Await, ?Return]
```

## Spec:

https://github.com/tc39/proposal-optional-catch-binding
https://tc39.es/proposal-optional-catch-binding/

## Remaining Tasks:

 - [ ] Update Issue #1954

## Additional considerations

* Supported and shipped in all major browsers: Safari, Chrome, Firefox
* Supported in JavaScript environments: jsc, node
* Proposed AST change is that `CatchClause` will now have an optional (null) `param`

**Comment by JosephPecoraro** [comment]
This was added to ESTree for ES2019:
https://github.com/estree/estree/blob/master/es2019.md

----

This document specifies the extensions to the core ESTree AST types to support the ES2019 grammar.

# Statements

## CatchClause

```js
extend interface CatchClause {
    param: Pattern | null;
}
```

The `param` is `null` if the `catch` binding is omitted. E.g., `try { foo() } catch { bar() }`

**Comment by ariya** [comment]
Thanks for adding some more important details @JosephPecoraro!

**Comment by darrnshn** [comment]
Any update on this? It still seems to be invalid on the demo page: https://esprima.org/demo/parse.html?code=try%20%7B%7D%20catch%20%7B%7D

We would really appreciate this fix! Thanks!

**Comment by peterkhayes** [comment]
This is still broken for me, as is the demo that @darrnshn posted.
