### ISSUE TITLE
Await not parsed in 4.0.1

### ISSUE THREAD

**Issue by whoisstan** [jquery/esprima#1955]
Can't get the parser to work with 'await'.  Having difficult times to find the relevant options that can be passed into the parse function.

### Steps to reproduce
```js
const esprima  = require('esprima');
esprima.parse("await function_call()")
```

### Expected output
Describing the code structure containing the await call

### Actual output
Error: Line 1: Unexpected identifier

**Comment by whoisstan** [comment]
got i: "async ()=>{await function_call()}"

**Comment by ariya** [comment]
Thanks for the report. It behaves as expected, you need to have `await` inside a function.
