### ISSUE TITLE
JS Error in comparison page

### ISSUE THREAD

**Issue by igneel64** [jquery/esprima#1968]
Hey, I wanted to check a bit on the benchmarks page for Esprima and the other parsers but there seems to be an issue on the http://esprima.org/test/compare.html page.
![image](https://user-images.githubusercontent.com/15251081/56196543-b22cd700-603f-11e9-85da-13f12946de12.png)

I did not find any place that this could be fixed in the repo, just wanted to report it and if you have any place that you keep those docs, point me so that I could look into possibly fixing it. Thanks!

**Comment by ariya** [comment]
Thanks @igneel64 for the report! I'll take a look. The site is actually in the repo, under the `gh-pages` branch.
