### ISSUE TITLE
esprima.org - invalid https SSL certificate

### ISSUE THREAD

**Issue by trivikr** [jquery/esprima#1975]
### Steps to reproduce
https://esprima.org/ shows invalid SSL certificate
This issue was noticed while adding link to ESPrima in OpenJSF CPC README in https://github.com/openjs-foundation/cross-project-council/pull/218 

### Expected output
The website https://esprima.org/ loads without any certificate issues

### Actual output
https://esprima.org/ shows invalid SSL certificate

**Comment by trivikr** [comment]
Any update on this request?

**Comment by ariya** [comment]
Thanks for the report @trivikr! I'll take a look.

**Comment by ariya** [comment]
https://esprima.org is now working as intended.
