### ISSUE TITLE
Shoud update readme that this repo now is stall ?

### ISSUE THREAD

**Issue by donnagf** [jquery/esprima#1992]
This bullets should be enough to prove this repo is stall:

- New Esprima version every year. Not happen anymore.

- ES2018 features is said to be implemented mid 2018. Over 1 year ago.

- ES2019 and ES2020 features not implemented

- Missing follow up on issues and PR

- The author are almost not active on GH anymore. See his profile.

- The author said for 1 year ago that he should investigate and follow up some issues. Still
not happened.

**Comment by JosephPecoraro** [comment]
> ES2019 and ES2020 features not implemented

I plan to send PRs for these very soon.

> The author are almost not active on GH anymore.

If no maintainer is that would be pretty sad. I'll try to send some PRs and see if I can get a reviewer.

**Comment by ariya** [comment]
Help is always welcomed!

**Comment by JosephPecoraro** [comment]
> Help is always welcomed!

A few PRs are out for minor bug fixes, with ES2018+ES2019 updates to follow if these can get landed!

**Comment by ariya** [comment]
> > Help is always welcomed!
> 
> A few PRs are out for minor bug fixes, with ES2018+ES2019 updates to follow if these can get landed!

Awesome, I'll take a look at that. Thanks @JosephPecoraro!
