### ISSUE TITLE
Update minimum node version and CI scripts

### ISSUE THREAD

**Issue by calvinf** [jquery/esprima#2012]
As Node versions less than 10 are deprecated, this PR bumps the minimum in package.json to Node 8 and updates the versions run on CI.  

### Steps to reproduce

* View supported [Node releases](https://nodejs.org/en/about/releases/)
* Everything older than Node 10 is no longer supported

### Proposed change

* Bump minimum engine in package.json to 8 (assuming some people may still need time to migrate off of 8)
* Update CI scripts

### Pull request

https://github.com/jquery/esprima/pull/2011

**Comment by ariya** [comment]
Implemented in commit 3d182f16.

@calvinf Next time, please mention this issue number in the commit log so it is referred here automatically.

**Comment by calvinf** [comment]
@ariya Okay, I’ll do that next time.
