### ISSUE TITLE
Update dev dependency: lodash

### ISSUE THREAD

**Issue by calvinf** [jquery/esprima#2014]
In preparation for the 5.x update, `esprima` is updating its dev dependencies.  As such, `lodash` needs to be updated.

### Steps to reproduce

* View package.json and package-lock.json
* Currently on 3.10.x

### Expected output

* `lodash` 4.17.5 is current

### Relevant references

* https://www.npmjs.com/package/lodash

**Comment by calvinf** [comment]
Lodash is easy to update, but it's leading to problems with the browser tests (where it's used). Looking at how it's used (`forEach`), it may be better to eliminate Lodash as a dependency and simplify the browser test dependencies.

**Comment by ariya** [comment]
Overtaken by #2024 (lodash isn't needed anymore).
