### ISSUE TITLE
Missing ES2019 and ES2020 features

### ISSUE THREAD

**Issue by donnagf** [jquery/esprima#2015]
Looks like this parser doesn't support ES2019 and ES2020. 

I know that ES2018 implementation was scheduled to be implemented 2 years ago, but still not happened.

What's the release plan for ES2020?

**Comment by ariya** [comment]
Hi @donnagf, please take a look at individual issues for the syntax features (if there's any yet, feel free to create one).
As for the release plan, it will be released whenever the implementation is completed (contributions are welcomed!).
