### ISSUE TITLE
ES2020 Optional Chaining

### ISSUE THREAD

**Issue by calvinjuarez** [jquery/esprima#2023]
### Syntax

```js
if (foo?.bar?.baz) {
    console.log('baz exists on foo.bar')
}
```

Which is more-or-less equivalent to the following pre-ES2020 snippet.

```js
if (foo && foo.bar && foo.bar.baz) {
    console.log('baz exists on foo.bar')
}
```

MDN does a fantastic job explaining more thoroughly: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

### Spec

TC39:
https://tc39.es/ecma262/#prod-OptionalExpression
https://github.com/tc39/proposal-optional-chaining

### Tests

https://github.com/tc39/test262/tree/master/test/language/expressions/optional-chaining

**Comment by codebykenny** [comment]
Is this project still being worked on?

Last NPM published released was over 2 years ago. 

Is there a timeline on when esprima will support ES2020
