### ISSUE TITLE
Escaping quotes or single quote in code fails to parse

### ISSUE THREAD

**Issue by Meir017** [jquery/esprima#2038]
### Steps to reproduce

```js
esprima.parse('var a = "b\"c";');
```

### Expected output
valid AST

### Actual output
throws `SyntaxError: Unexpected token`

**Comment by Meir017** [comment]
also acorn fails https://github.com/acornjs/acorn/issues/994

**Comment by ariya** [comment]
@Meir017 you need another backslash to escape the backslash, this is just how string literal works in the code (nothing to do with the parser).
