### ISSUE TITLE
ES2020 Nullish Coalescing

### ISSUE THREAD

**Issue by ljqx** [jquery/esprima#2039]
### Steps to reproduce

```js
esprima.parse('"foo" ?? "bar"')
```

### Expected output

A LogicalExpression with operator `"??"`. Esprima should support [ES2020 Nullish Coalescing](https://github.com/tc39/proposal-nullish-coalescing).

### Actual output

>> Uncaught Error: Line 1: Unexpected token ?

### Relevant references

The proposal: https://github.com/tc39/proposal-nullish-coalescing
Spec: https://tc39.es/ecma262/#sec-binary-logical-operators
Test262: https://github.com/tc39/test262/tree/master/test/language/expressions/coalesce

**Comment by nbcchen** [comment]
Was this fixed? I have 4.0.1 and still have this issue. This is my eslintrc:
```json
{
    "env": {
        "browser": false,
        "node": true,
        "es2021": true
    },
    "extends": [
        "eslint:recommended"
    ],
    "overrides": [],
    "parser": "esprima",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "rules": {
        "semi": [
            "error",
            "always"
        ],
        "prefer-const": "error"
    }
}
```
