### ISSUE TITLE
Fix the Tree files in the tests

### ISSUE THREAD

**Issue by jogibear9988** [jquery/esprima#2077]
I've fixed a bug in esprima, but now some tests fail, cause the exported tree does not match.

Is there a way to newly write the tree files from the tests with the current AST?

**Comment by jogibear9988** [comment]
i debuged the tests now, copied the correct AST via debuger, and inserted into file (but this is much work)

**Comment by ariya** [comment]
Hi @jogibear9988, simply delete the `.json` files and run the tests again. The expected new `.json` should be created automatically.
