### ISSUE TITLE
(spam)

### ISSUE THREAD

**Issue by ghost** [jquery/esprima#2126]
(spam)

**Comment by mauraamandamoni** [comment]
[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)

**Comment by kinjeungndoso** [comment]
[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)





[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)






[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)






[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)

**Comment by bapadewaagenda** [comment]
[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)



[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)




[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)




[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_L6jiBttqs3UB73S5BGQpS51jhnTFOtzTA9pyGNj7yGwfxqsdoUDKhn23hXnQgMEBipPh4uzTOgvkSRKP9NN2UFypMvDQ60_QkWch7hfT88ZObLXPY6Ah4XG-ZT7JVC5c9ES_8Kjxn-KaF7r8ah3yCteDxZnTnZr7c84mzhRq9VHMBhipMiw3R8uLOCw/s16000/375462600-7dd7bec2-14b1-401a-b730-f942d62e9b6d.png)](https://t.co/Yd7RkX2M9a)
