### ISSUE TITLE
`export default function() {}` Should parse the function as a nameless FuncDecl

### ISSUE THREAD

**Issue by jeffmo** [jquery/esprima#311]
Currently esprima parses this as a function expression (probably because, before ES6, only function expressions could be nameless...not function decls).

However, in the `export default` grammar, this should be parsed as a special "HoistableDeclaration" which allows for nameless (yet hoisted) function declarations:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports

**Comment by caridy** [comment]
for reference, `export default function () {}` should parse to:

```
        {
            type: 'ExportDeclaration',
            'default': true,
            declaration: {
                type: 'HoistableDeclaration',
                id: null,
                params: [],
                defaults: [],
                body: {
                    type: 'BlockStatement',
                    body: []
                },
                rest: null,
                generator: false,
                expression: false
            },
            specifiers: [],
            source: null
        }
```

**Comment by jeffmo** [comment]
@caridy : Off the top of your head, could you list off any downstream tools that will break as a result of this so we might reach out? (Obviously it would need to go out with a breaking-version bump as well)

**Comment by caridy** [comment]
let me /cc some people here that might know as well: @eventualbuddha, @guybedford, @benjamn.

obviously this decision might also affect other tools since that function is hoistable, which means they will have to transform it into a FunctionDeclaration, I wonder what 6to5 and esperanto are doing with it, cc: @sebmck, @Rich-Harris.

from the top of my head:

* `es6-module-transpiler` (which will probably require some work downstream in recast), this one is deprecated in favor of esperanto though.

**Comment by mikesherov** [comment]
Despite its backward incompatibility, i still think we need to make this change ASAP, and then land modules in master.

We've already diverged from espree, and have an import token patch not yet there.

Landing a fixed, ready to go module implementation in master should be IMO a top priority. In fact, we should be collaborating with Espree here.

@caridy, @jeffmo, @ariya... Thoughts?

**Comment by ariya** [comment]
Any other reference from the AST produced by e.g. SpiderMonkey or V8?

**Comment by ariya** [comment]
@mikesherov I would recommend a separate discussion of what features need to get into master. There are other careful considerations (dependency e.g. should we do class first, error mesage, etc).

**Comment by jeffmo** [comment]
Agree we should land the fix asap -- especially since this will go into the `harmony` branch which hasn't tracked breaking-changes (or any version bumps) for a while. If we decide to publish the harmony branch somewhere, we'll just need to consider it a breaking change in the version number we choose when we publish...no problem.

OTOH: I understand that a lot of people who use the harmony branch actually use `esprima-fb` because it (a) tracks upstream harmony branch relatively closely and (b) has an npm module  associated with it that is kept up to date with semver-compatible version bumps, etc.

Maybe it would make sense to let `esprima-fb` just take over the `harmony` branch for now to let esprima focus on getting master up to date and at feature parity? At that point, esprima-fb becomes irrelevant modulo fb-specific syntax and it can then switch over to tracking esprima master rather than the harmony branch.

**Comment by jeffmo** [comment]
@ariya : I don't think anyone has fully implemented modules in a VM yet

**Comment by ariya** [comment]
@jeffmo I think if `esprima-fb` focuses on the harmony branch. It's easy enough to pull from another origin for the development of ES6 features on the master branch.

BTW, V8 has already `Parser::ParseExportDeclaration` for a while. We just need to inspect closely what it does.

**Comment by mikesherov** [comment]
@ariya fair enough, created a ticket for tracking blockers to landing modules here: https://github.com/jquery/esprima/issues/313

**Comment by mikesherov** [comment]
My only reservation with abandoning the harmony branch is that people are already submitting PR's against it. I think we can continue to land patches to it until the moment we merge that feature into master. For example @attamusc plans on adding tokens to all the modules tests tonight. I'd like him to be able to do that against `jquery/esprima`. Making contributors contribute to a branch is confusing enough. Having to contribute to a different repo, well, that's even harder.

The key takeaway is that we should no longer publish the harmony branch, and it's continued existence should just serve as a patching ground until we merge that feature into master. Esprima-fb can continue to publish its fork according to it's needs and its consumers. Everyone wins.

**Comment by sebmck** [comment]
@caridy 6to5 and eseperanto uses a fork of acorn which has already been fixed marijnh/acorn#184

**Comment by jeffmo** [comment]
Until master is at full feature parity to harmony, I think we'll need some kind of support for all features in harmony even if those features have been folded in to master. for example, a tool may need class and module support from the parser -- so just because we've folded classes into master (but not yet modules) we'll need to be sure the classes implementation in harmony (or maybe just esprima-fb?) can take bug fixes for both.

**Comment by mikesherov** [comment]
@jeffmo, yes. Bug fixes for both. I misspoke. My key takeaway is that we should consider the harmony branch and development branch and not concern ourselves with BC there.

**Comment by RReverser** [comment]
> for reference, `export default function () {}` should parse to:

@caridy How is `HoistableDeclaration` related to anonymous function? There is no sense in hoisting those.

Also, in your example structure of `HoistableDeclaration` is just the same as `FunctionExpression` (which argument of `export default` actually is), which raises two another questions:

1. Why adding extra type that semantically will make no difference with existing standard representation (for anonymous functions)?
2. Even if we do, how do `export default class {}` represented then (which, according to spec, are also variation of `HoistableDeclaration`)?

**Comment by sebmck** [comment]
Agree completely with @RReverser. Completely against adding `HoistableDeclaration` when another node can be reused. It's already hard enough to transform the SpiderMonkey AST without adding another node type that's semantically equivalent.

**Comment by jeffmo** [comment]
The two are not the same. One is a declaration and one is an expression. Expressions are not hoisted and declarations are -- that is the main difference and the reason this new grammar production was added to the spec.

**Comment by sebmck** [comment]
@jeffmo What's the actual effect of a hoisted anonymous function?

**Comment by jeffmo** [comment]
Additionally, declarations are statements and not expressions -- which has important implications for static analysis that wants to target expressions vs statements (etc)

**Comment by RReverser** [comment]
Agree, but having anonymous function declaration adds implications for static analysis as well, and even breaks compatibility while not adding anything new.

**Comment by jeffmo** [comment]
Heh I probably shouldn't have replied right now -- I'm driving for the next 2-3hours... :p

I'll come back to discuss further a little later

**Comment by caridy** [comment]
@RReverser the reason why Allen added that is cycles. If a module use `export default function () {}` it will require to allocate the `default` identifier, and hoist the declaration, that way importer modules can execute that exported function even when the exporter is not fully initialized. Here is an example:

```
// a.js
import b from "b.js";
export default function () { b(); }

// b.js
import a from "a.js";
export default function () { ...do something else...}
a(); // execute default export from a.js
```

independently of how your pipeline digest those two modules, order should not matter, it should work, and the reason why it works is because it hoists both functions. But an anonymous function (function expressions) will never hoist, that's why he added `HoistableDeclaration`.

**Comment by caridy** [comment]
If you want the desugar version of this, it will be something like this:

```
function mod$default() {}
export {mod$default as default};
```

where `mod$default` is hoisted and artificial obviously (otherwise you could update the value of the default binding), and that's not the same as in:

```
var mod$default = function () {};
export {mod$default as default};
```

**Comment by sebmck** [comment]
@caridy I don't think anyone's proposing that it not be represented at all, only about how it should be.

**Comment by michaelficarra** [comment]
@jeffmo @caridy: The semantics should not even be coming into play in this conversation. It is fine to re-use the node because we're creating an AST where the semantics of each node is dependent upon its context. The only reason not to re-use FunctionExpression would be either if we had a completely context insensitive AST or if we wanted to have some sort of replaceability property for transformation a la Shift AST.

**Comment by sebmck** [comment]
There are many places where the Spidermonkey AST falls short with it's representation (no `BindingIdentifier` is the biggest for me) but I don't think this should be the first step in changing that.

**Comment by jeffmo** [comment]
Just to be sure we're all on the same page: I wouldn't want a new "HoistableDeclaration" node here -- simply to parse the function as a nameless declaration as it is described in the spec (and treated in its semantics).

The fact is that there is now a form of function declarations that can be nameless. Any new grammar productions that are added to the Lang will indeed require updates to static analysis...such is the nature of adding features to a language. It would be odd in the long-tail of the future if we side-stepped the structure of the spec here for some reason.

In fact, there is nothing preventing future forms of the spec from using nameless function decls ("HoistedDeclartions") in other positions...so this is a new aspect of the Lang that we all just need to incorporate in our respective tooling to stay up to date with new features in the Lang.

Additionally, it is important that tools be able to distinguish statements from expressions for all sorts of reasons. one such reason would be exactly the one described by @caridy: the need to pre-scan a scope for hoisted bindings. Sure such logic could special-case export decls with expressions in them...but it would be an odd divergence between the AST and what the spec describes.

I think I understand the desire to minimize necessary changes, but I think this would simply be an odd historical divergence in the AST of we didn't fix this now.

**Comment by sebmck** [comment]
@jeffmo You already have to special case a lot of stuff when statically analysing a scope for bindings anyway, and while the introduction may make it easier in this specific case I think consistency is key. I personally don't think it's a compelling enough reason to introduce another node type when the representation has been so conservative thus far. I'm willing to concede if the consensus is that it should be added but I'm not convinced.

**Comment by sebmck** [comment]
@jeffmo You already have to special case a lot of stuff when statically analysing a scope for bindings anyway, and while the introduction may make it easier in this specific case I think consistency is key.

**Comment by jeffmo** [comment]
Let's be careful not to make the argument that because some special cases exist, more are acceptable.

But even if you don't buy the special-casing argument, wouldn't you agree that divergence from the spec'd grammar structure in one place would be pretty surprising if you were approaching this AST for the first time?

**Comment by jeffmo** [comment]
I guess I'm saying that consistency depends on the lens in which you view things. If we stuck with func expr, we would be inconsistently congruent with the spec.

I agree that there's an argument to be made that the spec'd grammar is a little surprising if you come at it with background knowledge of ES5 or before

**Comment by sebmck** [comment]
@jeffmo I deleted my comment shortly after posting because I didn't articulate myself well enough. I completely agree with people being surprised with the divergence in spec grammar.

But as @michaelficarra mentioned, the semantics of each node is dependent on the context already. There are so many things wrong with the Spidermonkey AST associated with static analysis and transformation due to this (many of which the Shift AST has fixed) that divergence from these already established norms is harmful IMO.

**Comment by jeffmo** [comment]
At this point in the convo I think it would be best to understand the implications to your tooling that we'd be incurring if we switched to func decl. I'm happy to keep an open objective mind if it sounds like such implications would cost more than the potential confusion about spec consistency in the future. (And please don't forget that I too have several feet in this game too...so I'll also have to live with the implications of however we proceed).

So far I have been able to model scope and symbol analysis rather cleanly using the declaration form in the export default position...but maybe you're doing something for which it would be much harder?

**Comment by jeffmo** [comment]
At this point in the convo I think it would be helpful to understand the implications to your tooling that we'd be incurring if we switched to func decl. I'm happy to keep an open objective mind if it sounds like such implications would cost more than the potential confusion about spec consistency in the future. (And please don't forget that I too have several feet in this game too...so I'll also have to live with the implications of however we proceed).

So far I have been able to model scope and symbol analysis rather cleanly using the declaration form in the export default position...but maybe you're doing something for which it would be much harder?

**Comment by sebmck** [comment]
The main issue is the optional `id`. Take the following (simplified) example which is used to split up default function declaration exports.

```javascript
node; // ExportDeclaration
var declar = node.declaration;
if (node.default && isFunctionDeclaration(declar)) {
  node.declaration = declar.id;
  return [declar, node];
}
```

This is done to simplify the transformation later on and to hoist the export to the top so circular function dependencies work.

With the `HoistableDeclaration` change it'd quite trivially become:

```javascript
node; // ExportDeclaration
var declar = node.declaration;
if (node.default && isHoistableDeclaration(declar)) {
  declar.id = declar.id || generateUid();
  node.declaration = declar.id;
  return [declar, node];
}
```

This is a contrived example and while finding examples actually discovered that this change would be much easier than I expected. Thankfully I have a helper that's used to match both `FunctionDeclaration` and `FunctionExpression` so adding `HoistableDeclaration` to that list would be trivial. As I said previously (in my now deleted comment), I'm happy to concede if the consensus is that it'll make it vastly easier in other cases.

I'm mainly concerned with deviating from the Mozilla Parser API and I'm not sure why the AST structure discussion is even happening here. What's the goal? Are we defining our own spec or is the plan to follow the Mozilla Parser API? If the latter then this discussion should be taken up on Bugzilla, otherwise there needs to be more discussion around why a "fork" is even necessary as well as additional bureaucracy to avoid hurting the ecosystem and to maintain interop.

**Comment by jeffmo** [comment]
> Are we defining our own spec or is the plan to follow the Mozilla Parser API?

That's a great point -- we should do whatever the API spec states. I don't know if this has been defined yet, but if I may speculate, I'd imagine Firefox will spit out whatever its internal parser generates. I would be pretty surprised if they arbitrarily converted their declaration to an expression...but point taken and agreed: We should do whatever the API spits out. I think the only issue is that the spec isn't super well-defined. Does the FF API support modules yet?

**Comment by sebmck** [comment]
Just want to note as well that I don't think forking should be ruled out (collaboration is obviously highly preferable). But there are so many areas for improvement that would make static analysis and transformation **signifcantly** easier. (As mentioned before I would **love** `BindingIdentifier`)

**Comment by michaelficarra** [comment]
Unfortunately, I don't think SpiderMonkey supports import/export declarations yet.

@sebmck: Shift's ES6 branch has BindingIdentifier, it's implemented on our parser's ES6 branch, and it is *wonderful*. :stuck_out_tongue_winking_eye:

**Comment by sebmck** [comment]
@michaelficarra I've been looking into Shift and it's sooo good, corrects so many mistakes.

I really think that closer collaboration or a fork needs to be considered. There are going to be more issues like this in the future and we need to be able to parse this stuff before vendors implement it.

**Comment by mikesherov** [comment]
so what's the conclusion here? Seems like a third AST separate from both SpiderMonkey and Shift would be bad. 

Who at Mozilla can we loop in here?

**Comment by jeffmo** [comment]
Cc @dherman

**Comment by RReverser** [comment]
> Unfortunately, I don't think SpiderMonkey supports import/export declarations yet.

It actually does, just not all the final extensions. @impinball's proposal on import/export AST nodes was the closest one to SpiderMonkey representation.

**Comment by jeffmo** [comment]
After today's discussions, it sounds like we're going to be moving the source of truth for the AST spec into it's own repo and call that `ESTree`. @dherman is working on setting up this repo now and porting the spec to markdown.

Once we have that, we can bikeshed this issue over in that repo. We really should do that before committing anything though, because this is no longer only about esprima (it's also about what spidermonkey and acorn and others who which to conform to the ESTree spec want out of it).

As for me: I still think FunctionExpression is the wrong thing in the long term. I think it exposes us to vulnerabilities related to diverging from the spec (including any future updates that might conceivably happen to function decls/exprs in the future) and it does so simply in the name of deferring the pain of having to deal with nameless function decls until they [potentially] become valid in other positions in the grammar as well in the future.

That said, in this very specific position at this specific point in time, I don't see the tangible harm. So if it pleases the masses (including anyone who wants to chime in on the discussion in the `ESTree` repo), I'm willing to reluctantly concede here.

**Comment by michaelficarra** [comment]
@jeffmo: Thanks for the update. Please post a link to ESTree when it becomes available.

**Comment by mikesherov** [comment]
https://github.com/estree/estree

On Wed, Feb 11, 2015 at 10:40 PM, Michael Ficarra <notifications@github.com>
wrote:

> @jeffmo <https://github.com/jeffmo>: Thanks for the update. Please post a
> link to ESTree when it becomes available.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/esprima/issues/311#issuecomment-74012575>.
>



-- 
Mike Sherov

**Comment by michaelficarra** [comment]
For the Shift parser, I will be proposing that we use FunctionDeclaration nodes in this position with an Identifier with value `*default*`. This is consistent with the name the spec uses:

> NOTE "\*default\*" is used within this specification as a synthetic name for hoistable anonymous functions that are defined using export declarations.

See the `[[LocalName]]` column of [Table 39](https://people.mozilla.org/~jorendorff/es6-draft.html#table-39).

**Comment by sebmck** [comment]
@michaelficarra I'd imagine that has it's own set of problems as it complicates things like scope tracking since you wont be able to assume that all `FunctionDeclaration`s create bindings?

**Comment by michaelficarra** [comment]
It actually does create that binding. There's just no way for you to reference it. But proper scope analysis should represent it. It's completely consistent.

**Comment by sebmck** [comment]
Oh right, since `default` is a keyword.

**Comment by michaelficarra** [comment]
And it has asterisks in it.

**Comment by sebmck** [comment]
How I missed those I have no idea

**Comment by ikarienator** [comment]
That's just the way the spec represents it. I don't think you can even
refer it with the starred symbol.

**Comment by michaelficarra** [comment]
That's what we were saying, Bei.

**Comment by RReverser** [comment]
Not sure that having invalid identifier (with asterisks) in any `Identifier` node is a good idea for consumers that aren't aware of this (same problems as with anonymous `FunctionDeclaration` - breaking backward compatibility).

**Comment by nzakas** [comment]
+1 to @RReverser. I think it would make more sense to have a null ID than a contrived one.

**Comment by caridy** [comment]
+1 to @RReverser IMO most of those artifacts in the spec (e.g.: `*default*`) are meant to simplify algo steps, but they are not implementation detail. What if tomorrow we come up with a new hoistable declaration that declares a ``[[LocalName]]`?

**Comment by ariya** [comment]
The harmony branch is not maintained anymore.
Meanwhile, in the master branch, this is already parsed as `ExportDefaultDeclaration`, pretty much as specified in ESTree:

```
{ type: 'ExportDefaultDeclaration',
  declaration: 
   { type: 'FunctionDeclaration',
     id: null,
     params: [],
     defaults: [],
     body: { type: 'BlockStatement', body: [] },
     generator: false,
     expression: false } }
```
