### ISSUE TITLE
`export default` should only take a class decl, generator decl, or assignment expression

### ISSUE THREAD

**Issue by jeffmo** [jquery/esprima#312]
Currently the parser will accept any source-element in the final position of an `export default`. This is wrong as `export default foo;` (as just one example) should not parse since `foo` is not an assignment expression.

**Comment by michaelficarra** [comment]
No, any `AssignmentExpression` is allowed following `export default`. The spec even uses the example `export default 42`.

```
ExportDeclaration :
  export * FromClause ;
  export ExportClause FromClause ;
  export ExportClause ;
  export VariableStatement
  export Declaration
  export default HoistableDeclaration[Default]
  export default ClassDeclaration[Default]
  export default [lookahead ∉ {function, class}] AssignmentExpression[In] ;
```

**Comment by jeffmo** [comment]
Right, but assignment expression (if I'm reading correctly...and it seems I'm good at not reading the spec correctly sometimes) can only be a `LeftHandSideExpression[?Yield] = AssignmentExpression[?In, ?Yield]` or `LeftHandSideExpression[?Yield] AssignmentOperator AssignmentExpression[?In, ?Yield]`:

```
AssignmentExpression[In, Yield] :
  ConditionalExpression[?In, ?Yield]
  [+Yield] YieldExpression[?In]
  ArrowFunction[?In, ?Yield]
  LeftHandSideExpression[?Yield] = AssignmentExpression[?In, ?Yield]
  LeftHandSideExpression[?Yield] AssignmentOperator AssignmentExpression[?In, ?Yield]
```

Indeed I see the `export default 42` example in the spec...am I reading things wrong? Or is that a spec bug?

**Comment by michaelficarra** [comment]
But `AssignmentExpression` can be a `ConditionalExpression`, `ConditionalExpression` can be a `LogicalORExpression`, etc. all the way down to `PrimaryExpression`, which includes number literals. Then, if you want, grouping parentheses lift you all the way back up to the top (sequence operator, which has the lowest precedence) to fall back down through operations of increasing precedence again.

Makes sense?

**Comment by jeffmo** [comment]
Yep yep, nice catch. Turtles all the way down!
