### ISSUE TITLE
ES7 feature: Trailing commas in function argument lists.

### ISSUE THREAD

**Issue by kaustubh-karkare** [jquery/esprima#316]
I'd like to add a pull request to allow trailing commas in the list of arguments in function calls, which will help with VCS authorship attribution.

ES7 Proposals: https://github.com/tc39/ecma262
Specific proposal for this change: https://github.com/jeffmo/es-trailing-function-commas

**Comment by ariya** [comment]
Since the harmony branch is gone and Facebook is moving away from its fork of Esprima, I'd say we put this on hold. In addition, looking at https://github.com/tc39/ecma262, it seems that trailing commas in function call expressions is still at Stage 1.

**Comment by michaelficarra** [comment]
@jeffmo do you have any interest moving that proposal forward at next week's meeting?

**Comment by jeffmo** [comment]
@michaelficarra https://github.com/tc39/agendas/pull/110
