### ISSUE TITLE
Type of the object property `default` was "Keyword" instead of "Identifier".

### ISSUE THREAD

**Issue by yakimchuk** [jquery/esprima#317]
I did try tokenize this code:

```js
var argv = parse(['moo'] , {
        boolean: [
            't' , 'verbose'
        ],
        default: {
            verbose: false,
            t: false
        }
    });
```

In result, token of identifier "default" was "Keyword" instead of "Identifier".

**Comment by yakimchuk** [comment]
http://esprima.org/demo/parse.html?code=var%20argv%20%3D%20parse(%5B'moo'%5D%20%2C%20%7B%0A%20%20%20%20%20%20%20%20boolean%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20't'%20%2C%20'verbose'%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20default%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20verbose%3A%20false%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20t%3A%20false%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B

**Comment by ikarienator** [comment]
Unfortunately there is little we can do about it. You may want to parse it use a list of tokens like `esprima.parse(source, {tokens: true});`. I personally wish no programming language contains any contextual keywords/identifier, that is, the kind of a token only depends on it's content after it's tokenized. But JavaScript has contextual tokens. Not only that, it requires re-tokenization in some cases (regular expression and in ES6, template literal tail), which makes context-free tokenization theoretically impossible. As a conclusion, the result of the tokenization for JavaScript is not guaranteed to be correct and you should not assume any context-free tokenizer can.

**Comment by yakimchuk** [comment]
You can detect type of expression which includes a token?

If you can: you can change type of token after tokenization, or in progress of tokenization.
If no: i think, without reworking of module (i guess currently you are not using method "parse" for tokenization of the code), you can't do this.

**Comment by ariya** [comment]
@ikarienator Is this like the previous issue filed here: https://code.google.com/p/esprima/issues/detail?id=481?

**Comment by ariya** [comment]
Due to the limitation (tokenization does not have enough context), we can't do much and thus we'll keep the situation as it currently is.
