### ISSUE TITLE
Add a directive flag to ExpressionStatement to indicate a directive prologue

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#318]
In the current syntax tree, a directive such as `"use strict"` will appear as `ExpressionStatement`. A tool that consumes the tree and needs to be aware of the strict mode will have to perform an extra step to figure out whether such an ExpressionStatement is representing a directive or not.

In this proposal, a new flag `directive` is added to `ExpressionStatement`. The value is set to `true` for a directive prologue.

The current state:

```
> esprima.parse('"use strict"').body[0]
{ type: 'ExpressionStatement',
  expression: 
   { type: 'Literal',
     value: 'use strict',
     raw: '"use strict"' } }
```

If this proposal is implemented, it becomes:

```
> esprima.parse('"use strict"').body[0]
{ type: 'ExpressionStatement',
  expression: 
   { type: 'Literal',
     value: 'use strict',
     raw: '"use strict"' },
  directive: true }
```

Additional resources:

* ECMAScript 5.1 [Section 14.1](http://es5.github.io/#x14.1) on *Directive Prologues and the Use Strict Directive*
* Previous Esprima discussion: https://code.google.com/p/esprima/issues/detail?id=330.
* SpiderMonkey issue: https://bugzilla.mozilla.org/show_bug.cgi?id=791294

**Comment by ariya** [comment]
To give a different perspective, [Shift AST Specification](https://github.com/shapesecurity/shift-spec) introduces a different node called `Directive` (which could be `UseStrictDirective` or `UnknownDirective`).

For Esprima, in the spirit of staying as close as possible to the existing AST format, a flag is less intrusive.

**Comment by mikesherov** [comment]
LGTM

**Comment by gibson042** [comment]
I agree with the argument for augmenting existing nodes rather than inventing new types. But is this intended as a stopgap while waiting for the AST format to catch up, or as a proposed extension to it? If the latter, I'd prefer the value to indicate type of directive rather than boolean presence, for flexibility with covering potential future language changes.

**Comment by mikesherov** [comment]
@gibson, the `value` property will already contain what directive it is. Adding a type would be explicit, but is likely duplicative and creates even more divergence from SpiderMonkey.

**Comment by mikesherov** [comment]
Oops, meant @gibson042

**Comment by gibson042** [comment]
I suppose you're right; it's just a matter of tradeoffs in the goal to simplify this process:
> A tool that consumes the tree and needs to be aware of the strict mode will have to perform an extra step to figure out whether such an ExpressionStatement is representing a directive or not.

**Current**:
```js
if ( inDirectiveProlog ) {
    if ( currentNode.type === "Literal" && typeof currentNode.value === "string" ) {
        // "A Use Strict Directive may not contain an EscapeSequence or LineContinuation"
        if ( currentNode.raw.slice( 1, -1 ) === "use strict" ) {
            strictMode = true;
        }
    } else {
        inDirectiveProlog = false;
    }
}
```

**Boolean `directive`**:
```js
strictMode = currentNode.directive === true &&
    // "A Use Strict Directive may not contain an EscapeSequence or LineContinuation"
    currentNode.raw.slice( 1, -1 ) === "use strict";
```

**Non-Boolean `directive`**:
```js
strictMode = currentNode.directive === "use strict";
```

**Comment by mikesherov** [comment]
@gibson042, no slice needed... Use the value property. Still a bit clunkier, but avoids us having to duplicate the info.

`currentNode.directive && currentNode.value === 'use strict')`

**Comment by gibson042** [comment]
The value property decodes escape sequences, making it impossible to distinguish valid `"use strict"` from invalid equivalents like `"use\u0020strict"`.

http://esprima.org/demo/parse.html?code=%22use%20strict%5C%0A%22%3B%0A%22use%5Cu0020strict%22%3B

**Comment by michaelficarra** [comment]
@mikesherov: The value doesn't represent the original representation. If escapes are used anywhere, those escapes are significant and make it a different directive. The non-boolean value that @gibson042 suggests would represent the escapes used, which is the same as slicing the string delimiters off the `raw` value.

**Comment by mikesherov** [comment]
fair enough. @ariya, thoughts?

**Comment by ariya** [comment]
Unfortunately the `raw` property also does not capture any escape sequences. I think it's fair to choose a string as the value of the `directive` property.

**Comment by ariya** [comment]
Moving this to #1006.
