### ISSUE TITLE
Enhance the comment-attaching algorithm

### ISSUE THREAD

**Issue by ikarienator** [jquery/esprima#319]
This algorithm currently tests if the comment "belongs" to an AST tree if the range of the AST covers the comment. This end up giving the following result:

The comment of 
```js
a  //x
```

is attached to the `ExpressionStatement`, but the comment of
```js
a; //x
```

is attached to the `FunctionBody`.

**Comment by michaelficarra** [comment]
I think you mean `ExpressionStatement`, not `FunctionBody`?

**Comment by ikarienator** [comment]
I'm not sure which one should be attached to.

**Comment by michaelficarra** [comment]
But the SpiderMonkey AST doesn't have FunctionBody. You've created an issue on esprima.

**Comment by ikarienator** [comment]
Ah, I see... It's the `body` of the program which is an Array...

I think It should be `Expression` and `ExpressionStatement`.

**Comment by ikarienator** [comment]
I shall close this now for the issue number bump.
